### PR TITLE
fix #965 Prevent handle sink usage after error/complete

### LINKED ISSUE #965: Tighten up FluxHandle operator to not allow multiple signals
Currently handle does not allow multiple next() signals, but it does allow `error()+next()`, `error()+complete()` etc. Ideally this is tighen up to throw `IllegalArgumentException` in all cases that don't make sense.

### PR DESCRIPTION
**Pull request by simonbasle**
This commit ensures handle will propagate an exception both when next()
is used twice but also when it is called after complete() or error() in
the handle callback.

### CODE REVIEW

**Comment by smaldini** [comment]
Why would next() after stop trigger an error here where we usually ignore it in most scenario, I agree that error should not be ignored, similar to the logging and throwing we do usually in onNext/onError. That means we should safely drop next whereas calling error after done is set should throw.

**Comment by simonbasle** [comment]
This change stems from an inconsistency in the handle API usage, where 2 subsequent calls to `sink.next()` will throw and thus trigger `onError`, but a call to `sink.error()` followed by `sink.next(v)` will happily emit `v` and propagate the error (same with complete).

It felt like it would be more consistent to fail fast on this API misuse, rather than accepting it or dropping.

Note that the extra `stop` is needed to distinguish between an upstream error/completion and the explicit use of `sink.error/complete` in the handler. Without this I'd get some instances where the `Flux` wouldn't complete, because the operator was tricked into thinking it had already emitted a terminal signal to its `actual` (`done == true`) where it had actually just seen a `sink.complete()` call.

File: reactor-core/src/test/java/reactor/core/publisher/FluxHandleTest.java [hunk 1]
```diff
@@ -510,4 +512,102 @@ public void contextTestFilterHide() {
...
+		StepVerifier.create(Flux.just(1)
+		                        .filter(i -> true)
+		                        .handle((v, sink) -> {
+			                        sink.error(new NullPointerException("boom"));
+			                        sink.next(2);
+		                        }))
+		            .verifyErrorSatisfies(e -> assertThat(e).isInstanceOf(IllegalStateException.class)
+		                                                    .hasMessage("Cannot emit after a complete or error"));
+	}
+
```
Comment (dfeist) [inline reactor-core/src/test/java/reactor/core/publisher/FluxHandleTest.java]: Be good to add the other cases while here:
- error() + error()
- next() + next()
- complete() + error()

**Comment by simonbasle** [comment]
@smaldini can you re-review this after today's sync? to reiterate, this is about internal consistency of the `handle` `Sink` (why would `next next` fail but not `error next`?) rather than its consistency with `FluxSink` (as handle naturally has more restriction than create)
