### PR TITLE
fix #2436 Polish some 3.2 JUnit5 tests and compiler options

### LINKED ISSUE #2436: JUnit5 migration polishing tasks on 3.2.x
Follow-up to #2344 / #2395, polishing things on 3.2.x

 - [ ] Fix compile options that were mistakenly changed in `JavaConventions` (`maxwarns` and `maxerrs` to be set to 500 so as to eg. limit the number of back and forth when fixing an common usage pattern change across all tests)
 - [ ] in `ExceptionTest`, move the `@BeforeEach` higher in the file
 - [ ] in `FluxReplayTest`, move the `vts` field + `@BeforeEach`/`@AfterEach` higher in the file (before first `@Test`)
 - [ ] use `@Tag` in `GuideTest#populateDebug()` rather than display name
 - [ ] fix bad line breaks in `SchedulersTest`, clean up dead code and static classes/field positions in the file
 - [ ] fix bad line breaks in `AbstractSchedulerTest`

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

File: reactor-core/src/test/java/reactor/core/ExceptionsTest.java [hunk 1]
```diff
@@ -38,6 +39,16 @@
...
 public class ExceptionsTest {
 
+	//used for two addThrowableXxx tests lower in the class
+	volatile @Nullable Throwable addThrowable;
+	static final AtomicReferenceFieldUpdater<ExceptionsTest, Throwable> ADD_THROWABLE =
+			AtomicReferenceFieldUpdater.newUpdater(ExceptionsTest.class, Throwable.class, "addThrowable");
+
+	@BeforeEach
+	public void resetAddThrowable() {
+		addThrowable = null;
```
Comment (ericbottard) [inline reactor-core/src/test/java/reactor/core/ExceptionsTest.java:49]: Not needed since each test gets a new instance

File: reactor-core/src/test/java/reactor/core/publisher/FluxReplayTest.java [hunk 2]
```diff
@@ -41,6 +41,22 @@
...
+
+	@BeforeEach
+	public void vtsStart() {
+		//delayElements (notably) now uses parallel() so VTS must be enabled everywhere
+		vts = VirtualTimeScheduler.getOrSet();
+	}
+
+	@AfterEach
+	public void vtsStop() {
+		vts = null;
```
Comment (ericbottard) [inline reactor-core/src/test/java/reactor/core/publisher/FluxReplayTest.java:54]: Not needed as each test gets a new instance of FluxReplayTest

File: reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java [hunk 3]
```diff
@@ -623,10 +624,6 @@ public void assertRejectingScheduler(Scheduler scheduler) {
 		}
 	}
 
-	//private final int             BUFFER_SIZE     = 8;
-	private final AtomicReference<Throwable> exceptionThrown = new AtomicReference<>();
-	private final int                        N               = 17;
```
Comment (ericbottard) [inline reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java:628]: I assume N was unused?

**Review by bsideup — APPROVED** [review]

**Review by ericbottard — CHANGES_REQUESTED** [review]

File: reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java (hunk 3 above)
Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java:628]: yes, it was indeed

**Review by aneveu — APPROVED** [review]
