### PR TITLE
fix #2362 Prevent ConcurrentModificationEx on bufferPredicate discard

### LINKED ISSUE #2362: BufferPredicateSubscriber not thread safe
As far as I understand, `reactor.core.publisher.FluxBufferPredicate.BufferPredicateSubscriber` violates the [reactive-streams specification](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/README.md#specification) in a few ways;

> 2.8 A Subscriber MUST be prepared to receive one or more onNext signals after having called Subscription.cancel() if there are still requested elements pending [see 3.12]. Subscription.cancel() does not guarantee to perform the underlying cleaning operations immediately.

Ok, so the `BufferPredicateSubscriber` does in fact accept more `onNext` signals after `cancel`, but the behaviour is kind of undefined, and the ongoing `cancel`-operation may fail due to the `onNext` signal.

> 3.5 Subscription.cancel MUST respect the responsivity of its caller by returning in a timely manner, MUST be idempotent and MUST be thread-safe.

`BufferPredicateSubscriber#cancel` is clearly not thread safe with respect to other interactions on for instance `onNext`. As `cancel` iterates over the buffer to dispose its elements (via `Operators.onDiscardMultiple`), and `onNext` adds new elements to the buffer. This causes `ConcurrentModificationException` to be thrown (at least when the underlying buffer is a `ArrayList` which it is by default)

> 3.15 Calling Subscription.cancel MUST return normally.

As mentioned above, cancel may throw `ConcurrentModificationException` if there are `onNext` signals that overlaps with the `cancel` operation.

## Expected Behavior

* `onNext` signals that does _not_ happen before `cancel` should be discarded (not sure about the exact expected behaviour here, but this is how `reactor.core.publisher.FluxOnBackpressureBuffer.BackpressureBufferSubscriber` works).
* `BufferPredicateSubscriber#cancel` MUST be thread-safe.
* `BufferPredicateSubscriber#cancel` MUST return normally.

## Actual Behavior

`BufferPredicateSubscriber#cancel` may throw `ConcurrentModificationException` if there are `onNext` signals that overlaps with the `cancel` operation. 

## Steps to Reproduce

I did an attempt to reproduce this in the context of micrometer (since that is where we observed the effects of this issue). Code to reproduce the bug is available here; https://github.com/tommyk-gears/micrometer-2238. It triggers this error quite frequently, but it is not a proper test case - it just exercises/provokes the code a bit but the test code doesn't really check if any error occurs. As the test was written on top of micrometer it might be a bit convoluted in the context of reactor-core, but I believe the problem is pretty obvious by just reading the source of `BufferPredicateSubscriber`.

Also, more context can be found in a corresponding micrometer issue; https://github.com/micrometer-metrics/micrometer/issues/2238

## Possible Solution

I suppose one could take inspiration from `reactor.core.publisher.FluxOnBackpressureBuffer.BackpressureBufferSubscriber`.

## Your Environment

* Reactor version(s) used: 3.3.9-RELEASE
* JVM version (`java -version`): 
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
* OS and version (eg `uname -a`):
Darwin LeoAdmins-MacBook-Pro-4.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by simonbasle**
This commit adds some internal synchronization of the buffer in
FluxBufferPredicate in order to ensure that cancellation racing with
onNext doesn't trigger a ConcurrentModificationException (due to the
buffer being iterated by onDiscard while onNext adds an element to it).

### CODE REVIEW

**Comment by simonbasle** [comment]
when forward-merging, will need a few modifications (added `cleanup()` in 3.3, removed `this.ctx`...)

File: reactor-core/src/main/java/reactor/core/publisher/FluxBufferPredicate.java [hunk 1]
```diff
@@ -176,8 +178,13 @@ public void request(long n) {
 
 		@Override
 		public void cancel() {
+			C b;
+			synchronized (this) {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/FluxBufferPredicate.java:182]: why not getAndSet?

File: reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java [hunk 2]
```diff
@@ -912,6 +916,153 @@ public void discardOnError() {
...
+
+			@Override
+			protected void hookOnNext(ArrayList<AtomicInteger> value) {
+				receivedCounter.addAndGet(value.size());
+			}
+		};
+	}
+
+	@Test
+	public void discardRaceWithOnNext_bufferAdds() {
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java:936]: this one could _really_ use a stress test instead

Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java:936]: no time for this unfortunately, too much on my plate. can you open a follow up issue?

File: reactor-core/src/main/java/reactor/core/publisher/FluxBufferPredicate.java (hunk 1 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxBufferPredicate.java:182]: I should probably eliminate the volatile above. overall for this issue `getAndSet` doesn't cut it because the `onNext` could still capture the `buffer` just in time and perform the `add` despite cancel swapping out the buffer.

File: reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java (hunk 2 above)
Comment (bsideup) [reply reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java:936]: mhm... okay 😅

Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java:936]: (plus jcstress was added in master, this is targeting 3.2 so it would have to be done separately anyway)

Comment (bsideup) [reply reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java:936]: Maybe we can remove the test from this PR and add it in master later as a follow up? These really make the test execution longer and more heavyweight...

**Review by bsideup — APPROVED** [review]
approving with a note on the stress tests (and an idea to not introduce them in 3.2, but with JCstress on master)

File: reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java (hunk 2 above)
Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java:936]: I can do smaller loops, to at least keep a minimum of testing while not impacting the time too much?

Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java:936]: to be honest the worst offender seems to be pre-existing `requestRaceWithOnNextLoops` (32s)
