### PR TITLE
Fixes #282 When FluxHandle sink.error(ex) is used the data value is n…

### LINKED ISSUE #282: When FluxHandle sink.error(ex) is used the data value is not passed to onOperatorError hook
My understanding is that the following should really behave the same. (should they?)

`.handle((d, sink) -> d.error(exception))`

`.handle((d, sink) -> { throw Exceptions.propagate(ex); }`

They don't because when `error(exception)` is used `Operators.onOperatorError()` is called in the `error(t)` method rather than in `tryOnNext` before calling `actual.onError()` where the data value is available in context.

### PR DESCRIPTION
**Pull request by dfeist**
…ot passed to onOperatorError hook enhancement.

### CODE REVIEW

File: src/main/java/reactor/core/publisher/FluxHandle.java [hunk 1]
```diff
@@ -107,7 +107,7 @@ public void onNext(T t) {
 			if(done){
 				s.cancel();
 				if(error != null){
-					actual.onError(error);
+					actual.onError(Operators.onOperatorError(s, error, t));
```
Comment (dfeist) [inline src/main/java/reactor/core/publisher/FluxHandle.java]: You're right, not sure how i missed those.  Just pushed commit with fix.

**Comment by simonbasle** [comment]
@dfeist can you just convert the spaces to tabs in the tests (yeah tabs are not ideal on github but that's the indentation we went with originally 😄 )
after that, it should be good to go 👍
