### PR TITLE
fix #1793 Reject Context.of calls with duplicate keys

### LINKED ISSUE #1793: Context.of() not checking for duplicate keys
### Expected behavior
Creating an instance of `Context`  using `Context.of()` method should check for duplicate keys.

### Actual behavior
`Context.of()` currently allows duplicate keys and when an update to the key is made, only the 1st entry matching the key is updated. When the context is read, the last argument matching the key in `Context.of()` is returned as the value for the key.

For e.g. 
```
Context context = Context.of(key, "value1", key, "value2"); 
context.put(key, "value3");
```
This will result in `key` returning `value2` instead of `value3` which was the last updated value.

### Steps to reproduce
```
import java.util.List;
import java.util.Map.Entry;
import java.util.stream.Collectors;
import reactor.core.publisher.Mono;
import reactor.util.context.Context;

public class TestReactorContext {
    public static void main(String[] args) {
        TestReactorContext test = new TestReactorContext();
        String key = "name";

        // Same key with multiple values. Last updated value is "Baz"
        Context context = Context.of(key, "John", key, "Doe");
        context = context.put(key, "Foo");
        context = context.put(key, "Bar");
        context = context.put(key, "Baz");

        String result = test
            .greet("Hello, ")
            .subscriberContext(context)
            .block();

        // Expected: "Hello, my name is Baz."
        // Actual: "Hello, my name is Doe."
        System.out.println(result);
    }

    Mono<String> greet(String prefix) {
        // convert subscriberContext coming into this method into a string
        return Mono.subscriberContext()
            .map(this::getMessage)
            .flatMap(message -> prettyPrint(prefix, message));
    }

    private Mono<String> prettyPrint(String prefix, String context) {
        String msg = prefix + context;
        return Mono.just(msg);
    }

    private String getMessage(Context context) {
        List<Entry<Object, Object>> entries = context.stream().collect(Collectors.toList());
        System.out.println("Reactor context size = " + entries.size()); // size is 1
        StringBuilder contextBuilder = new StringBuilder();
        entries.stream().forEach(
            entry -> contextBuilder.append("my ").append(entry.getKey()).append(" is ").append(entry.getValue()).append("."));
        return contextBuilder.toString();
    }
}

```
### Reactor Core version
3.2.3.RELEASE

### JVM version (e.g. `java -version`)
JDK 8

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

File: reactor-core/src/main/java/reactor/util/context/Context.java [hunk 1]
```diff
@@ -72,6 +94,7 @@ static Context of(Object key, Object value) {
 	 */
 	static Context of(Object key1, Object value1,
 			Object key2, Object value2) {
+		checkDuplicateKeys(key1, key2);
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/util/context/Context.java]: AFAIR this creates an allocation (an array of varargs), while the implementation is as simple as `if (key1.equals(key2))`.
Maybe we shouldn't use the generic check method here?

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/util/context/Context.java]: good point, originally intended to limit the impact for the 2 k/v case (which is likely one of the most used along with 1 k/v and `empty()` cases) but moving that special case from `checkDuplicateKey` to the main method would save additional allocation.

File: reactor-core/src/main/java/reactor/util/context/Context.java [hunk 2]
```diff
@@ -89,6 +116,13 @@ static Context of(Object key1, Object value1,
 	static Context of(Object key1, Object value1,
 			Object key2, Object value2,
 			Object key3, Object value3) {
+		//prefer direct check for the simple 3 keys case over checkDuplicateKeys (saves up 1 array allocation)
+		if (key1.equals(key2) || key1.equals(key3)) {
```
Comment (robotmrv) [inline reactor-core/src/main/java/reactor/util/context/Context.java]: there is no null check so it is possible to catch NPE.  
Intresting. ContextX constructors allow null keys and values but put() method does not

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/util/context/Context.java]: mmh that is indeed a shortcoming, although the IDE should report this kind of usage (as part of a `@NonNullApi`). let me open a separate issue to enforce null checks in the constructors.

File: reactor-core/src/main/java/reactor/util/context/Context.java [hunk 3]
```diff
@@ -61,6 +62,28 @@ static Context of(Object key, Object value) {
...
 	}
 
+	/**
+	 * Checks for duplicate keys. This method is intended for a short space of keys in the
+	 * 4-10 range. Shorter number of keys can easily be checked with direct equals comparison(s),
+	 * saving on allocating a vararg array (although this method would still behave correctly).
+	 *
+	 * @param keys the keys to check for duplicates, by looping over the combinations
+	 */
+	static void checkDuplicateKeys(Object... keys) {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/util/context/Context.java]: I just realized.... Since the method is defined in the interface, it will be public. I guess we don't want to leak it to public, don't we?

File: reactor-core/src/main/java/reactor/util/context/Context.java [hunk 4]
```diff
@@ -61,6 +62,28 @@ static Context of(Object key, Object value) {
...
+		int size = keys.length;
+		if (size < 2) return;
+
+		for (int i = 0; i < keys.length - 1; i++) {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/util/context/Context.java]:
```suggestion
		for (int i = 0; i < size - 1; i++) {
```

File: reactor-core/src/main/java/reactor/util/context/Context.java [hunk 5]
```diff
@@ -61,6 +62,28 @@ static Context of(Object key, Object value) {
...
+			Object key = keys[i];
+			for (int j = i + 1; j < keys.length; j++) {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/util/context/Context.java]:
```suggestion
			for (int j = i + 1; j < size; j++) {
```

File: reactor-core/src/main/java/reactor/util/context/Context.java [hunk 6]
```diff
@@ -61,6 +62,28 @@ static Context of(Object key, Object value) {
...
+	/**
+	 * Checks for duplicate keys. This method is intended for a short space of keys in the
+	 * 4-10 range. Shorter number of keys can easily be checked with direct equals comparison(s),
+	 * saving on allocating a vararg array (although this method would still behave correctly).
+	 *
+	 * @param keys the keys to check for duplicates, by looping over the combinations
+	 */
+	static void checkDuplicateKeys(Object... keys) {
+		int size = keys.length;
+		if (size < 2) return;
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/util/context/Context.java]: `for (int i = 0; i < size - 1; i++) {` will ignore it anyways

File: reactor-core/src/main/java/reactor/util/context/Context.java [hunk 7]
```diff
@@ -72,6 +95,10 @@ static Context of(Object key, Object value) {
 	 */
 	static Context of(Object key1, Object value1,
 			Object key2, Object value2) {
+		//prefer direct check for the simple 2 keys case over checkDuplicateKeys (saves up 1 array allocation)
+		if (key1.equals(key2)) {
+			throw new IllegalArgumentException("Found duplicate key in Context.of() with 2 key-value pairs: " + key1);
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/util/context/Context.java]: Since the stracktrace will have `Context.of` already, maybe we should simplify the message to something like `"Duplicated key: " + key1`?

File: reactor-core/src/main/java/reactor/util/context/Context.java [hunk 8]
```diff
@@ -132,9 +167,42 @@ static Context of(Object key1, Object value1,
...
+	 *
+	 * @implNote this method compacts smaller maps into a relevant fields-based implementation
+	 * when number of key-value pairs is under 6.
+	 */
+	static Context of(Map<?, ?> keyValuePairs) {
+		int size = keyValuePairs.size();
+		if (size == 0) return Context.empty();
+		if (size <= 5) {
+			Map.Entry[] entries = keyValuePairs.entrySet().toArray(new Map.Entry[size]);
+			if (size == 1) return new Context1(entries[0].getKey(), entries[0].getValue());
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/util/context/Context.java]: WDYT about using `switch` here?

File: reactor-core/src/main/java/reactor/util/context/Context.java [hunk 9]
```diff
@@ -132,9 +167,42 @@ static Context of(Object key1, Object value1,
...
 
+	/**
+	 * Create a {@link Context} out of a {@link Map}. Prefer this method if you're somehow
+	 * incapable of checking keys are all distinct in other {@link #of(Object, Object, Object, Object, Object, Object, Object, Object)}
+	 * implementations.
+	 *
+	 * @implNote this method compacts smaller maps into a relevant fields-based implementation
+	 * when number of key-value pairs is under 6.
+	 */
+	static Context of(Map<?, ?> keyValuePairs) {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/util/context/Context.java]: the variable name is a bit misleading because there are no "pairs", map is a map :) Maybe just "values"?

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/util/context/Context.java]: map is a container of key-value pairs, isn't it? but yeah, I should simply say `when size of the map is less than 6`.

File: reactor-core/src/main/java/reactor/util/context/Context.java (hunk 3 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/util/context/Context.java]: ah snap you're right we don't want that to leak... since the approach here is to throw, we don't have to decide between several candidate implementations so we could move this logic in the constructors 🤔

Comment (bsideup) [reply reactor-core/src/main/java/reactor/util/context/Context.java]: you could also create an internal class in `Context.java` just for the validation

File: reactor-core/src/main/java/reactor/util/context/Context.java (hunk 9 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/util/context/Context.java]: (my bad thought this referred to the javadoc comment... I'll also change the parameter name)

File: reactor-core/src/main/java/reactor/util/context/Context.java (hunk 2 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/util/context/Context.java]: see #1797 and PR #1800

File: reactor-core/src/main/java/reactor/util/context/Context.java (hunk 3 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/util/context/Context.java]: I moved the static method to `Context4`, which is accessible by `Context5` (the only other usage of the method)

File: reactor-core/src/main/java/reactor/util/context/Context.java (hunk 7 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/util/context/Context.java]: I changed the message to the format `Key #keyN (valueN) is duplicated` across the board

File: reactor-core/src/main/java/reactor/util/context/Context.java (hunk 8 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/util/context/Context.java]: done

**Comment by simonbasle** [comment]
@bsideup I'll rebase this on top of #1800 once merged and forwarded into `master`

**Comment by simonbasle** [comment]
I have rebased on top of now merged #1800, so I have changed the last commit a bit: `checkDuplicateKeys` is now `checkKeys` and integrates the null check. We ensure the last key in the array is checked for null after the loops, since the outer loop never visits the last key.

File: reactor-core/src/main/java/reactor/util/context/ContextN.java [hunk 10]
```diff
@@ -29,42 +30,45 @@
...
 		super(map.size() + 1, 1f);
-		innerPutAll(map);
-		innerPut(key, value);
+		Objects.requireNonNull(map, "map")
+		       .forEach(this);
+		accept(key, value); //innerPut
 	}
 
 	ContextN(Map<Object, Object> sourceMap, Map<?, ?> other) {
 		super(sourceMap.size() + other.size(), 1f);
```
Comment (robotmrv) [inline reactor-core/src/main/java/reactor/util/context/ContextN.java]: access to probably null value 
both bellow validations are useless - they will never work but just allocate message Strings

Comment (bsideup) [reply reactor-core/src/main/java/reactor/util/context/ContextN.java]: FYI constant strings are stored in the constant pool and are not allocated every time

File: reactor-core/src/main/java/reactor/util/context/Context.java [hunk 11]
```diff
@@ -140,6 +141,45 @@ static Context of(Object key1, Object value1,
...
+	/**
+	 * Create a {@link Context} out of a {@link Map}. Prefer this method if you're somehow
+	 * incapable of checking keys are all distinct in other {@link #of(Object, Object, Object, Object, Object, Object, Object, Object)}
+	 * implementations.
+	 *
+	 * @implNote this method compacts smaller maps into a relevant fields-based implementation
+	 * when map size is less than 6.
+	 */
+	static Context of(Map<?, ?> map) {
+		int size = map.size();
```
Comment (robotmrv) [inline reactor-core/src/main/java/reactor/util/context/Context.java]: validation from the ContextN() constructor will never work.  
but it is still obvious NPE on the `map`. maybe it is ok)

File: reactor-core/src/main/java/reactor/util/context/ContextN.java (hunk 10 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/util/context/ContextN.java]: I'll follow up with a polish moving this part one step above
