### PR TITLE
Fix #2107 by throwing (and checking) a specialized error

### LINKED ISSUE #2107: Mutualized `subscribe` error-catching doesn't play well with StepVerifier
## Expected Behavior
The catch-all code in `Flux#subscribe(Subscriber)`, `Operators.reportThrowInSubscribe` can lead to a double `onSubscribe`. This was deeemed ok because well-formed subscribers are supposed to react to that by ignoring the second `Subscription` (after cancelling it), but `StepVerifier` is a bit different: it must somehow report the underlying failure to the test framework. Furthermore, it cannot simply ignore double subscriptions as they could come from a really problematic `Publisher`.

## Actual Behavior
Currently, this means that instead of reporting the original failure, `StepVerifier` can hide it and report a double subscription instead...

In some instances, it was found to report at best a `CompositeException` with original failure + double subscription...

## Steps to Reproduce
```java
	private static final class ErrorInSubscribeFlux<T> extends Flux<T> {

		final Supplier<T> tSupplier;

		private ErrorInSubscribeFlux(Supplier<T> supplier) {
			tSupplier = supplier;
		}

		@Override
		public void subscribe(CoreSubscriber<? super T> actual) {
			//for now we MUST call actual.onSubscribe in case of exception
			final T t = tSupplier.get();
			if (t == null) throw new NullPointerException("supplied null value");

			//past this point we MUST NOT  call actual.onSubscribe in case of exception
			actual.onSubscribe(new Subscription() {
				@Override
				public void request(long l) {
					actual.onNext(t);
					throw new IllegalStateException("ErrorInSubscribeFlux");
				}

				@Override
				public void cancel() {
					//NO-OP
				}
			});
		}
	}

	@Test
	public void mutualizedSubscribeErrorHandlingWPreOnSubscribe() {
		new ErrorInSubscribeFlux<>(() -> null)
				.as(StepVerifier::create)
				.verifyErrorMessage("supplied null value");
	}

	@Test
	public void mutualizedSubscribeErrorHandlingPostOnSubscribe() {
		new ErrorInSubscribeFlux<>(() -> 42)
				.as(StepVerifier::create)
				.expectNext(42)
				.verifyErrorSatisfies(e -> assertThat(e)
						.isInstanceOf(IllegalStateException.class)
						.hasMessage("ErrorInSubscribeFlux"));
	}
```

While the first test passes, the second test fails because `ErrorInSubscribeFlux` is hidden by the following exception:

```
java.lang.AssertionError: expectation failed (an unexpected Subscription has been received: reactor.core.publisher.Operators$EmptySubscription@16e7dcfd; actual: reactor.core.publisher.scenarios.FluxTests$ErrorInSubscribeFlux$1@3d121db3)

	at reactor.test.MessageFormatter.assertionError(MessageFormatter.java:115)
	at reactor.test.MessageFormatter.failPrefix(MessageFormatter.java:104)
	at reactor.test.MessageFormatter.fail(MessageFormatter.java:73)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.setFailure(DefaultStepVerifierBuilder.java:1300)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.setFailure(DefaultStepVerifierBuilder.java:1286)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onSubscribe(DefaultStepVerifierBuilder.java:1134)
	at reactor.core.publisher.Operators.reportThrowInSubscribe(Operators.java:190)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8268)
```

## Possible Solution
 * backtrack and let each operator individually deal with exceptions, thus correctly deciding when one cannot invoke `actual.onSubscribe(Operators.emptySubscription())`
 * have `reportThrowInSubscribe` emit a specific instance of `EmptySubscription` that can be detected (via a **new public API**) by `StepVerifier` as the only case where a second subscription can be ignored.

## Your Environment

* Reactor version(s) used: 3.3.5.BUILD-SNAPSHOT (see #2072)

### PR DESCRIPTION
**Pull request by bsideup**

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/Operators.java [hunk 1]
```diff
@@ -181,13 +193,13 @@ public static Subscription emptySubscription() {
 	 * @param e the actual error
 	 */
 	public static void error(Subscriber<?> s, Throwable e) {
-		s.onSubscribe(EmptySubscription.INSTANCE);
+		s.onSubscribe(OnErrorSubscription.INSTANCE);
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/Operators.java:196]: @simonbasle after thinking more about it, I ended up with `OnErrorSubscription` in both `#error` and `#reportThrowInSubscribe`.
The meaning of it is the same - we pass a dummy subscription to satisfy spec's 1.9 rule.

But now `#error` and `#reportThrowInSubscribe` look almost identical (except the spec violating catch).
WDYT about adding `try {} catch {}` to `error` and removing `reportThrowInSubscribe`?

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/Operators.java:196]: I'm not comfortable with this modification, as `#error` can be used as part of the normal path. the only situation where the double subscribe _can_ be ignored by StepVerifier is `reportThrowInSubscribe`

Comment (bsideup) [reply reactor-core/src/main/java/reactor/core/publisher/Operators.java]: pushed a new attempt :D
