### PR TITLE
fix #1451 Dematerialize needs extra request(1) for terminal signals...

### LINKED ISSUE #1451: Materializing/dematerializing without complete loses last onNext
### Expected behavior

Chaining Flux.materialize().dematerialize() should not alter output.

This seems to be related to issue #585 but if the behavior is indeed expected, it should at least be documented (JavaDoc for Flux.dematerialize()).

### Actual behavior

If the publisher never sends a complete signal, the last onNext signal is lost (stuck in dematerialize).

### Steps to reproduce

Example:

```java
Flux.just("one", "two", "three")
        .concatWith(Flux.never())
        .materialize()
        .dematerialize()
        .subscribe(x -> log.info("Got next: {}", x)) ;
```

The output shows only "one" and "two" arriving. All three arrive if either `concatWith(Flux.never())` or `materialize.()dematerialize.()` is omitted.

### Reactor Core version

3.2.3

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-b26)
OpenJDK 64-Bit Server VM (build 25.192-b26, mixed mode)

### PR DESCRIPTION
**Pull request by simonbasle**
This commit reworks dematerialize so that it maps 1 request to 1 Signal
from upstream, immediately propagating that decoded signal.

As a consequence, when requested one by one, dematerialize now requires
one more request for the terminal signal to be pulled and propagated.

This also means that the requested signals won't be delayed until the
upstream emits the next signal (which was both problematic in terms of
timing consistency and in terms of getting the last `onNext` in the case
of a never ending source).

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/FluxDematerialize.java [hunk 1]
```diff
@@ -36,46 +32,32 @@
...
+		source.subscribe(new DematerializeSubscriber<>(actual, false));
 	}
 
-	static final class DematerializeSubscriber<T> extends AbstractQueue<T>
-			implements InnerOperator<Signal<T>, T>,
-			           BooleanSupplier {
+	static final class DematerializeSubscriber<T> implements InnerOperator<Signal<T>, T> {
 
 		final CoreSubscriber<? super T> actual;
+		final boolean isMono;
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/FluxDematerialize.java]: Is it possible to change the name of this flag from "is of type" to "should be doing this"? I assume there isn't anything Mono specific here, just the behaviour flag.

Just thinking out loud of the future cases of having this behaviour for some another, non-Mono type

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxDematerialize.java]: this is quite `Mono` specific, but why not.

File: reactor-core/src/main/java/reactor/core/publisher/FluxDematerialize.java [hunk 2]
```diff
@@ -86,32 +68,29 @@ public void onSubscribe(Subscription s) {
...
 				Operators.onNextDropped(t, actual.currentContext());
 				return;
 			}
+
 			if (t.isOnComplete()) {
 				s.cancel();
 				onComplete();
 			}
-			else if (t.isOnError()) {
+			else if (t.isOnError() && t.getThrowable() != null) {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/FluxDematerialize.java]: 1) I'm curious how we can get `onError` without the error?
2) Since we add these guards, I wonder whether we should handle the `else` case now (currently it is unhandled and may block the processing)

File: reactor-core/src/main/java/reactor/core/publisher/FluxDematerialize.java [hunk 3]
```diff
@@ -137,79 +111,27 @@ public void onComplete() {
...
-				}
+				s.request(n);
 			}
 		}
 
 		@Override
 		public void cancel() {
-			cancelled = true;
-			s.cancel();
+			if (!cancelled) {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/FluxDematerialize.java]: it is serialized, right? No need for CAS?

File: reactor-core/src/test/java/reactor/core/publisher/FluxDematerializeTest.java [hunk 4]
```diff
@@ -284,31 +240,68 @@ public void dematerialize() {
...
+				    .materialize()
+				    .<Tuple2<Long, String>>dematerialize()
+				    .timestamp()
+		)
+		            .thenAwait(Duration.ofSeconds(5))
+		            .thenConsumeWhile(tupleDematerialize -> {
+		            	long dematerializeTimestamp = tupleDematerialize.getT1();
+		            	long originalTimestamp = tupleDematerialize.getT2().getT1();
+
+			            System.out.println(tupleDematerialize.getT2().getT2() + ": " + originalTimestamp + ", " + dematerializeTimestamp);
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/FluxDematerializeTest.java]: a leftover from debugging? Or we do need this logging?

File: reactor-core/src/main/java/reactor/core/publisher/FluxDematerialize.java (hunk 2 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxDematerialize.java]: ah yeah, leftover from trying to make the IDE happy with the test and nullability. Seems IntelliJ cannot infer that `hasError()` implies non-null `getThrowable()`...

File: reactor-core/src/main/java/reactor/core/publisher/FluxDematerialize.java (hunk 3 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxDematerialize.java]: no need for CAS, but some operators might be to liberal with calling `cancel()` twice (since it MUST be idempotent), hence this guard.

File: reactor-core/src/test/java/reactor/core/publisher/FluxDematerializeTest.java (hunk 4 above)
Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/FluxDematerializeTest.java]: probably not that useful now that the test passes 😄
