### PR TITLE
Propagate ThreadLocals in tap

### LINKED ISSUE #3395: Micrometer.observation failure with automatic context propagation
Context is not properly propagated through publishers when using `Hooks.enableAutomaticContextPropagation();`. I've created a simple [spring boot 3 application](https://github.com/maciej-gromul/boot-3-problems-with-context-propagation) that should be working using micrometer observations to create tracing context. I can see spans being created but their context is not propagated which results in something like this:

image

while expected trace should be nested like this:

```
http get /trace
  |
  -- some-random-name
       |
       -- simple-text-wrapping-service
            |
            -- other-layer
```

I've confirmed that TapSubscriber properly registers in reactor context new tracing context from created span, but it get's lost somewhere and in the next tap operator that creates a new observation with new span later on it always attaches to the root span.

## Expected Behavior
Context get's propagated and spans are being properly connected to each other.

## Actual Behavior
Root span created by spring webflux is always being treated as parent root, even if we create new span following the migration guide for sleuth, it get's created but parent stays as current span/context.

## Steps to Reproduce
Here's the project with example to reproduce the problem: https://github.com/maciej-gromul/boot-3-problems-with-context-propagation. There's docker compose configuration file to run grafana stack allowing easy verification of generated tracing.

## Possible Solution
Don't know what precisely causes this.

### PR DESCRIPTION
**Pull request by chemicL**
Aside from `contextWrite()`, the tap operator also has write access to the `Context`.
New classes have been added to handle the automatic context propagation:

* `MonoTapRestoringThreadLocals`
* `FluxTapRestoringThreadLocals`

They replace the corresponding operators in tap when `Hooks.enableAutomaticContextPropagation()` is called, and when the `context-propagation` library is on the class path.

As a result of these changes, `FluxTapTest` was also moved to the `withMicrometerTest` source set, where the `context-propagation` library is present.

Fixes #3395.

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java [hunk 1]
```diff
@@ -166,7 +166,7 @@ static <T, R> BiConsumer<T, SynchronousSink<R>> contextRestoreForHandle(BiConsum
 	}
 
 	static <T> SignalListener<T> contextRestoreForTap(final SignalListener<T> original, Supplier<Context> contextSupplier) {
-		if (propagateContextToThreadLocals || !ContextPropagation.isContextPropagationAvailable()) {
+		if (!ContextPropagation.isContextPropagationAvailable()) {
```
Comment (OlegDokuka) [inline reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java:169]: Any reasons why this is changed?

File: reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java [hunk 2]
```diff
@@ -0,0 +1,353 @@
...
+		/**
+		 * Cancel the active subscription, pass the listener error to {@link SignalListener#handleListenerError(Throwable)}
+		 * and then terminate the downstream directly with same error (without invoking any other handler).
+		 *
+		 * @param listenerError the exception thrown from a handler method
+		 */
+		protected void handleListenerErrorAndTerminate(Throwable listenerError) {
+			s.cancel();
+			listener.handleListenerError(listenerError);
+			actual.onError(listenerError); //TODO wrap ? hooks ?
```
Comment (OlegDokuka) [inline reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java:156]: decorated with scope?

File: reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java [hunk 3]
```diff
@@ -0,0 +1,353 @@
...
+		 * Cancel the prepared subscription, pass the listener error to {@link SignalListener#handleListenerError(Throwable)}
+		 * and then terminate the downstream directly with same error (without invoking any other handler).
+		 *
+		 * @param listenerError the exception thrown from a handler method before the subscription was set
+		 * @param toCancel      the {@link Subscription} that was prepared but not sent downstream
+		 */
+		protected void handleListenerErrorPreSubscription(Throwable listenerError, Subscription toCancel) {
+			toCancel.cancel();
+			listener.handleListenerError(listenerError);
+			Operators.error(actual, listenerError);
```
Comment (OlegDokuka) [inline reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java:144]: scope?

File: reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java (hunk 1 above)
Comment (OlegDokuka) [reply reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java:169]: how about adding comment that this method is used in non-context restoring versions of tap operator

Comment (chemicL) [reply reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java:169]: yep, will do

File: reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java [hunk 4]
```diff
@@ -0,0 +1,353 @@
...
+		 * (without invoking any other handler).
+		 *
+		 * @param listenerError the exception thrown from a handler method
+		 * @param originalError the exception that was about to occur when handler was invoked
+		 */
+		protected void handleListenerErrorMultipleAndTerminate(Throwable listenerError, Throwable originalError) {
+			s.cancel();
+			listener.handleListenerError(listenerError);
+			RuntimeException multiple = Exceptions.multiple(listenerError, originalError);
+			actual.onError(multiple); //TODO wrap ? hooks ?
```
[the remark this answers is not in the document]
Comment (chemicL) [reply reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java:171]: Right, good eye. I fixed the three you noticed and also found 2 more in the subscribe method, so together with the Mono counterpart that makes 4 more places to add. Will follow up shortly.

File: reactor-core/src/main/java/reactor/core/publisher/MonoTapRestoringThreadLocals.java [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+		//if the SignalListener cannot be created, all we can do is error the subscriber.
+		//after it is created, in case doFirst fails we can additionally try to invoke doFinally.
+		//note that if the later handler also fails, then that exception is thrown.
+		SignalListener<T> signalListener;
+		try {
+			//TODO replace currentContext() with contextView() when available
+			signalListener = tapFactory.createListener(source, actual.currentContext().readOnly(), commonTapState);
+		}
+		catch (Throwable generatorError) {
+			try (ContextSnapshot.Scope ignored =
```
Comment (OlegDokuka) [inline reactor-core/src/main/java/reactor/core/publisher/MonoTapRestoringThreadLocals.java:53]: i guess this is redundant since we don't have new TL set

File: reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java [hunk 6]
```diff
@@ -0,0 +1,368 @@
...
+		//if the SignalListener cannot be created, all we can do is error the subscriber.
+		//after it is created, in case doFirst fails we can additionally try to invoke doFinally.
+		//note that if the later handler also fails, then that exception is thrown.
+		SignalListener<T> signalListener;
+		try {
+			//TODO replace currentContext() with contextView() when available
+			signalListener = tapFactory.createListener(source, actual.currentContext().readOnly(), commonTapState);
+		}
+		catch (Throwable generatorError) {
+			try (ContextSnapshot.Scope ignored =
```
Comment (OlegDokuka) [inline reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java:56]: this is redundant here since there is no new TL restored yet

File: reactor-core/src/main/java/reactor/core/publisher/MonoTapRestoringThreadLocals.java [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+		}
+
+		// invoked AFTER doFirst
+		Context alteredContext;
+		try {
+			alteredContext = signalListener.addToContext(actual.currentContext());
+		}
+		catch (Throwable e) {
+			signalListener.handleListenerError(new IllegalStateException("Unable to augment tap Context at construction via addToContext", e));
+			try (ContextSnapshot.Scope ignored =
```
Comment (OlegDokuka) [inline reactor-core/src/main/java/reactor/core/publisher/MonoTapRestoringThreadLocals.java:76]: any reasons for doing that?

File: reactor-core/src/main/java/reactor/core/publisher/MonoTapRestoringThreadLocals.java [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
+					     ContextPropagation.setThreadLocals(actual.currentContext())) {
+				alteredContext = actual.currentContext();
+			}
```
Comment (OlegDokuka) [inline reactor-core/src/main/java/reactor/core/publisher/MonoTapRestoringThreadLocals.java:79]: interesting. the return statement is missing and likely a bug in both existing implementations.

File: reactor-core/src/main/java/reactor/core/publisher/MonoTapRestoringThreadLocals.java (hunk 7 above)
Comment (OlegDokuka) [reply reactor-core/src/main/java/reactor/core/publisher/MonoTapRestoringThreadLocals.java:76]: I mean we dont have new TL set yet

File: reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java [hunk 9]
```diff
@@ -0,0 +1,368 @@
...
+		}
+
+		// invoked AFTER doFirst
+		Context alteredContext;
+		try {
+			alteredContext = signalListener.addToContext(actual.currentContext());
+		}
+		catch (Throwable e) {
+			signalListener.handleListenerError(new IllegalStateException("Unable to augment tap Context at construction via addToContext", e));
+			alteredContext = actual.currentContext();
```
Comment (OlegDokuka) [inline reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java:82]: likely there should be 
`Operators.error(actual, listenerError);` and `return;` seems to be a bug in both existing implementations

File: reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java (hunk 6 above)
Comment (chemicL) [reply reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java:56]: my bad

File: reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java [hunk 10]
```diff
@@ -0,0 +1,368 @@
...
+			}
+			return;
+		}
+
+		try {
+			signalListener.doFirst();
+		}
+		catch (Throwable listenerError) {
+			signalListener.handleListenerError(listenerError);
+			try (ContextSnapshot.Scope ignored =
```
[the remark this answers is not in the document]
Comment (chemicL) [reply reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java:68]: right, my mistake

File: reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java (hunk 9 above)
Comment (chemicL) [reply reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java:82]: I don't know, I suppose. But let's not make the fix part of this PR, but a follow up.

File: reactor-core/src/main/java/reactor/core/publisher/MonoTapRestoringThreadLocals.java (hunk 7 above)
Comment (chemicL) [reply reactor-core/src/main/java/reactor/core/publisher/MonoTapRestoringThreadLocals.java:76]: That must have been a mistake, `currentContext()` doesn't need TLs to be present at all, removing.

File: reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java (hunk 9 above)
Comment (chemicL) [reply reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java:76]: I created #3414 to address this concern.

File: reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerTest.java [hunk 11]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2022 VMware Inc. or its affiliates, All Rights Reserved.
+ * Copyright (c) 2022-2023 VMware Inc. or its affiliates, All Rights Reserved.
```
Comment (OlegDokuka) [inline reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerTest.java:2]: redundant change?

**Review by OlegDokuka — APPROVED** [review]
