### PR TITLE
fix #1992 Reimplement boundedElasticScheduler with reentrancy but less efficient work stealing

### LINKED ISSUE #1973: BoundedElasticScheduler does not invoke any tasks after interruption.
I've stumbled upon a problem with BoundedElasticScheduler when there's high traffic creating many queued task on it. Invoking dispose() on scheduled tasks seems to break scheduler, to the point where it is not invoking any new tasks.

## Expected Behavior
Scheduler should correctly invoke tasks, after disposing all of its other tasks.

## Actual Behavior
Scheduler doesn't do anything after disposing all of its tasks, and scheduling a new one.

## Steps to Reproduce
In the following example, behavior is as follows:

* ~520 tasks are scheduled
* ~300 scheduled tasks are processed correctly
* When dispose() is called all of scheduled tasks are cancelled
* On most scheduled tasks InterruptedException occurs, except ~15 last ones (505-520)
* Scheduled task after dispose() call is never invoked.

```java
Logger logger = LoggerFactory.getLogger("Test");

    @Test
    public void test() throws InterruptedException {
        Scheduler scheduler =
                Schedulers.newBoundedElastic(30, Schedulers.DEFAULT_BOUNDED_ELASTIC_QUEUESIZE, "test-scheduler");
        Disposable subscription = Flux.range(0, 100000000)
                .flatMap(i -> {
                    logger.info("Scheduling {}", i);
                    return Mono.fromSupplier(() -> invokeLongOperation(i))
                            .subscribeOn(scheduler)
                            .publishOn(Schedulers.parallel())
                            .doOnError(throwable -> logger.error("Error occurred in thread {} ", i, throwable))
                            .doOnCancel(() -> logger.info("Thread {} cancelled", i));
                })
                .subscribe(i -> logger.info("Thread {} finished", i),
                           throwable -> logger.error("Error ", throwable));
        Thread.sleep(10000);
        logger.info("Invoking dispose");
        subscription.dispose();
        Thread.sleep(1000);
        Mono.fromSupplier(() -> invokeLongOperation(999999999))
                .subscribeOn(scheduler)
                .publishOn(Schedulers.parallel())
                .subscribe((i) -> logger.info("Consumed value {} ", i),
                           throwable -> logger.error("Exception"));
        logger.info("Sleeping");
        Thread.sleep(100000);
    }

    private int invokeLongOperation(Integer i) {
        logger.info("Invoking long operation {}", i);
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            logger.error("Thread {} interrupted", i);
        }
        return i;
    }
```

##Environment

* Reactor version used: 3.3.0
* JVM version: 1.8.0

### LINKED ISSUE #1992: Multiple subscribeOn calls with a BoundedElasticScheduler can cause deadlock
The following code, containing two `subscribeOn` calls never completes:

```java
final Scheduler scheduler = Schedulers.newBoundedElastic(1, Integer.MAX_VALUE, "test");
        
final Mono<Integer> integerMono = Mono.fromSupplier(() -> 1)
                .subscribeOn(scheduler)
                .subscribeOn(scheduler);

        integerMono.block();
```

The issue is unique to `BoundedElasticScheduler`. Other bounded schedulers do not show this behaviour. If one `subscribeOn` is removed, then it does run to completion.

## Expected Behavior
As per https://projectreactor.io/docs/core/release/reference/#_the_subscribeon_method, 

> Only the earliest subscribeOn call in the chain is actually taken into account. 

Therefore the code above should be equivalent to having a single `subscribeOn`. 

## Actual Behavior
The code never terminates. A stack dump shows it is awaiting a `CountDownLatch`

```java
"Test worker" #13 prio=5 os_prio=31 cpu=310.15ms elapsed=672.58s tid=0x00007faa55190800 nid=0x5b03 waiting on condition  [0x000070000a3dc000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.4/Native Method)
        - parking to wait for  <0x00000007ff86c888> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.4/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.4/AbstractQueuedSynchronizer.java:885)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.4/AbstractQueuedSynchronizer.java:1039)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11.0.4/AbstractQueuedSynchronizer.java:1345)
        at java.util.concurrent.CountDownLatch.await(java.base@11.0.4/CountDownLatch.java:232)
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:81)
        at reactor.core.publisher.Mono.block(Mono.java:1663)
        at test.SingleThreadedExecutorSubscribeOnTest.getOneFromMono(SingleThreadedExecutorSubscribeOnTest.java:39)
        at test.SingleThreadedExecutorSubscribeOnTest.subscribeOn_twice_for_single_threaded_boundedElastic_should_complete(SingleThreadedExecutorSubscribeOnTest.java:
```

## Steps to Reproduce
The following unit test illustrates two bounded schedulers which _do_ work as expected (`fromExecutor`, `fromSingle`), and the one which doesn't (`newBoundedElastic`)

```java
class SingleThreadedExecutorSubscribeOnTest {
    @Test
    void subscribeOn_twice_for_single_executor_should_complete() {
        getOneFromMono(Schedulers.newSingle("test"));
    }

    @Test
    void subscribeOn_twice_for_single_threaded_boundedElastic_should_complete() {
        // This never completes
        getOneFromMono(Schedulers.newBoundedElastic(1, Integer.MAX_VALUE, "test"));
    }

    @Test
    void subscribeOn_twice_for_single_threaded_executor_should_complete() {
        final Scheduler executorScheduler = Schedulers.fromExecutor(
                new ThreadPoolExecutor(0, 1,
                        60L, TimeUnit.SECONDS,
                        new LinkedBlockingDeque<>()));

        getOneFromMono(executorScheduler);
    }

    private void getOneFromMono(final Scheduler scheduler) {
        final Mono<Integer> integerMono = Mono.fromSupplier(() -> 1)
                .subscribeOn(scheduler)
                .subscribeOn(scheduler);

        integerMono.block();
    }
}
```

## Possible Solution
Not researched in detail, however it appears that having _n_ `subscribeOn` calls in a chain subscribing with a scheduler with _n-1_ `threadCap` triggers the issue. 

## Your Environment
* Reactor version(s) used: io.projectreactor:reactor-core:3.3.1.RELEASE
* JVM version (`javar -version`):
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

* OS and version (eg `uname -a`): MacOS

### PR DESCRIPTION
**Pull request by simonbasle**
This should fix #1973 and fix #1992

The general idea is to abandon the facade `Worker` and instead always submit tasks to an executor-backed worker. In order of preference, when an operator requests a `Worker`:
 - if thread cap not reached, create and pick a new worker
 - else if idle workers, pick an idle worker
 - else pick a busy worker

This implies a behavior under contention that is closer to `parallel()`, with a pool that is expected to be quite larger than the typical parallel pool. Livelocks can still happen but they seem to be far too frequent with the current implementation anyway.

The drawback is that once we get to pick a busy worker, there's no telling when its tasks (typically blocking tasks for a `BoundedElasticScheduler`) will finish. So even though another executor might become idle in the meantime, the operator's tasks will be pinned to the (potentially still busy) executor initially picked.

To try to counter that effect a bit, we use a priority queue for the busy executors, favoring executors that are tied to less `Worker`s (and thus operators). We don't yet go as far as factoring in the task queue of each executor.

Finally, one noticeable change is that the second `int` parameter in the API, `maxPendingTask`, is now influencing **EACH** executor's queue, and is not a shared counter. It should be safe in the sense that the number set with previous version in mind is bound to be over-dimensionned for the new version, but it would be recommended for users to scale that number back.

### CODE REVIEW

**Comment by simonbasle** [comment]
note: for now `BoundedElasticScheduler` changed to the new implementation. might make more sense to review raw file rather than diff. Kept temporarily the old implementation as `BoundedFacadeElasticScheduler`.

**Comment by simonbasle** [comment]
@rstoyanchev @bsideup this should now be in final state, except for the pending removal of `BoundedFacadeElasticScheduler` (now dead code)

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 1]
```diff
@@ -1,315 +1,239 @@
 /*
- * Copyright (c) 2011-Present Pivotal Software Inc, All Rights Reserved.
+ * Copyright (c) 2011-2017 Pivotal Software Inc, All Rights Reserved.
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]:
```suggestion
 * Copyright (c) 2011-Present Pivotal Software Inc, All Rights Reserved.
```

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 2]
```diff
@@ -1,315 +1,239 @@
...
+	 * ({@code Executors.newScheduledThreadPoolExecutor} with core and max pool size of 1).
+	 */
+	BoundedScheduledExecutorService createBoundedExecutorService() {
+		return new BoundedScheduledExecutorService(this.maxTaskQueuedPerThread, this.factory);
 	}
 
 	@Override
 	public boolean isDisposed() {
-		return shutdown;
+		return BOUNDED_SERVICES.get(this) == SHUTDOWN;
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: Educational question: can't we just refer the (volatile) field here? Why do we need to get it via the updater?

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 3]
```diff
@@ -319,491 +243,554 @@ public String toString() {
...
 		}
-	}
 
-	static final class CachedServiceExpiry {
-
-		final CachedService cached;
-		final long          expireMillis;
+		@Override
+		public boolean isDisposed() {
+			return get() == -1;
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: nit: please extract the constant (to be used in `dispose()`)

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java (hunk 2 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: for reads, one can use the _volatile_ directly yeah. It is important to do all writes through the field updater as they have slightly relaxed guarantees. I ended up using the field updater everywhere for consistency, as AFAIK the difference is just cosmetic for reads

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java (hunk 3 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: done

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 4]
```diff
@@ -5,311 +5,236 @@
...
+		this.clock = Objects.requireNonNull(clock, "A Clock must be provided");
+		this.ttlMillis = ttlMillis;
+
+		this.boundedServices = new BoundedServices(this);
 		this.evictor = Executors.newScheduledThreadPool(1, EVICTOR_FACTORY);
-		this.evictor.scheduleAtFixedRate(() -> this.eviction(System::currentTimeMillis),
-				ttlSeconds,
-				ttlSeconds,
-				TimeUnit.SECONDS);
+		evictor.scheduleAtFixedRate(boundedServices::eviction,
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: nit: `this.boundedServices = `, `this.evictor = ` and `scheduleAtFixedRate` can be replaced with a single `start()` since they share the implementation.

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 5]
```diff
@@ -319,492 +244,554 @@ public String toString() {
...
-					REMAINING_THREADS.incrementAndGet(this);
-				}
-			}
-		}
+	@Override
+	public Worker createWorker() {
+		BoundedState picked = BOUNDED_SERVICES.get(this)
+		                                      .pick();
+		ExecutorServiceWorker worker = new ExecutorServiceWorker(picked.executor);
+		worker.tasks.add(picked); //this ensures the BoundedState will be released when worker is disposed
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: unrelated nit: `ExecutorServiceWorker#tasks` is very misleading (especially when populated from places like here), `ExecutorServiceWorker#disposables` or something would make it much easier to understand what it actually does (since it does not execute `tasks`, only disposes them)

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 6]
```diff
@@ -5,311 +5,236 @@
...
-
-	final ThreadFactory              factory;
-	final int                        ttlSeconds;
-	final int                        threadCap;
-	final int                        deferredTaskCap;
-	final Deque<CachedServiceExpiry> idleServicesWithExpiry;
-	final Queue<DeferredFacade>      deferredFacades;
-	final Queue<CachedService>       allServices;
-	final ScheduledExecutorService   evictor;
+	static final int             DISPOSED = -1;
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: This constant seems to be reused between `BoundedServices` and `BoundedState`.

I would suggest having two, in each class, especially given that `BoundedServices` uses it for checking a variable that is a counter (although I haven't checked `BoundedState`), so that the value is more meaningless in the given domain

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 7]
```diff
@@ -319,492 +244,554 @@ public String toString() {
...
-						//if no more work, the service is put back at end of the cached queue and new expiry is started
-						CachedServiceExpiry e = new CachedServiceExpiry(this,
-								System.currentTimeMillis() + parent.ttlSeconds * 1000L);
-						parent.idleServicesWithExpiry.offerLast(e);
-						if (parent.shutdown) {
-							if (parent.idleServicesWithExpiry.remove(e)) {
-								exec.shutdownNow();
-							}
-						}
+					//else optimistically retry
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: WDYT about using `continue` here? Otherwise, if we accidentally add some logic to the end of this loop, it will get executed when inner `if` resolves to false

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 8]
```diff
@@ -319,492 +244,554 @@ public String toString() {
...
+						newState.markPicked(); //no need to check return value as this one is brand new
+						busyQueue.add(newState);
+						return newState;
+					}
+					//else optimistically retry
+				}
+				else {
+					//pick the least busy one
+					BoundedState s;
+					s = busyQueue.poll();
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: nit: `BoundedState s;` and `s = ` can be merged

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 9]
```diff
@@ -319,492 +244,554 @@ public String toString() {
...
-			if (key == Attr.NAME) return parent.scanUnsafe(key);
-			if (key == Attr.PARENT) return parent;
-			if (key == Attr.TERMINATED || key == Attr.CANCELLED) return isDisposed();
-			if (key == Attr.CAPACITY) {
-				//assume 1 if unknown, otherwise use the one from underlying executor
-				Integer capacity = (Integer) Schedulers.scanExecutor(exec, key);
-				if (capacity == null || capacity == -1) return 1;
-			}
-			return Schedulers.scanExecutor(exec, key);
+		void setIdle(BoundedState boundedState) {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: We need to be careful with the order here, otherwise:
1. we add it to `idleQueue`
2. in another thread, `pick()` polls it and adds to the busy queue and returns
3. next statement removes it from the busy queue

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 10]
```diff
@@ -319,492 +244,554 @@ public String toString() {
...
+				if (MARK_COUNT.compareAndSet(this, i, i + 1)) {
+					return true;
+				}
+			}
 		}
 
+		/**
+		 * Check if this {@link BoundedState} should be evicted by comparing its idleSince
+		 * timestamp to the evictionTimestamp and comparing the difference with the
+		 * give ttlMillis. When eligible for eviction, the executor is shut down and the
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]:
```suggestion
		 * given ttlMillis. When eligible for eviction, the executor is shut down and the
```

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 11]
```diff
@@ -319,492 +244,554 @@ public String toString() {
...
+		 *
+		 * @param evictionTimestamp the timestamp at which the eviction process is running
+		 * @param ttlMillis the maximum idle duration
+		 * @return true if this {@link BoundedState} has shut down itself as part of eviction, false otherwise
+		 */
+		boolean tryEvict(long evictionTimestamp, long ttlMillis) {
+			long idleSince = this.idleSinceTimestamp;
+			if (idleSince < 0) return false;
+			long elapsed = evictionTimestamp - idleSince;
+			if (elapsed > 0 && elapsed >= ttlMillis) {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: nit: since `ttlMillis` is always positive `elapsed > 0` here is redundant

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 12]
```diff
@@ -319,492 +244,554 @@ public String toString() {
...
+		void release() {
+			int picked = MARK_COUNT.decrementAndGet(this);
+			if (picked == 0) {
+				this.idleSinceTimestamp = parent.clock.millis();
+				parent.setIdle(this);
+			}
+			else if (picked > 0) {
+				this.idleSinceTimestamp = -1L;
+			}
+			// -1 means being evicted, do nothing
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: nit: could use an early return instead of a comment ;)

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java (hunk 5 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: used to bear a reference to the `Disposable` handle that allows cancelling all the tasks, but can contain more than just task-related handlers. will rename 👍

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java (hunk 6 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: they both are atomic counters: `BoundedServices` counts the number of states, aka executors it spawned. `BoundedState` counts the number of `Worker`s that picked that state/executor.

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: I'll duplicate the constant and rename the second one `EVICTED`

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java (hunk 7 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: avoiding that is the goal of the comment, but I'll augment the comment with `"(implicit continue here)"`. otherwise triggers inspection "continue is unnecessary as the last statement in a loop".

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java (hunk 9 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: indeed. reversing the operations should be safer: remove from `busyQueue` (it is now nowhere to be seen by a concurrent process) -> add to `idleQueue` 👍

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: (I probably should add a test for that)

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java (hunk 4 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: they don't really share the implementation since the `BOUNDED_SERVICE` would need to be initialized to `SHUTDOWN` first, and in constructor the looping is superfluous.

**Comment by simonbasle** [comment]
ok I'm now preparing this for merging, by removing the old code and squashing the commits that needs squashing (if not all), cc @bsideup
