### PR TITLE
fix #1486 Prevent usingWhen terminal & cancel callbacks to both apply

### LINKED ISSUE #1486: Ensure atomic cleanup in Flux/Mono.usingWhen(…)
### Expected behavior
Cleanup functions should be called only once.

### Actual behavior
Cleanup close can be called multiple times if a subscription terminates and then gets cancelled.

### Steps to reproduce

```java
Publisher<Void> cleanup = …,
Flux flux = Flux.usingWhen(…, cleanup, cleanup, cleanup);

flux.subscribe(new CoreSubscriber<Object>() {
	Subscription subscription;

	@Override
	public void onSubscribe(Subscription s) {
		s.request(1);
		subscription = s;
	}

	@Override
	public void onNext(Object o) {}

	@Override
	public void onError(Throwable t) {}

	@Override
	public void onComplete() {
		subscription.cancel();
	}
});
```

### Reactor Core version

Reactor 3.2.5

### PR DESCRIPTION
**Pull request by simonbasle**
This commit prevents asyncComplete/asyncError terminal callbacks to
apply in addition to asyncCancel, in case one signal is still received
after the other (eg. a cancellation is performed asynchronously,
resulting in the signal arriving AFTER the onError/onComplete signals).

### CODE REVIEW

**Comment by simonbasle** [comment]
cc @mp911de can you look at the added tests see if they correctly cover your case?

File: reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java [hunk 1]
```diff
@@ -852,6 +855,180 @@ public void contextPropagationOnCancelWithNoHandler(Flux<String> source) {
 		assertThat(errorRef).hasValue(null);
 	}
 
+	// == tests checking callbacks don't pile up ==
+
+	@Test
+	public void noCancelCallbackAfterComplete() {
+		LongAdder cleanupCount = new LongAdder();
+		Flux<String> flux = Flux.usingWhen(Mono.defer(() -> Mono.just("foo")), Mono::just,
+				s -> Mono.fromRunnable(() -> cleanupCount.add(10)), //10 for completion
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java]: WDYT about using strings, to make the test more readable?

File: reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java [hunk 2]
```diff
@@ -852,6 +855,180 @@ public void contextPropagationOnCancelWithNoHandler(Flux<String> source) {
...
+			}
+
+			@Override
+			public void onError(Throwable t) {}
+
+			@Override
+			public void onComplete() {}
+		});
+
+		Thread.sleep(300);
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java]: `await().untilAsserted`?

Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java]: nope, tried with awaitility but there is an intermediate state where the cancellation increment was performed, but not the complete increment (yet). awaitility would happily say the test was green.
Similarly, I couldn't make use of `atLeast` because if the assertion is true too early, awaitility complains.
So most straightforward way of checking the state is waiting for a bunch of ms and asserting.

File: reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java (hunk 1 above)
Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java]: The numbers let us atomically detect application of several "callbacks". Using a `String` would make that property harder to get.

File: reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java (hunk 2 above)
Comment (bsideup) [reply reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java]: > where the cancellation increment was performed, but not the complete increment (yet)
We could assert this condition too so that it passes only when both are matched

File: reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java (hunk 1 above)
Comment (bsideup) [reply reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java]: `List<String>`?

`LongAdder` will successfully pass if we expect 100 (error) but actually called completion 10 times :D

Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java]: meh. the `List` is what I'm talking about: either skew operator /with a synchronized list or get potentially out of order / incomplete results.

the operator calling the callback 10 times when we only trigger completion 1 time would be quite a different problem...

Comment (bsideup) [reply reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java]: Okay... :D

File: reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java (hunk 2 above)
Comment (bsideup) [reply reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java]: My intention was to avoid static sleeps because they add a constant time to the test execution time, but okay to not use it if it makes it harder to detect the error

Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java]: yeah that is indeed something I tried to avoid by trying with awaitility first, without success ;)

**Comment by bsideup** [comment]
@simonbasle don't we need to do the same in `MonoUsingWhen`?

File: reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java [hunk 3]
```diff
@@ -852,6 +855,180 @@ public void contextPropagationOnCancelWithNoHandler(Flux<String> source) {
...
+			}
+
+			@Override
+			public void cancel() {
+				cancelled.set(true);
+			}
+		});
+
+		Flux<String> flux = Flux.usingWhen(Mono.just("foo"), v -> badPublisher,
+				s -> Mono.fromRunnable(() -> cleanupCount.add(10)).log(), //10 for completion
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java]:
```suggestion
				s -> Mono.fromRunnable(() -> cleanupCount.add(10)), //10 for completion
```

**Comment by simonbasle** [comment]
> @simonbasle don't we need to do the same in `MonoUsingWhen`?

nope, the `MonoUsingWhen` operator reuses the same `Subscriber`.
