### PR TITLE
fix #2459 Add a composite of all source as cause to firstWithValue error

### LINKED ISSUE #2459: `firstWithValue` exposure of combination of error and empty sources only
## Motivation
In the original issue #2173 part of the discussion was around how to expose the fact that all the sources either completed empty or with an error. The original plan was that if the operator was unable to produce an actual value, it should fail with `NoSuchElementException e` (which has been implemented) then allow to distinguish between error and empty sources via a `Exceptions.unwrapMultiple(e.getCause())`.

Unfortunately, it was instead implemented as a _suppressed_ exception rather than a cause, and this slipped past the review (#2363) 😢

This is clunkier from a usability perspective from the original plan:

```java
Flux.firstWithValue(Flux.error(new IllegalStateException("boom")), Flux.empty())
    .onErrorResume(NoSuchElementException.class, nse -> {
	    // boilerplate from there...
	    Throwable[] suppressed = nse.getSuppressed();
	    if (suppressed.length != 1) return Mono.error(nse);
        //...to there
        return Exceptions.unwrapMultiple(suppressed[0])
                         .stream()
                         .filter(NoSuchElementException.class::isInstance)
                         .findFirst()
                         .map(t -> Mono.just("has empty sources"))
                         .orElse(Mono.just("has only errors"));
    })
```

compared to:

```java
Flux.firstWithValue(Flux.error(new IllegalStateException("boom")), Flux.empty())
    .onErrorResume(NoSuchElementException.class,
		    nse -> Exceptions.unwrapMultiple(nse.getCause())
		                     .stream()
		                     .filter(NoSuchElementException.class::isInstance)
		                     .findFirst()
		                     .map(t -> Mono.just("has empty sources"))
		                     .orElse(Mono.just("has only errors"))
    )
```

## Desired solution
Since this behavior is technically not documented, can we get away with amending the behavior before officially documenting it?

## Considered alternatives
 1. Expose the composite through both `getCause()` and `getSuppressed()[0]` (but that implies some duplication when printing the stacktrace).
 2. Keep it as is for the foreseeable future (throughout 3.4.x)

### PR DESCRIPTION
**Pull request by aneveu**

### CODE REVIEW

File: reactor-core/src/test/java/reactor/core/publisher/FluxFirstWithValueTest.java [hunk 1]
```diff
@@ -67,7 +67,7 @@ void onlyErrorOrCompleteEmptyEmitsError() {
 				.expectErrorSatisfies(e -> {
 					assertThat(e).isInstanceOf(NoSuchElementException.class);
 					assertThat(e.getMessage()).isEqualTo("All sources completed with error or without values");
```
Comment (ericbottard) [inline reactor-core/src/test/java/reactor/core/publisher/FluxFirstWithValueTest.java:69]: Not related to this issue **per se** but can use the opportunity to change `assertThat(e.getMessage())` to `assertThat().hasMessage()` and variants.
Otherwise LGTM

**Review by ericbottard — APPROVED** [review]

**Review by simonbasle — CHANGES_REQUESTED** [review]
the mono version doesn't instantiate the `NoSuchElementException`, but it still has tests that use the `getSuppressed()[0]` pattern, so these should be changed as well

**Comment by ericbottard** [comment]
> the mono version doesn't instantiate the `NoSuchElementException`, but it still has tests that use the `getSuppressed()[0]` pattern, so these should be changed as well

Good catch. I'm on it

**Review by simonbasle — APPROVED** [review]
