### PR TITLE
fix #1529 StepVerifier CollectEvent blocks

### LINKED ISSUE #1529: StepVerifier.expectRecordedMatches(...) causes verify to block forever if you consume the capacity of the underlying flux
### Expected behavior

The following `StepVerifier` should work independently of how many elements one consumes in the `.thenConsumeWhile(...)` step (as long as there's an element in the provided flux that causes the condition passed to `.thenConsumeWhile(...)` to return false).

    int CAPACITY = ...;
    int end = ...;
    List<Integer> expected = IntStream.range(0, end).boxed().collect(Collectors.toList());

    ReplayProcessor<Integer> flux = ReplayProcessor.create(CAPACITY);

    for (int i = 0; i < CAPACITY; i++) flux.onNext(i);

    StepVerifier.create(flux)
            .recordWith(ArrayList::new)
            .thenConsumeWhile(i -> i < (end - 1))
            .expectRecordedMatches(expected::equals)
            .thenCancel()
            .verify();

### Actual behavior

Everything works fine if the `thenConsumeWhile` condition causes you to consume fewer elements than are available in the underlying flux, however if you consume _exactly_ the number of elements that are available then the `expectRecordedMatches` step executes but the `verify` step blocks forever.

### Steps to reproduce

Define `CAPACITY` above as a constant, e.g. 100, and create a function that takes `end` as an argument and contains the above `StepVerifier` sequence, then create two unit tests - one that calls the function like so:

    myStepVerifierFunction(CAPACITY - 1); // Record CAPACITY - 1 elements.

And another one that calls it with:

    myStepVerifierFunction(CAPACITY); // Record exactly CAPACITY elements.

I've created a GitHub repo that does this - see [`RecordTest`](https://github.com/george-hawkins/publish-cancel-test/blob/master/src/test/java/com/example/RecordTest.java). 

In my code, I've added a `System.err.println` call into the `expectRecordedMatches` step, so you can see there's no problem with this aspect of things - in both tests the `expectRecordedMatches` step executes and returns true. But in the test where we record exactly `CAPACITY` elements the `verify` blocks forever, and in the one where we record less than `CAPACITY` elements there's no issue.

I've also added an additional test where I consume `CAPACITY` elements from the flux _but_ miss out the `expectRecordedMatches` step. In this case, the `verify` does _not_ block, so it seems it's a side effect of this `expectRecordedMatches` step that causes the issue.

### Reactor Core version

3.2.5.RELEASE

### JVM version (e.g. `java -version`)

```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

### PR DESCRIPTION
**Pull request by pmackowski**
Fix issue [#1529](https://github.com/reactor/reactor-core/issues/1529)

Fix has also been tested against test [RecordTest](https://github.com/george-hawkins/publish-cancel-test/blob/master/src/test/java/com/example/RecordTest.java) provided by the issue author.

Everything worked fine if publisher ended with `onComplete` signal.
Without `onComplete` ,  `completeLatch` was never decremented and as a result 
verify step blocked forever.

### CODE REVIEW

File: reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java [hunk 1]
```diff
@@ -1307,7 +1307,7 @@ boolean onCollect(Signal<T> actualSignal) {
 				this.completeLatch.countDown();
 				return true;
 			}
-			return true;
+			return false;
```
Comment (simonbasle) [inline reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java]: is that part of the fix? can you expand on this change? it seems odd, as now the method always returns `true` (and thus the line 1343 would seem unreachable?)

Comment (pmackowski) [reply reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java]: Just checked that the change in line 1310 is the only one needed.
Indeed, now `onCollect` always returns true and this [part of code](https://github.com/reactor/reactor-core/blob/master/reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java#L1361-L1382) is never reached. 
The problem only occures when `expectRecordedMatches` consumes all signals from upstream. 
That is why `onComplete` makes a difference.

I also added `testExpectRecordedMatchesTwice` as I do not understand why [this is needed](https://github.com/reactor/reactor-core/blob/master/reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java#L1372-L1376)
