### PR TITLE
fix #1945 Avoid unnecessary wrapping of exceptions in scalar flatMap

### LINKED ISSUE #1945: Flux onError's exhibit inconsistent behavior
This issue was working correctly in `3.2.11` and began to fail in `3.2.12`

While upgrading our services, we ran into an issue where our onErrorResume which had previously been working, no longer did.

In examining the behavior, it seems that when a flux has only a single element, the onErrorResume is wrapped in a `ReactiveException` with the `.getCause()` being the original exception. When the publisher is a Mono or when a Flux has multiple elements, this behavior goes away.

A junit test to demonstrate the inconsistent behavior (using NoSuchMethodException for no reason in particular except demonstration):

```java
  @Test
  public void temptest() {
    boolean monoTest = (boolean) Mono.just("")
      .flatMap(x -> Mono.error(new NoSuchMethodException()))
      .onErrorResume(x -> x instanceof NoSuchMethodException ? Mono.just(true) : Mono.just(false))
      .block();
    boolean fluxMultiTest = (boolean) Flux.just("", "")
      .flatMap(x -> Mono.error(new NoSuchMethodException()))
      .onErrorResume(x -> x instanceof NoSuchMethodException ? Mono.just(true) : Mono.just(false))
      .next()
      .block();
    boolean fluxTest = (boolean) Flux.just("")
      .flatMap(x -> Mono.error(new NoSuchMethodException()))
      .onErrorResume(x -> x instanceof NoSuchMethodException ? Mono.just(true) : Mono.just(false))
      .next()
      .block();

    assertTrue("Mono test failed", monoTest);
    assertTrue("Flux Multi test failed", fluxMultiTest);
    assertTrue("Flux test failed", fluxTest);  // The only assertion that fails
  }
```

While we are lucky that we caught this issue in test, this now forces us to understand at every step whether the Flux is emitting a single element or more, and in areas of unpredictable behavior, we are forced to check both the actual exception and the ReactiveException, which does not seem to be the documented behavior.

### PR DESCRIPTION
**Pull request by simonbasle**
Due to the usage of Operators.onNextPollError for the purpose of error
mode with scalar sources, which returns a RuntimeException, the original
errors can be wrapped in a ReactiveException (provided they're not a
RuntimeException already).

This is problematic, since this occurs even if no error mode strategy
is in place.

This change introduces a new Operators.onNextError variant that doesn't
wrap the exception nor cancels a Subscription. It merely returns the
original error to be passed to onError.

### CODE REVIEW

File: reactor-core/src/test/java/reactor/core/publisher/FluxFlatMapTest.java [hunk 1]
```diff
@@ -1688,4 +1688,36 @@ public void errorModeContinueScalarSourceMappedCallableFails() {
 
 		assertThat(msg).contains("42 skipped, reason: boom");
 	}
+
+	@Test
+	public void noWrappingOfCheckedExceptions() {
+		Flux.just("single")
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/FluxFlatMapTest.java]: nit: these tests could use some parameterization, but this is minor
