### PR TITLE
fix #1260 Race condition on refCount quick subscribe-and-cancel

### LINKED ISSUE #1260: Dropped signal in ConnectableFlux with multiple subscriptions
Hi,

I think that the following code introduces a bug. After onNextDropped is invoked, no more signals are received by the subscriptions.

### Expected behavior
Console output:
```
Signal count: 100000
Signal count: 100000
```

### Actual behavior
Console output:
```
[DEBUG] (Thread-0) onNextDropped: Test
Signal count: 1458
Signal count: 4
```

### Steps to reproduce
```
final Flux testFlux = Flux.create(fluxSink -> fluxSink.next("Test")).replay(1).refCount();

final Runnable subscriber = () -> {
    final AtomicInteger signalCount = new AtomicInteger();

    for (int i = 0; i < 100000; i++) {
        testFlux.next().subscribe(signal -> signalCount.incrementAndGet(), System.err::println);
    }

    System.out.println("Signal count: " + signalCount);
};

new Thread(subscriber).start();
new Thread(subscriber).start();
```

### Reactor Core version
3.1.8.RELEASE

### JVM version (e.g. `java -version`)
1.8.0_171

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/FluxRefCount.java [hunk 1]
```diff
@@ -61,21 +57,58 @@ public int getPrefetch() {
...
+		}
+
+		source.subscribe(new RefCountInner<>(actual, state));
+		if (connect) {
+			source.connect(state);
+		}
+	}
+
+	void connectionCancel(RefCountMonitor rc) {
+		synchronized (this) {
```
Comment (smaldini) [inline reactor-core/src/main/java/reactor/core/publisher/FluxRefCount.java]: we can't use synchronized if we nest user/external calls (like dispose())

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxRefCount.java]: do you mean we need to exit the synchronized block before calling the user code? (this reflects the way things are done in RxJava2 btw)

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxRefCount.java]: external call poses the risk that the `dispose()` method would recursively re-subscribe, need to polish that
