### PR TITLE
fix #2160 Accommodate ASYNC fusion in Mono.metrics()

### LINKED ISSUE #2160: Enabling metrics causes NPE or hanging on certain cases
## Expected Behavior
Enabling metrics using `Mono#metrics` has no effect on the behavior of the `Mono`, other than enabling metrics.

## Actual Behavior
Enabling metrics using `Mono#metrics` may cause a `NullPointerException` or hanging on certain cases.

## Steps to Reproduce

```java
@Test
@Timeout(value = 10, unit = SECONDS)
void this_hangs() {
    StepVerifier.create(
                    Mono.fromSupplier(() -> List.of(1, 2, 3))
                            .metrics()
                            .flatMapIterable(Function.identity()))
            .expectNext(1, 2, 3)
            .verifyComplete();
}

@Test
void this_throws_NPE() {
    StepVerifier.create(
                    Mono.using(
                                    () -> "irrelevant",
                                    irrelevant -> Mono.fromSupplier(() -> List.of(1, 2, 3)),
                                    irrelevant -> {})
                            .metrics()
                            .flatMapIterable(Function.identity()))
            .expectNext(1, 2, 3)
            .verifyComplete();
}
```

## Possible Solution
Applying any of the following workarounds fixes both tests:
* Removing the `.metrics()` operator.
* Replacing `.flatMapIterable(Function.identity()))` with `.flatMapMany(Flux::fromIterable))`.
* Replacing `Mono.fromSupplier(() -> List.of(1, 2, 3))` with `Mono.just(List.of(1, 2, 3))`.

## Your Environment
* Reactor version: Dysprosium-SR7, 3.3.5.RELEASE.
* JVM version: openjdk 11.0.6 2020-01-14.

### PR DESCRIPTION
**Pull request by alex-dukhno**
Closes #2160

### CODE REVIEW

**Comment by alex-dukhno** [comment]
@simonbasle I adapt tests for `Flux` and the issue is not reproducible for the `Flux`

File: reactor-core/src/test/java/reactor/core/publisher/FluxMetricsTest.java [hunk 1]
```diff
@@ -456,4 +459,29 @@ public void flowDurationTagsConsistency() {
...
+
+	@Test
+	public void ensureFuseablePropagateOnComplete_inCaseOfAsyncFusion() {
+		Flux.fromIterable(Arrays.asList(1, 2, 3))
+		    .metrics()
+		    .flatMapIterable(Arrays::asList)
+		    .as(StepVerifier::create)
+		    .expectNext(1, 2, 3)
+		    .expectComplete()
+		    .verify(Duration.ofMillis(1));
```
Comment (simonbasle) [inline reactor-core/src/test/java/reactor/core/publisher/FluxMetricsTest.java:471]: the `Duration` in the `verify` method is an upper bound after which the test times out. `1ms` is a bit short, as it could hiccup (eg. on CI machines). I suggest you raise it to `Duration.ofSeconds(1)` everywhere just to be on the safe side

**Comment by simonbasle** [comment]
@alex-dukhno I've changed the base branch of the PR to `3.3.x`. As you can see, it now includes irrelevant commits from master. Please rebase your branch on top of `3.3.x` and ensure it doesn't include these irrelevant commits:

```bash
git checkout fix-when-metrics-enabled
git rebase -i 3.3.x
```
In the editor, delete the lines that don't correspond to one of your relevant commits, save, then:
```bash
git push --force-with-lease
```

**Comment by simonbasle** [comment]
(I went ahead and did the rebase myself, should be good for merging in a couple minutes @alex-dukhno 👍)
