### PR TITLE
fix #247 Improve doOn callback failures handling

### LINKED ISSUE #247: Improve doOn callback failures handling
Currently peek set done property to true onComplete but when onComplete callbacks fail it might delegate to onError handling which first checks that done property.

### PR DESCRIPTION
**Pull request by simonbasle**
@smaldini we should probably improve on this by making sure all 3
variants of `FluxPeekFuseable` are tested (conditional, fuseable and
conditional-fuseable).

There is also the potential inconsistency of FluxPeekFuseableSubscriber
calling `throwIfFatal(t)` in onError(t) whereas FluxPeekSubscriber does
not...

### CODE REVIEW

File: src/main/java/reactor/core/publisher/FluxPeek.java [hunk 1]
```diff
@@ -173,17 +173,26 @@ public void onError(Throwable t) {
 				return;
 			}
 			done = true;
+			boolean errorCallbackFailed = false;
 			if(parent.onErrorCall() != null) {
```
Comment (simonbasle) [inline src/main/java/reactor/core/publisher/FluxPeek.java]: here, `FluxPeekFuseable` variants would first call `Exceptions.throwIfFatal(t)`

**Comment by smaldini** [comment]
Even if duplicate I would consider direct onError callback call rather than adding a field to a very common operator.

**Comment by dfeist** [comment]
Looks like this PR may also resolve #272 (and duplicate #253) and not just #247.  If you plan to put both fixes in together please take a look at my PR https://github.com/reactor/reactor-core/pull/273 and ensure this covers that scenario fully.  Then we can close all three issues :-)

File: src/main/java/reactor/core/publisher/FluxPeek.java [hunk 2]
```diff
@@ -174,16 +174,22 @@ public void onError(Throwable t) {
...
 			done = true;
 			if(parent.onErrorCall() != null) {
-				parent.onErrorCall().accept(t);
+				try {
+					parent.onErrorCall().accept(t);
+				}
+				catch (Throwable e) {
+					Exceptions.throwIfFatal(e);
+					e.addSuppressed(t);
+					t = e;
```
Comment (dfeist) [inline src/main/java/reactor/core/publisher/FluxPeek.java]: Shouldn't `onOperatorError` be used here?

**Comment by simonbasle** [comment]
@dfeist added your tests from #272 and #253 to the test cases in this PR + fixed your comment about wrapping the onError callback exception using `Operators.onOperatorError`. This PR will now close all 3 issues and your PR.

**Comment by dfeist** [comment]
@simonbasle Fantastic. Feel free to close my PR once this goes in.  Sorry, I hadn't seen this PR when I put mine together and although I'd seen #247 it talked about complete callback and not others. Might be a good idea to update issue description, just for correctness.
