### PR TITLE
fix #301 flatMapSequential broken with more than prefetch src elements

### LINKED ISSUE #301: flatMapSequential is broken with more than `prefetch` source elements
The logic in creating the bounded queue for inner subscribers is inverted and thus takes the minimum of `maxConcurrency` and `prefetch`, undersizing the queue.

Unfortunately, the queue offering of new subscribers isn't checked, and thus as soon as there are more than `prefetch` subscribers, the excess is silently discarded :(

**Workaround**: Use the same value for prefetch and maxConcurrency: `.flatMapSequential(v -> ..., CONCURRENCY, CONCURRENCY)`.

**Fix**: Fix the queue sizing logic and add a sanity check when doing the eager inner subscribing.

### PR DESCRIPTION
**Pull request by simonbasle**
Note: Reworded javadoc to highlight the difference with concat/concatMap and merge/flatMap.

Made the exception in case of queue failure testable by providing a package-private ctor.

### CODE REVIEW

**Comment by simonbasle** [comment]
cc @devrandom

File: src/main/java/reactor/core/publisher/FluxMergeSequential.java [hunk 1]
```diff
@@ -128,18 +142,16 @@ public void subscribe(Subscriber<? super R> s) {
...
+				Supplier<Queue<MergeSequentialInner<R>>> queueSupplier) {
 			this.actual = actual;
 			this.mapper = mapper;
 			this.maxConcurrency = maxConcurrency;
 			this.prefetch = prefetch;
 			this.errorMode = errorMode;
-			this.subscribers = QueueSupplier.<MergeSequentialInner<R>>get(Math.min(
-					prefetch,
-					maxConcurrency)).get();
+			this.subscribers = queueSupplier.get();
```
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMergeSequential.java]: In RxJava 2, the subscribes is an unbouded queue with the island size of the smaller value because sometimes `maxConcurrency` could be `Integer.MAX_VALUE` yet `prefetch` is reasonable.

Comment (simonbasle) [inline src/main/java/reactor/core/publisher/FluxMergeSequential.java]: yep, bad bad me for I didn't think when I blindly used the same sizing strategy **on a bounded queue** 😭 🔔 *shame* 🔔
