### PR TITLE
fix #1739 Enforce a name for Schedulers.fromExecutorService

### LINKED ISSUE #1739: reactor.scheduler.id metric tag for Schedulers.fromExecutorService is not useful
When using a `Scheduler` created via `Schedulers.fromExecutorService`, with metrics enabled via `Schedulers.enableMetrics()`, the metrics for the scheduler are tagged with `reactor.scheduler.id=fromExecutorService(null)`, which is not very useful.

The first problem is the `null` string, which is caused by:
1. [`this` escaping the constructor](http://www.javapractices.com/topic/TopicAction.do?Id=252) of `DelegateServiceScheduler` [here](https://github.com/reactor/reactor-core/blob/d4fd8c61d75e9ab44a98524ae8d9a52cfc4868b8/reactor-core/src/main/java/reactor/core/scheduler/DelegateServiceScheduler.java#L50).
2. The `decorateExecutorService` call results in the `SchedulerMetricDecorator` accessing the not-fully-constructed `DelegateServiceScheduler` when it [scans for the Attr.NAME](https://github.com/reactor/reactor-core/blob/d4fd8c61d75e9ab44a98524ae8d9a52cfc4868b8/reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java#L49-L51)
3. The scan calls back into the not-fully-constructed `DelegateServiceScheduler` [scanUnsafe](https://github.com/reactor/reactor-core/blob/d4fd8c61d75e9ab44a98524ae8d9a52cfc4868b8/reactor-core/src/main/java/reactor/core/scheduler/DelegateServiceScheduler.java#L101)
4. At that point, the executor is null, because `this.executor` hasn't been assigned yet from step 1

The second problem is that even if the first problem was solved, using the [`executor.toString()`](https://github.com/reactor/reactor-core/blob/d4fd8c61d75e9ab44a98524ae8d9a52cfc4868b8/reactor-core/src/main/java/reactor/core/scheduler/DelegateServiceScheduler.java#L101) as the scheduler name, and therefore in the `reactor.scheduler.id` tag, is questionable.  The standard executor service implementations provided by the JDK have toString() values that change based on the state of the executor service.  For example, [`java.util.concurrent.ThreadPoolExecutor` includes the number of active tasks, etc in the `toString()` value](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/concurrent/ThreadPoolExecutor.java#l1916).  Using such an unpredictable value in a tag is bad.

It seems that there should be a first class way of providing a scheduler name/id.  You could somewhat do this by wrapping an ExecutorService in something that provides a better .toString() , but that seems like a hack.

### Expected behavior

`reactor.scheduler.id` metric tag value for `Schedulers.fromExecutorService` has a useful value.

### Actual behavior

`reactor.scheduler.id=fromExecutorService(null)`

See main description.

### Steps to reproduce

1. Call `Schedulers.enableMetrics()`
2. Construct a scheduler via `Schedulers.fromExecutorService`
3. Observe tag values of metrics for the scheduler

### Reactor Core version

3.2.9.RELEASE

### JVM version (e.g. `java -version`)

11.0.2

### PR DESCRIPTION
**Pull request by simonbasle**
This avoids relying on the underlying ExecutorService's toString, at
least for the purpose of calling `scan(Attr.NAME)`.

Previously, relying on the backing ExecutorService#toString method
was not ideal as this generally depends on the state of the executor,
which is not ideal for most usages of `NAME` and especially not for
metrics (where NAME is used a a differentiating tag for the meters).

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java [hunk 1]
```diff
@@ -118,9 +118,24 @@ public static Scheduler fromExecutor(Executor executor, boolean trampoline) {
 	 * @param executorService an {@link ExecutorService}
 	 *
 	 * @return a new {@link Scheduler}
+	 * @deprecated prefer using {@link #fromExecutorService(ExecutorService, String)},
+	 * especially if you plan on using metrics as this gives the executor a meaningful identifier
 	 */
+	@Deprecated
 	public static Scheduler fromExecutorService(ExecutorService executorService) {
-		return new DelegateServiceScheduler(executorService);
+		return fromExecutorService(executorService, null);
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java]: WDYT about using `"anonymous-" + System.identityHashCode(executorService)`?

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java]: good idea! plus added benefit of avoiding nullable string 👍

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java]: updated

File: reactor-core/src/test/java/reactor/core/scheduler/SchedulersMetricsTest.java [hunk 2]
```diff
@@ -3,36 +3,41 @@
...
 
+import reactor.core.Disposable;
+import reactor.core.Disposables;
+
 import static org.assertj.core.api.Assertions.assertThat;
 
 public class SchedulersMetricsTest {
 
 	final SimpleMeterRegistry simpleMeterRegistry = new SimpleMeterRegistry();
+	Disposable.Composite toCleanUp;
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/scheduler/SchedulersMetricsTest.java]: Really like it!

minor: would be cool to have it in `DelegateServiceSchedulerTest` too 👍

File: reactor-core/src/test/java/reactor/core/scheduler/SchedulersMetricsTest.java [hunk 3]
```diff
@@ -3,36 +3,41 @@
...
 
 	@Before
 	public void setUp() {
 		Metrics.addRegistry(simpleMeterRegistry);
 		Schedulers.enableMetrics();
+		toCleanUp = Disposables.composite();
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/scheduler/SchedulersMetricsTest.java]: I'm curious why you didn't make it `final` and initialize in the field's declaration? JUnit creates a new instance of the test class for each test anyways

**Comment by simonbasle** [comment]
cc @philsttr does that look like a good fix for the particular issue of the `fromExecutorService` name?

**Comment by philsttr** [comment]
Looks good to me. Thanks @simonbasle
