### PR TITLE
Fix #2196: don't hang on repeatWhenEmpty + discard handler

### LINKED ISSUE #2196: repeatWhenEmpty hangs on cancel when discard hook is present
## Expected Behavior
It should be safe to cancel the sequence.

## Actual Behavior
Cancelling a sequence which is in a `repeatWhenEmpty()` loop will cause issues when a discard hook has been registered. In that case `Operators.onDiscardMultiple()` is invoked with the iterator used to keep track of the current iteration and the hook would be called for every remaining number up to `Long.MAX_VALUE`. 

## Steps to Reproduce
This test case will succeed when removing the `doOnDiscard()` operator.

```java
@Test
public void shouldCompleteEventually()
{
    StepVerifier.create(Mono.empty()
                            .repeatWhenEmpty(Repeat.once())
                            .doOnDiscard(PooledDataBuffer.class, DataBufferUtils::release))
                .thenAwait()
                .thenCancel()
                .verify(Duration.ofSeconds(5));
}
```

## Possible Solution
Probably we should treat the remaining iterations in a way that they can be safely discarded without bothering any application level hooks. Also, I guess `FluxStream` should not be considered "knownToBeFinite" if its size is `Long.MAX_VALUE`.

## Your Environment
* Reactor version(s) used: 3.3.6.RELEASE

### PR DESCRIPTION
**Pull request by ericbottard**

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/Mono.java [hunk 1]
```diff
@@ -3416,23 +3417,16 @@ public T block(Duration timeout) {
...
+				return repeatFactory.apply(o.index().map(Tuple2::getT1));
 			}
 			else {
-				iterations = Flux
-					.range(0, maxRepeat)
-					.map(Integer::longValue)
-					.concatWith(Flux.error(new IllegalStateException("Exceeded maximum number of repeats"), true));
+				return repeatFactory.apply(o.index().map(Tuple2::getT1)
+						.take(maxRepeat)
+						.concatWith(Flux.error(new IllegalStateException("Exceeded maximum number of repeats"), true)));
```
Comment (robotmrv) [inline reactor-core/src/main/java/reactor/core/publisher/Mono.java:3427]: @ericbottard  @simonbasle   
isn't it better to use `Flux.error(Supplier)` version?  
as it always creates Exception which captures stacktrace ?

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/Mono.java:3427]: this could be an improvement to the existing code yeah, nothing to do with the bug addressed by this PR though. do you want to submit a PR @robotmrv ?

Comment (robotmrv) [reply reactor-core/src/main/java/reactor/core/publisher/Mono.java:3427]: @simonbasle   
created PR https://github.com/reactor/reactor-core/pull/2221
