### PR TITLE
fix #1442 Add putNonNull and size to Context

### LINKED ISSUE #1442: Add null safe put method to Context interface
For now `reactor.util.context.Context#put` throws exception when receive null value. It would be better to nullsafe methods like:

    Context put(Object key, Optional<Object> value);

Intenally it should check whether `Optional.isPresent` and merge or not value into Context.

Now additional nullchecks leads to boilerplate code:

    ctx -> {
         if (some !=null) {
                  ctx.put("someKey", some);
         }
         return ctx;
    }

With new method:

    ctx -> ctx.put("someKey", Optional.ofNullable(some));

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

File: reactor-core/src/test/java/reactor/util/context/ContextNTest.java [hunk 1]
```diff
@@ -296,4 +296,30 @@ public void putAllOfEmpty() {
...
+		assertThat(put).isNotSameAs(c);
+		assertThat(put.getOrEmpty("putNonNull")).contains("value");
+		assertThat(put.size()).isEqualTo(expectedSize);
+	}
+
+	@Test
+	public void contextSize() { //renamed to allow import of size() Condition from ContextTest
+		assertThat(c.size()).isEqualTo(6);
+
+		assertThat(c.put("sizeGrows", "yes").size()).isEqualTo(7);
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/util/context/ContextNTest.java]: I would suggest `assertThat(c.put("sizeGrows", "yes")).hasSize(7)`. It will print the resulting Map if assertion fails and help to debug
