### PR TITLE
fix #1787 Eagerly remove executor metrics

### LINKED ISSUE #1787: ExecutorService metrics remain even after the scheduler is terminated
Since there is no way of removing reporter in Micrometer, once [we apply the decorator](https://github.com/reactor/reactor-core/blob/832d870a2ee7b36286750f69719a45245b18f55e/reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java#L82) it will continue reporting even if we terminate the scheduler & executor.

Steps to reproduce:
1. Enable metrics
2. Create a scheduler
3. Submit a task
4. Dispose the scheduler
5. Observe metrics being reported for the underlying executor after it got disposed

### PR DESCRIPTION
**Pull request by bsideup**
Fixes #1787

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java [hunk 1]
```diff
@@ -78,7 +79,32 @@ in order to avoid consider two calls in a row as duplicates (yet still being abl
...
+
+			@Override
+			public void shutdown() {
+				removeMetrics();
+				super.shutdown();
+			}
+
+			void removeMetrics() {
+				Search.in(globalRegistry)
+				      .tags(tags)
```
Comment (simonbasle) [inline reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java]: Is the `executorId` already part of the `tags`? otherwise unrelated executor meters could be removed when a single executor is shutdown out of a pool.

File: reactor-core/src/test/java/reactor/core/scheduler/SchedulersMetricsTest.java [hunk 2]
```diff
@@ -256,4 +258,27 @@ public void shouldReportExecutionTimes(Supplier<Scheduler> schedulerSupplier, St
 					.isEqualTo(taskCount);
 		});
 	}
+
+	@Test
+	public void shouldRemoveOnShutdown() {
+		Scheduler scheduler = afterTest.autoDispose(Schedulers.newParallel("A", 1));
```
Comment (simonbasle) [inline reactor-core/src/test/java/reactor/core/scheduler/SchedulersMetricsTest.java]: to test the above, make it `2`, capture a `Worker` to hold onto an executor and then call `createWorker()` a second time then `dispose()` that worker.
you can then verify the registry finds half as much meters as it did before the dispose, and that the meters for the first executor are still there.

File: reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java (hunk 1 above)
Comment (bsideup) [reply reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java]: you're right. Fixing (and will add a test)

**Comment by bsideup** [comment]
@simonbasle I changed to `await()` because it seems that the tests were failing on Travis (but work locally), let's see whether it helps or not
