### PR TITLE
fixes breaking change for `fromFuture` source cancellation

### LINKED ISSUE #3235: `Mono.fromCompletionStage` behaves differently from the documentation
## Documentation Issue
`Mono.fromCompletionStage` is documented to not cancel the future, but in pull request #3146 it was updated to do so. 

## Additional context
I was previously relying on the future not being cancelled, what is the recommended way to to get that behavior back?

### PR DESCRIPTION
**Pull request by OlegDokuka**
This PR rollbacks changes introduces by #3146 and reintroduce through a new configurable overload

closes #3235

Signed-off-by: Oleh Dokuka <odokuka@vmware.com>

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java [hunk 1]
```diff
@@ -52,7 +60,7 @@ public void subscribe(CoreSubscriber<? super T> actual) {
             @Override
             public void cancel() {
                 super.cancel();
-                if (future instanceof Future) {
+                if (cancel) {
```
Comment (chemicL) [inline reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java:63]: I believe the `instanceof` check is still required.

Comment (OlegDokuka) [reply reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java:63]: it is impossible that `cancel == true` and `!future instanceof Future`. The public API allows only `CompletableFuture` to have the `cancel` flag configurable. in all other cases, it is false. This, checking instance of in addition to cancel is true will be overhead

Comment (OlegDokuka) [reply reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java:63]: check the following code -> https://github.com/reactor/reactor-core/pull/3252/files#diff-e815d2e7a55f9f17006048ff085897e713143567345688c33e9d64b19f911f06R51

**Review by simonbasle — APPROVED** [review]

**Review by rstoyanchev — COMMENTED** [review]
This is a regression, no doubt, but arguably passing on the cancellation signal is the intuitive default behavior that probably should have been the starting point. 

From that point of view of the common case, the new `fromFuture` overload could call this flag `suppressCancel` where a value of `true` reflects the main reason for using the overload. It would also mean scaling back on having two overloaded methods. Perhaps just one is sufficient? We don't need to aim for full convenience of an uncommon case.

I've asked for clarification on the use case under #3235 that may provide further context related to this.

**Comment by OlegDokuka** [comment]
> This is a regression, no doubt, but arguably passing on the cancellation signal is the intuitive default behavior that probably should have been the starting point. 
> 
> From that point of view of the common case, the new `fromFuture` overload could call this flag `suppressCancel` where a value of `true` reflects the main reason for using the overload. It would also mean scaling back on having two overloaded methods. Perhaps just one is sufficient? We don't need to aim for full convenience of an uncommon case.
> 
> I've asked for clarification on the use case under #3235 that may provide further context related to this.

Sounds good! Thanks.

**Comment by benwiles1** [comment]
`Mono.fromCompletionStage` docs might want to be updated to also mention that `Mono.fromFuture` is an alternative that can be used to get the cancel logic.
as in suggest `Mono.fromFuture(stage.toCompletableFuture(), true)`

**Comment by benwiles1** [comment]
although maybe not very obvious this change does make it so that `Mono.fromCompletionStage(future)` doesn't have cancel logic. instead of having cancel logic based on the runtime type of `future`, which I think is overall a good thing.

**Review by simonbasle — APPROVED** [review]

**Comment by OlegDokuka** [comment]
@rstoyanchev @benwiles1 updated the PR as you both suggested. Feel free to have a look
