### PR TITLE
fix #2319 Split emitXxx/tryEmitXxx

### LINKED ISSUE #2319: Further refine the Sinks API: emitXxx vs tryEmitXxx
## Motivation
The `emitXxx` API relying on users checking the return value is maybe too brittle, leaving too much room for users purely ignoring said return value.

## Desired solution
Double the API to offer a throw-vs-enum choice:
 - `void emitXxx()` which throws an exception
 - `Emission tryEmitXxx()` which doesn't throw but returns an `Emission`: the `try` prefix better conveys that failure mode is communicated through the returned enum

## Considered alternatives
 - Adding `orThrow()` to `Emission`, but it is easier to still ignore the `Emission` altogether

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

**Comment by simonbasle** [comment]
@smaldini as I work on this refinement, I found that there is a lot of inconsistencies on how `FAIL_OVERFLOW` is delivered. Sometimes it propagates an exceptions to subscribers AND returns `FAIL_OVERFLOW`, sometimes it propagates to subscribers but returns `OK`, sometimes it just returns `FAIL_OVERFLOW`... The usage of dropped/discard hooks is also a bit debatable in my opinion.

In this PR I tried to make things more predicable so that `tryEmitXxx` methods usually don't invoke hooks, leaving it to the user to decide what to do with the rejected (value|exception).

As a consequence, `emitXxx` methods DO invoke the hooks with the intention of implementing sane default behavior when the user doesn't want to chose what to do with the `Emission` result (or doesn't want to check it at all).

**Comment by simonbasle** [comment]
@reactor/core-team and @smaldini this is probably going to be an extensive PR so don't hesitate to start reviewing despite the draft status. I'll try to make small commits as it progresses.

File: reactor-core/src/main/java/reactor/core/publisher/DelegateSinkFluxProcessor.java [hunk 1]
```diff
@@ -47,17 +47,17 @@ public Context currentContext() {
...
 	@Override
 	public void onError(Throwable t) {
-		sink.emitError(t);
+		sink.tryEmitError(t);
 	}
 
 	@Override
 	public void onNext(IN in) {
-		sink.emitNext(in);
+		sink.tryEmitNext(in);
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/DelegateSinkFluxProcessor.java:60]: IMO this and many other usages should use the regular emitNext that would fail on overflow. Otherwise we're introducing the same problem as in M2

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/DelegateSinkFluxProcessor.java:60]: good catch, indeed and same for `DelegateSinkOneMonoProcessor`

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/DelegateSinkFluxProcessor.java:60]: this will actually greatly simplify the PR since most uses in tests will be back to calling `emitXxx`

File: reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java [hunk 2]
```diff
@@ -166,13 +189,33 @@ public Emission emitError(Throwable t) {
 	}
 
 	@Override
-	public Emission emitNext(T t) {
+	public void emitNext(T value) {
+		Emission result = tryEmitNext(value);
+		if (result == Emission.FAIL_OVERFLOW) {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java:194]: nit: could use a `switch` for readability _and_ performance

File: reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java [hunk 3]
```diff
@@ -147,14 +158,26 @@ public Emission emitComplete() {
...
 	@Override
-	public Emission emitError(Throwable t) {
+	public void onError(Throwable throwable) {
+		emitError(throwable);
+	}
+
+	@Override
+	public void emitError(Throwable error) {
+		Emission result = tryEmitError(error);
+		if (result == Emission.FAIL_TERMINATED) {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java:168]: while migrating some of r-kafka code, I had the following in mind:
what if r-core adds more "negative" `Emission` cases but I only handle one.

Hence the idea:
Add `Emission#isSuccessful`, so that it can be checked in places like this one.

WDYT?

File: reactor-core/src/main/java/reactor/core/publisher/NextProcessor.java [hunk 4]
```diff
@@ -114,17 +114,41 @@ public O block(@Nullable Duration timeout) {
 	}
 
 	@Override
-	public Emission emitEmpty() {
-		return emitValue(null);
+	public final void onComplete() {
+		//no particular error condition handling for onComplete
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/NextProcessor.java:118]: idea:
```java
@SuppressWarnings("unused")
Emission emission = tryEmitEmpty();
```

File: reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java (hunk 3 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java:168]: there's `hasEmitted()` and `hasFailed()`. Maybe I should rename `hasEmitted()` to `hasSucceeded()`? not sure what you mean by "checked in places like this one" though... are you suggesting this piece of code should check something more?

Comment (bsideup) [reply reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java:168]: Ah, cool, so we can use `hasEmitted()` here (although renaming it to `hasSucceeded()` would be nice).
BTW isn't `hasFailed() == !hasEmitted()`? Why both?

re "can be checked in places like this one":
sorry, I meant this method is a good example where such boolean could be handy, and there are more methods like this one (in this PR but also in r-kafka, for example), hence "the flag that can be checked in places like this one"

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java:168]: yeah, I think it was just added because it reads better. And most likely, `hasFailed()` is going to be the more interesting one to check...

I've opened a separate issue to track these

File: reactor-core/src/main/java/reactor/core/publisher/DelegateSinkFluxProcessor.java (hunk 1 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/DelegateSinkFluxProcessor.java]: I've rebased so that a single commit has the introduction of tryEmit BUT correct use of emit in test classes

File: reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java (hunk 2 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java]: done

File: reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java (hunk 3 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java:168]: added a commit for #2329 in the latest rebase (with the `orThrow` split out of the original tryEmit commit)

**Comment by simonbasle** [comment]
With the introduction of #2329, I've reorganized the commits a bit with a first interactive rebase: extracted the `inners[]` parameter change in `Operators` in separate commit, split out `orThrow()` change in #2329-dedicated commit and squashed the two biggest commits so that introducing tryEmit doesn't change most tests.

kept other recent commits for review purposes, but I will squash these before merging.

File: reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java (hunk 3 above)
Comment (bsideup) [reply reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java:171]: Either I don't see it or don't get it :D 

Anyways, shouldn't it be:
```suggestion
		if (result.hasFailed()) {
```
?

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java:171]: no. for an emitError, cancelled or overflown states don't warrant specific action, whereas an attempt at terminating twice is illegal and usually notified to the `onErrorDropped`

Comment (bsideup) [reply reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java:171]: ok 👍

File: reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java [hunk 5]
```diff
@@ -280,8 +328,7 @@ public Emission emitNext(T t) {
 					ex.initCause(e);
 				}
 			}
-			Operators.onDiscard(t, ctx);
-			onError(ex);
+			onError(ex); //FIXME should this really error ??
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java:331]: this one is indeed inconsistent with other usages. `tryEmitNext` should probably not emit any error here

File: reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java [hunk 6]
```diff
@@ -1186,8 +1184,15 @@ public void mapNotifiesOnce() throws InterruptedException {
 			                            }
 		                            }));
 
+		final long start = System.currentTimeMillis();
 		for (int i = 0; i < COUNT; i++) {
-			while (s.emitNext(i).hasFailed() );
+			long busyLoops = 0;
+			while (s.tryEmitNext(i).hasFailed() ) {
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java:1190]:
```suggestion
			while (s.tryEmitNext(i).hasFailed()) {
```

File: reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java [hunk 7]
```diff
@@ -1186,8 +1184,15 @@ public void mapNotifiesOnce() throws InterruptedException {
...
+				busyLoops++;
+				if (busyLoops % 5000 == 0 && System.currentTimeMillis() - start >= 10_0000) {
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java:1192]: nit: this whole thing can be replaced with Awaitility, I think

File: reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java [hunk 8]
```diff
@@ -1226,8 +1231,15 @@ public void mapManyFlushesAllValuesThoroughly() throws InterruptedException {
 			latch.countDown();
 		});
 
+		final long start = System.currentTimeMillis();
 		for (int i = 1; i <= items; i++) {
-			while (s.emitNext(String.valueOf(i)).hasFailed() );
+			long busyLoops = 0;
+			while (s.tryEmitNext(String.valueOf(i)).hasFailed() ) {
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java:1237]: ditto

File: reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxSpecTests.java [hunk 9]
```diff
@@ -1103,8 +1103,15 @@ public void collectFromMultipleThread1() throws Exception {
 					latch.countDown();
 				});
 
+		final long start = System.currentTimeMillis();
 		Flux.range(1, 1000).subscribe(data -> {
-			while(head.emitNext(data).hasFailed());
+			long busyLoops = 0;
+			while(head.tryEmitNext(data).hasFailed()) {
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxSpecTests.java:1109]: ditto

File: reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxTests.java [hunk 10]
```diff
@@ -589,7 +589,13 @@ private void parallelBufferedTimeoutTest(int iterations) throws InterruptedExcep
 		long start = System.currentTimeMillis();
 
 		for (String i : data) {
-			while (deferred.emitNext(i).hasFailed() );
+			long busyLoops = 0;
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxTests.java:592]: ditto

File: reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java (hunk 5 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java:331]: I opened a separate issue, `SerializedManySink` is also guilty of a similar thing

File: reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java (hunk 7 above)
Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java:1192]: I tried, but it makes the test longer and the tuning of poll interval is complicated, I won't have time to fine tune it.

File: reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java (hunk 6 above)
Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java]: the extra space appears in several other places, I'll fix it
