### PR TITLE
fix #1414 Detect cancelled subscriber in MonoCompletionStage

### LINKED ISSUE #1414: MonoCompletableStage should ignore stage's signals once cancelled
Copied from reactor/reactor#652 by @daschl

Hi,

after talking to @simonbasle, opening a ticket here to investigate.

The use case I am having is that a `CompletableFuture<T>` represents an eventual response which I wrap in a `Mono<T>`. Now once the subscriber stops listening to the mono for whatever reason (i.e. timeout, picked a different mono,...) then there is no need in scheduling the future in the system so I want to cancel it explicitly. 

Here is a simplified example (my exception is a different one, but the same applies):

```java
  @Test
  void shouldPropagateException() {
    CompletableFuture<Integer> future = new CompletableFuture<>();
    Mono<Integer> mono = Mono
      .fromFuture(future)
      .doFinally(st -> future.completeExceptionally(new CancellationException()));

    assertThrows(Exception.class, () -> mono.timeout(Duration.ofMillis(10)).block());
    assertTrue(future.isCompletedExceptionally());
  }
```

This test completes fine, the problem is that the logs complain that there is no `onErrorDropped` defined - my expectation is that since I do the "cleanup" finally, so the mono is already not in use anymore, this error should not be shown?

```
06:31:12 ERROR [reactor.core.publisher.Operators:300] Operator called default onErrorDropped
com.couchbase.client.core.error.StoppedListeningException: null
06:31:12 ERROR [reactor.core.publisher.Operators:300] Operator called default onErrorDropped
reactor.core.Exceptions$BubblingException: com.couchbase.client.core.error.StoppedListeningException
	at reactor.core.Exceptions.bubble(Exceptions.java:154) ~[reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.Operators.onErrorDropped(Operators.java:512) ~[reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:202) ~[reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onError(FluxDoFinally.java:129) ~[reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:61) ~[reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_112]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_112]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_112]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_112]
	at com.couchbase.client.core.msg.BaseRequest.fail(BaseRequest.java:78) ~[classes/:?]
	at com.couchbase.client.core.Reactor.lambda$wrap$0(Reactor.java:58) ~[classes/:?]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.cancel(FluxDoFinally.java:145) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:1906) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1875) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1687) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:287) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27) [reactor-core-3.2.2.RELEASE.jar:3.2.2.RELEASE]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_112]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_112]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

Of course I could define a a hook to silence the warning, but since I'm shipping a library this does not sound like the best idea.

Is this a bug or is that expected behavior? (and if so, how can I potentially work around this?)

Thanks!

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java [hunk 1]
```diff
@@ -56,6 +56,12 @@ public void subscribe(CoreSubscriber<? super T> actual) {
         }
 
         future.whenComplete((v, e) -> {
+            if (sds.isCancelled()) {
```
Comment (smaldini) [inline reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java]: should test if error is not null ?

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java]: Mmh, that was the source of the issue in the first place. if the mono is cancelled, sometimes the user wants to also cancel the `Future`, but said cancellation triggers `whenComplete`...

If that sounds very important that a cancelled Mono should still receive an error, then _maybe_ we can forward any error *other than a `CancellationException`* 🤔
