### PR TITLE
fix #1687 Change usingWhen API to use BiFunction for error handler

### LINKED ISSUE #1687: Propagate exception to asyncError in Flux/Mono.usingWhen
### Expected behavior

`Flux/Mono.usingWhen(…)` should provide an override accepting a `BiFunction<? super D,? super Throwable, ? extends Publisher<?>>` to propagate the error to the asynchronous error callback.

### Actual behavior

Currently, we translate transactional errors with `onErrorResume`:

```java
return Flux.usingWhen(Mono.just(it), action::doInTransaction,
		this.transactionManager::commit, s -> Mono.empty())
		.onErrorResume(ex -> rollbackOnException(it, ex).then(Mono.error(ex)));
```

In our case, we want to potentially post-process the exception.

### PR DESCRIPTION
**Pull request by simonbasle**
This PR introduces an API-breaking change, but maybe I could do it as a single full-argument additional overload (even though we try to avoid overloads where the only difference is  the number of inputs to a lambda parameter)...

cc @mp911de

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/Flux.java [hunk 1]
```diff
@@ -1745,6 +1745,45 @@
...
+	 * @param resourceSupplier a {@link Publisher} that "generates" the resource,
+	 * subscribed for each subscription to the main sequence
+	 * @param resourceClosure a factory to derive a {@link Publisher} from the supplied resource
+	 * @param asyncCleanup an asynchronous resource cleanup invoked when the resource
+	 * closure terminates (with onComplete, onError or cancel)
+	 * @param <T> the type of elements emitted by the resource closure, and thus the main sequence
+	 * @param <D> the type of the resource object
+	 * @return a new {@link Flux} built around a "transactional" resource, with asynchronous
+	 * cleanup on all terminations (onComplete, onError, cancel)
+	 * @deprecated prefer using the {@link #usingWhen(Publisher, Function, Function, BiFunction, Function)} version which is more explicit about all termination cases,
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/Flux.java]: funny enough, I find this one more preferable. When I was using this operator, I always needed 3 blocks:
1. create the resource
2. work with the resource
3. `finally` that will destroy the resource afterwards, no matter what happened (complete, error, cancel)

Since this operator is usually advertised as "async try-with-resources", it is essential to expect to have these 3 parameters.

Separation of complete/error/cancel will lead to the code duplication because (in my practice) in most of the cases the same code is invoked.

Just my 2c :)

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/Flux.java]: the callback themselves having error handling is something else entirely though... and a signal based approach would represent a larger change

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/Flux.java]: ok, what about this: leave the single callback version and the BiPredicate-with-3-callbacks versions undeprecated, and also introduce the single callback version to `Mono` for better API alignment. wdyt @bsideup ?

Comment (bsideup) [reply reactor-core/src/main/java/reactor/core/publisher/Flux.java]: `BiFunction` you mean? :)

I would say I'm fine with deprecating `usingWhen(Publisher,Function,Function,Function)` and `usingWhen(Publisher,Function,Function,Function,Function)`, but keeping `usingWhen(Publisher,Function,Function)` :)
