### PR TITLE
fix #2060 Introduce and use VirtualTimeScheduler#getOrSet(boolean)

### LINKED ISSUE #2060: VirtualTimeScheduler does not run scheduled tasks since 3.3.3.RELEASE
## Expected Behavior
`VirtualTimeScheduler` runs scheduled tasks at certain intervals.

## Actual Behavior
At version `3.3.3.RELEASE`, `VirtualTimeScheduler` runs the task once and never again, even though virtual time elapsed.

## Steps to Reproduce
With `io.projectreactor:reactor-test:3.2.15.RELEASE`, the following test passes. After updating to `3.3.3.RELEASE`, it hangs.

```
@Test
public void isolateIssue() {
	Scheduler.Worker subscriptionWorker = VirtualTimeScheduler.getOrSet().createWorker();
	List<String> source = Stream.of("first", "second", "third").collect(Collectors.toList());


	StepVerifier.withVirtualTime(() -> {
		EmitterProcessor<String> fluxEmitter = EmitterProcessor.create();

		subscriptionWorker.schedulePeriodically(() -> {
			if (source.size() > 0)
				fluxEmitter.onNext(source.remove(0));
			else
				fluxEmitter.onComplete();
		}, 0, 10, TimeUnit.MILLISECONDS);
		return fluxEmitter;
	})
			.expectNext("first")
			.expectNoEvent(Duration.ofMillis(10))
			.expectNext("second")
			.expectNoEvent(Duration.ofMillis(10))
			.expectNext("third")
			.expectNoEvent(Duration.ofMillis(10))
			.verifyComplete();
}
```

## Possible Solution
No solutions, but I suspect #2017 may have something to do with this.

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

File: reactor-test/src/test/java/reactor/test/StepVerifierTests.java [hunk 1]
```diff
@@ -2343,4 +2346,32 @@ public void verifyDrainOnRequestInCaseOfFusion2() {
...
+		Scheduler.Worker subscriptionWorker = VirtualTimeScheduler.getOrSet().createWorker();
+		List<String> source = Stream.of("first", "second", "third").collect(Collectors.toList());
+
+
+		StepVerifier.withVirtualTime(() -> {
+			EmitterProcessor<String> fluxEmitter = EmitterProcessor.create();
+
+			subscriptionWorker.schedulePeriodically(() -> {
+				if (source.size() > 0)
+					fluxEmitter.onNext(source.remove(0));
```
Comment (bsideup) [inline reactor-test/src/test/java/reactor/test/StepVerifierTests.java]: nit: `{}` are missing
