### PR TITLE
fix #1913 expectTimeout as an alternative to expectNoEvent.thenCancel

### LINKED ISSUE #1913: expectNoEvent does not fail test when event is actually emitted
## Expected Behavior
According to the Javadocs of `StepVerifier.expectNoEvent(Duration)`:
> Expect that no event has been observed by the verifier for the length of the provided Duration

When I create a `Mono` that emits an item, I would expect the verification to fail.

## Actual Behavior
`expectNoEvent` does wait for the specified duration, but does not seem to have any effect on the expectations.

## Steps to Reproduce

Consider the following unit test which is part of the project:
https://github.com/reactor/reactor-core/blob/5e9231edb8e3362730ae7c9b7f7dceeb336c5d17/reactor-test/src/test/java/reactor/test/StepVerifierTests.java#L1063

Change the publisher to `Mono.just("notNever")` so that it actually emits an event:
```java
@Test
public void verifyVirtualTimeNoEventNever() {
	StepVerifier.withVirtualTime(() -> Mono.just("notNever")
		                                   .log())
		        .expectSubscription()
		        .expectNoEvent(Duration.ofDays(10000))
		        .thenCancel()
		        .verify();
}
```
The test will still pass.

## Your Environment

* Reactor version(s) used: latest from master
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`): 13
* OS and version (eg `uname -a`): reproduced on Windows and macOS

### PR DESCRIPTION
**Pull request by simonbasle**
The `expectTimeout(d)` method is a preferred alternative to the
`expectNoEvent(d).thenCancel()` combination. It should do a better job
at avoiding false positives, and is more expressive of the expectation
that a Publisher "never ends" (although it is impossible to meaningfully
assert that without waiting for the heat death of the universe).

### CODE REVIEW

File: reactor-test/src/main/java/reactor/test/ValueFormatters.java [hunk 1]
```diff
@@ -48,6 +49,13 @@
 
 	private ValueFormatters() {}
 
+	/**
+	 * Default {@link Duration#toString() Duration} {@link ToStringConverter} that removes the PT prefix and
+	 * switches {@link String#toLowerCase() to lower case}.
+	 */
+	public static final ToStringConverter DURATION_CONVERTER = new ClassBasedToStringConverter<Duration>(
```
Comment (bsideup) [inline reactor-test/src/main/java/reactor/test/ValueFormatters.java]: WDYT about putting a new line after each lambda? `true, d` was a bit hard to read, confused with `(a, b) ->`-like lambda declaration :D

File: reactor-test/src/main/java/reactor/test/StepVerifier.java [hunk 2]
```diff
@@ -450,6 +450,21 @@ static void resetDefaultTimeout() {
...
+		 * <p>
+		 * This is equivalent to appending the {@link reactor.core.publisher.Flux#timeout(Duration) timeout}
+		 * operator to the publisher and expecting a {@link java.util.concurrent.TimeoutException}
+		 * {@link #expectError(Class) onError signal}, while also triggering a {@link Step#thenAwait(Duration) wait}
+		 * to ensure unexpected signals are detected.
+		 *
+		 * @param duration the {@link Duration} for which no new event is expected
+		 * @return the built verification scenario, ready to be verified
+		 */
+		StepVerifier expectTimeout(Duration duration);
```
Comment (bsideup) [inline reactor-test/src/main/java/reactor/test/StepVerifier.java]: is it chainable? (do we expect the users to call more `expect*` after `expectTimeout`?)
Or maybe we only need the `verifyTimeout` one?

File: reactor-test/src/test/java/reactor/test/StepVerifierTests.java [hunk 3]
```diff
@@ -666,12 +667,11 @@ public void verifyDurationTimeout() {
...
 
 	@Test
-	public void verifyNever() {
+	public void verifyNeverWithExpectTimeout() {
 		Flux<String> flux = Flux.never();
 
 		StepVerifier.create(flux)
-		            .expectSubscription()
-		            .thenCancel()
+		            .expectTimeout(Duration.ofMillis(500))
```
Comment (bsideup) [inline reactor-test/src/test/java/reactor/test/StepVerifierTests.java]: use `verifyTimeout` here maybe?

File: reactor-test/src/test/java/reactor/test/StepVerifierTests.java [hunk 4]
```diff
@@ -1225,11 +1249,26 @@ public void longDelayAndNoTermination() {
...
+		            .expectTimeout(Duration.ofHours(10))
 		            .verify();
 	}
 
+	//source: https://stackoverflow.com/questions/58486417/how-to-verify-with-stepverifier-that-provided-mono-did-not-completed
+	@Test
+	public void expectTimeoutSmokeTest() {
+		Mono<String> neverMono = Mono.never();
+		Mono<String> completingMono = Mono.empty();
+		Function<Mono<String>, Duration> f = m -> StepVerifier.create(m)
```
Comment (bsideup) [inline reactor-test/src/test/java/reactor/test/StepVerifierTests.java]: nit: if we use `m -> {}`-style lambda, the `StepVerifier` block would have much shorter indentation

File: reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java [hunk 5]
```diff
@@ -627,6 +629,42 @@ else if (!predicate.test(signal.getSubscription())) {
...
+	@Override
+	public DefaultStepVerifier<T> expectTimeout(Duration duration) {
+		if (sourceSupplier == null) {
+			throw new IllegalStateException("Attempting to call expectTimeout() without a Supplier<Publisher>");
+		}
+		Supplier<? extends Publisher<? extends T>> originalSupplier = sourceSupplier;
+		this.sourceSupplier = () -> {
+			Publisher<? extends T> p = originalSupplier.get();
+
+			if (p instanceof Flux) {
```
[the remark this answers is not in the document]
Comment (simonbasle) [reply reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java]: yeah actually that probably works

File: reactor-test/src/main/java/reactor/test/StepVerifier.java (hunk 2 above)
Comment (simonbasle) [reply reactor-test/src/main/java/reactor/test/StepVerifier.java]: no it is not chainable, this is intended with the same usage pattern as `expectError`.

File: reactor-test/src/test/java/reactor/test/StepVerifierTests.java (hunk 3 above)
Comment (simonbasle) [reply reactor-test/src/test/java/reactor/test/StepVerifierTests.java]: in order to cover the method?

File: reactor-test/src/test/java/reactor/test/StepVerifierTests.java (hunk 4 above)
Comment (simonbasle) [reply reactor-test/src/test/java/reactor/test/StepVerifierTests.java]: I'll rewrote a bit to avoid the `Function` altogether, doesn't bring much in terms of readability

File: reactor-test/src/test/java/reactor/test/StepVerifierTests.java (hunk 3 above)
Comment (simonbasle) [reply reactor-test/src/test/java/reactor/test/StepVerifierTests.java]: adding a test below `expectTimeoutSmokeTest` to check the `verifyTimeout` method
