### PR TITLE
fix #1995 Let exception handler deal with errors in Mono.subscribe

### LINKED ISSUE #1995: Mono should handle subscriber (Consumer) exceptions with provided exception handler
Exceptions thrown by subscriber (**Consumer**) are propagated to error handler defined in **Flux.subscribe**, yet they are re-thrown with **onErrorDropped** once we use **Mono**. This causes inconsistent behavior when using **Flux** and **Mono** respectively.
Moreover, if we extend **BaseSubscriber** and pass it to Mono.subscribe then exceptions are handled as expected.

## Expected Behavior
Error handler in Mono.subscribe should handle exceptions thrown by subscriber.
## Actual Behavior
Test cases attached. All tests should pass as semantically they are identical.

## Steps to Reproduce
```java
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

public class SubscriberTest {
    private static Logger LOG = LoggerFactory.getLogger(SubscriberTest.class);

    @Test
    public void monoHandlingSubscriberError() {
        Mono
                .just("test")
                .subscribe(x -> {
                    throw new IllegalStateException();
                }, e -> LOG.error("Handler", e));
    }

    @Test
    public void fluxHandlingSubscriberError() {
        Flux
                .just("test")
                .subscribe(x -> {
                    throw new IllegalStateException();
                }, e -> LOG.error("Handler", e));
    }

    @Test
    public void monoHandlingSubscriberErrorWhenBaseSubscriber() {
        Mono
            .just("test")
            .subscribe(new BaseSubscriber<String>() {
                @Override
                protected void hookOnNext(String value) {
                    throw new IllegalStateException();
                }

                @Override
                protected void hookOnError(Throwable e) {
                    LOG.error("Handler", e);
                }
            });
}
} 
```

## Your Environment
* Reactor version(s) used: 3.3.1.RELEASE
* JVM version (`javar -version`): 1.8.0_202-release-1483-b58 amd64
* OS and version (eg `uname -a`): Windows Version 6.1 (Build 7601: SP1)

### PR DESCRIPTION
**Pull request by aneveu**
When an error handler is provided to `Mono.subscribe()`, let it handle the error instead of dropping threw `Operators.onErrorDropped`

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/LambdaMonoSubscriber.java [hunk 1]
```diff
@@ -171,8 +171,7 @@ public final void onNext(T x) {
 				consumer.accept(x);
 			}
 			catch (Throwable t) {
-				Operators.onErrorDropped(t, this.initialContext);
-				return;
+				doError(t);
```
Comment (simonbasle) [inline reactor-core/src/main/java/reactor/core/publisher/LambdaMonoSubscriber.java:174]: this looks pretty much aligned with what is done in `LambdaSubscriber#onNext`, taking into account the fact that for `Mono` it already cancels the subscription (and calls `completeConsumer` on top of that). that said, maybe the only thing missing vs the flux version is `Exceptions.throwIfFatal(t)`

File: reactor-core/src/test/java/reactor/core/publisher/LambdaMonoSubscriberTest.java [hunk 2]
```diff
@@ -153,7 +153,7 @@ public void noSubscriptionConsumerTriggersRequestOfMax() {
 	}
 
 	@Test
-	public void onNextConsumerExceptionBubblesUpDoesntTriggerCancellation() {
+	public void onNextConsumerExceptionHandledByErrorHandler() {
```
Comment (simonbasle) [inline reactor-core/src/test/java/reactor/core/publisher/LambdaMonoSubscriberTest.java:156]: I would keep at least one additional test where the `errorHolder::set` is omitted, to demonstrate that if there is no error consumer, the exception in nextConsumer bubbles up wrapped in an `ErrorCallbackNotImplemented` exception.

File: reactor-core/src/test/java/reactor/core/publisher/LambdaMonoSubscriberTest.java [hunk 3]
```diff
@@ -165,18 +165,38 @@ public void onNextConsumerExceptionBubblesUpDoesntTriggerCancellation() {
...
+		tested.onNext("foo");
+
+		assertThat(errorHolder.get()).as("onError").isInstanceOf(IllegalArgumentException.class);
+		assertThat(testSubscription.isCancelled).as("subscription isCancelled").isTrue();
+	}
+
+
+	@Test
+	public void onNextConsumerBubblesUpErrorCallbackNotImplemented() {
+		AtomicReference<Throwable> errorHolder = new AtomicReference<>(null);
```
Comment (simonbasle) [inline reactor-core/src/test/java/reactor/core/publisher/LambdaMonoSubscriberTest.java:178]: the `errorHolder` is unused in this test

File: reactor-core/src/test/java/reactor/core/publisher/LambdaMonoSubscriberTest.java [hunk 4]
```diff
@@ -165,18 +165,38 @@ public void onNextConsumerExceptionBubblesUpDoesntTriggerCancellation() {
...
+		//the error is expected to be thrown as there is no error handler
 		try {
 			tested.onNext("foo");
-			fail("Expected a bubbling Exception");
-		} catch (RuntimeException e) {
-			assertThat(e).matches(Exceptions::isBubbling, "Expected a bubbling Exception")
-			             .hasCauseInstanceOf(IllegalArgumentException.class);
+			fail("Expected IllegalArgumentException to be thrown");
+		}
+		catch (UnsupportedOperationException e) {
```
Comment (simonbasle) [inline reactor-core/src/test/java/reactor/core/publisher/LambdaMonoSubscriberTest.java:194]: mmh `UnsupportedOperatorException` ?? 🤔

Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/LambdaMonoSubscriberTest.java:194]: also you could use assertj `assertThatIllegalArgumentException().isThrownBy(() -> tested.onNext("foo"))`

File: reactor-core/src/test/java/reactor/core/publisher/LambdaMonoSubscriberTest.java [hunk 5]
```diff
@@ -165,18 +166,27 @@ public void onNextConsumerExceptionBubblesUpDoesntTriggerCancellation() {
...
+				value -> { throw new IllegalArgumentException(); },
+				null,
+				() -> {},
+				null);
+
+		TestSubscription testSubscription = new TestSubscription();
+		tested.onSubscribe(testSubscription);
+
+		//the error is expected to be thrown as there is no error handler
+		assertThatIllegalArgumentException().isThrownBy(() -> tested.onNext("foo"));
```
Comment (simonbasle) [inline reactor-core/src/test/java/reactor/core/publisher/LambdaMonoSubscriberTest.java:188]: eh sorry for the back and forth. now the test fails because obviously no error handler == `ErrorCallbackNotImplemented`. So the assertion should A) check that the exception `satisfies` the `Exceptions.isErrorCallbackNotImplemented` `Predicate` and B) that its cause is the `IllegalArgumentException`.

the starting point of the assertion should thus be the more generic `assertThatExceptionOfType(RuntimeException.class).isThrownBy(() -> ...`.

Comment (aneveu) [reply reactor-core/src/test/java/reactor/core/publisher/LambdaMonoSubscriberTest.java:188]: My bad, I didnt' know how I missed it when re-running the test 🙇‍♀️
