### PR TITLE
fix #1666 Use queue.size() for onBackpressureBuffer maxSize evaluation

### LINKED ISSUE #1666: onBackpressureBuffer(maxSize) uses rounded up maxSize
### Expected behavior
`onBackpressureBuffer(3, System.err::println)` should emit 1, buffer 3 next unrequested elements, print out the 5th element and cancel the source.

`onBackpressureBuffer(9, System.err::println)` should emit 1, buffer next 9 unrequested elements, print out the 11th and cancel the source.

### Actual behavior
First version buffers up to 8 elements, prints out `10`. Second version buffers up to 16 elements, prints out `18`.

### Steps to reproduce
```java
	@Test
	public void gh1666_bufferThree() {
		AtomicInteger overflow = new AtomicInteger();
		StepVerifier.create(Flux.range(1, 100)
		                        .hide()
		                        .onBackpressureBuffer(3, overflow::set)
				, 0)
		            .expectSubscription()
		            .thenRequest(1)
		            .expectNext(1)
		            .thenAwait()
		            .thenCancel()
		            .verify();

		assertThat(overflow).as("overflow value").hasValue(5);
	}

	@Test
	public void gh1666_bufferNine() {
		AtomicInteger overflow = new AtomicInteger();
		StepVerifier.create(Flux.range(1, 100)
		                        .hide()
		                        .onBackpressureBuffer(9, overflow::set)
				, 0)
		            .expectSubscription()
		            .thenRequest(1)
		            .expectNext(1)
		            .thenAwait()
		            .thenCancel()
		            .verify();

		assertThat(overflow).as("overflow value").hasValue(11);
	}
```

### Reactor Core version
3.2.8.RELEASE

### PR DESCRIPTION
**Pull request by simonbasle**
The queue.offer() can be unreliable, mainly due to Spsc*Queue rounding the
requested capacity up to the nearest power of two, as well as 
Queues.get(capacity) rounding up capacity to a minimum of 8...

This commit keeps track of the exact buffer size and compares it to the 
queue size() when in bounded mode.

The documentation has been improved to reflect this, as well as the marble
diagram of both variants with a bufferSize and no strategy (the strategy
one being a different implementation that is not impacted).

Tests have been added, and some tests that didn't cover 
FluxOnBackpressureBuffer have been moved to the more correct 
FluxOnBackpressureStrategyTest case.

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/FluxOnBackpressureBuffer.java [hunk 1]
```diff
@@ -148,10 +156,8 @@ public void onNext(T t) {
 				Operators.onNextDropped(t, ctx);
 				return;
 			}
-			if (!queue.offer(t)) {
-				Throwable ex =
-						Operators.onOperatorError(s, Exceptions.failWithOverflow(), t,
-								ctx);
+			if (queue.size() >= capacityOrSkip || !queue.offer(t)) {
```
Comment (smaldini) [inline reactor-core/src/main/java/reactor/core/publisher/FluxOnBackpressureBuffer.java]: Maybe could be optimized a bit, like checking the size ONLY if the capacityOrSkip is != Integer MAX.

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxOnBackpressureBuffer.java]: good point, fixed. also added `scan(CAPACITY)` support
