### PR TITLE
fix #2008 Add onErrorContinue support to FluxFlattenIterable

### LINKED ISSUE #2008: The Flux.flatMapIterable operator does not honor onErrorContinue
## Motivation
Opposed to several other operators such as `map` and `flatMap`, the `Flux.flatMapIterable` does not honor `onErrorContinue`. Meaning if an exception is thrown inside the `flatMapIterable`, the Flux just completes with the error.
It would be nice if `flatMapIterable` has the same behaviour as `flatMap`.

## Desired solution
Correctly have exceptions / null values handled when `onErrorContinue` is used after `flatMapIterable`.

## Considered alternatives
There are no real alternatives. The Flux would need to be re-created and subscribed again. In our situation, that is not really an option.

## Example test case
The following test will currently fail, to underline the current behaviour:

```
    @Test
	public void errorModeContinueInternalError() {
	    Flux<Integer> test = Flux
			    .just(1, 2)
			    .hide()
			    .flatMapIterable(f -> {
            if (f == 1) {
              throw new IllegalStateException("boom");
            }
            return Arrays.asList(f);
			    })
			    .onErrorContinue(OnNextFailureStrategyTest::drop);

	    StepVerifier.create(test)
			    .expectNoFusionSupport()
			    .expectNext(2)
			    .expectComplete()
			    .verifyThenAssertThat()
			    .hasDropped(1)
			    .hasDroppedErrors(1);
    }
```

### PR DESCRIPTION
**Pull request by mdonkers**
As opposed to many other operators, the FluxFlattenIterable does not
support `onErrorContinue` handling.

Attempted to add that support in this PR, together with a test verifying
the behaviour.

This would fix issue https://github.com/reactor/reactor-core/issues/2008

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mdonkers Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2009)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2009) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by dfeist** [comment]
@mdonkers  You should add the `@reactor.errorMode` annotation to the relevant methods in `Flux` too..

**Comment by pivotal-issuemaster** [comment]
@mdonkers Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2009)!

**Comment by mdonkers** [comment]
> @mdonkers You should add the `@reactor.errorMode` annotation to the relevant methods in `Flux` too (two I believe)

Thanks, I had not realized that. Added them now.

**Comment by mdonkers** [comment]
One question from my side:
I'm not sure what should happen here: https://github.com/reactor/reactor-core/pull/2009/files#diff-f4c0ba942565d0ba860414a460f6a1c1L99-L104

That seems to me a different use-case, as the `iterable`is passed on to `FluxIterable`. I'm not sure if that needs to be handled and in which way? As `FluxIterable` will throw an Error then the `iterable` contains a `null` element.

**Comment by simonbasle** [comment]
> One question from my side:
> I'm not sure what should happen here: [reactor/reactor-core/pull/2009/files#diff-f4c0ba942565d0ba860414a460f6a1c1L99-L104](https://github.com/reactor/reactor-core/pull/2009/files#diff-f4c0ba942565d0ba860414a460f6a1c1L99-L104)
> 
> That seems to me a different use-case, as the `iterable`is passed on to `FluxIterable`. I'm not sure if that needs to be handled and in which way? As `FluxIterable` will throw an Error then the `iterable` contains a `null` element.

At this point there would not be anything to recover to, so this doesn't seem like it can be covered by _continue_.

**Comment by mdonkers** [comment]
@simonbasle Thanks for those suggestions, they uncovered a few issues / unhandled scenarios.
I've provided the necessary fixes.
As I'm not yet too familiar with the Reactor internals, I hope everything is covered now. Please suggest if I might miss more scenarios :-)

File: reactor-core/src/test/java/reactor/core/publisher/FluxFlattenIterableTest.java [hunk 1]
```diff
@@ -398,7 +397,7 @@ public void syncDrainWithPollFailure() {
     }
 
 	@Test
-	public void errorModeContinueNullPublisher() {
+	public void errorModeContinueNullPublisherAsync() {
```
Comment (simonbasle) [inline reactor-core/src/test/java/reactor/core/publisher/FluxFlattenIterableTest.java]: nit: maybe replace the test name suffixes of `Async` with `NotFused` and `Sync` with `Fused` ?

Comment (mdonkers) [reply reactor-core/src/test/java/reactor/core/publisher/FluxFlattenIterableTest.java]: Sure. I thought the Async / sync was logical because of the drain method that would get called.
Will change.
