### PR TITLE
SourceException wrapper for main stream errors delivered to windows

### LINKED ISSUE #2041: wrap exceptions sent to windows (rather than main sequence)  in a SourceException
The following results in `BubblingException` containing the `IllegalStateException`:

```java
Mono.just("a").concatWith(Mono.error(new IllegalStateException("e")))
		.windowUntil(s -> s.equals("b"))
		.concatMap(Flux::collectList)
		.blockLast();
```

By comparison the following results in just the `IllegalStateException` as expected:

```java
Mono.just("a").concatWith(Mono.error(new IllegalStateException("e")))
		.bufferUntil(s -> s.equals("b"))
		.blockLast();
```

### PR DESCRIPTION
**Pull request by chemicL**
In case of window operators, it might be beneficial to distinguish
between errors coming from the window chain of operators and errors
coming from the source sequence. `Exceptions.SourceException` has
been added and `Throwable`s coming from either the source
sequence, or, in case of window operators that accept `Publisher`s
to drive windowing, their errors also are wrapped.

This is a behavior change and if existing logic relied on the
properties of the delivered `Throwable` it will require reaching for
the `Throwable#getCause()` in case of `Exceptions.SourceException`.

An additional behavior change is in case of `FluxWindowWhen`,
which did not deliver source errors to the windows, despite
seemingly being intended by the implementation.

Resolves #2041

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/Exceptions.java [hunk 1]
```diff
@@ -725,6 +737,23 @@ public synchronized Throwable fillInStackTrace() {
...
 
+	/**
+	 * A {@link Throwable} that wraps the actual {@code cause} delivered via
+	 * {@link org.reactivestreams.Subscriber#onError(Throwable)} in case of
+	 * {@link org.reactivestreams.Publisher}s that themselves emit items of type
+	 * {@link org.reactivestreams.Publisher}. This wrapper is used to distinguish
+	 * {@code error}s delivered by the upstream sequence from the ones that happen via
+	 * the inner sequence processing chain.
+	 */
+	public static class SourceException extends ReactiveException {
```
Comment (chemicL) [inline reactor-core/src/main/java/reactor/core/Exceptions.java:748]: Intentionally public to allow distinguishing from regular window errors in user code.

Comment (chemicL) [inline reactor-core/src/main/java/reactor/core/Exceptions.java:748]: Intentionally public to allow distinguishing from regular window errors in user code.

File: reactor-core/src/main/java/reactor/core/publisher/FluxWindowWhen.java [hunk 2]
```diff
@@ -235,15 +237,16 @@ void drainLoop() {
 						dispose();
 						Throwable e = error;
 						if (e != null) {
-							actual.onError(e);
```
Comment (chemicL) [inline reactor-core/src/main/java/reactor/core/publisher/FluxWindowWhen.java:238]: Instructions here and in in `onComplete()` got swapped. Previously, the next line(s) would have no effect, as the call to `actual` cancelled the window subscriptions, causing the signals to be lost.

File: reactor-core/src/test/java/reactor/core/publisher/FluxWindowTimeoutTest.java [hunk 3]
```diff
@@ -469,4 +470,32 @@ public void scanMainSubscriber() {
...
+		            // failure observed by window
+		            .expectNextMatches(signalSourceErrorMessage("expected failure"))
+		            // failure observed by main Flux
+		            .expectErrorMessage("expected failure")
+		            .verify();
+
+		source.assertNoSubscribers();
+	}
+
+	private <T> Predicate<? super Signal<T>> signalSourceErrorMessage(String expectedMessage) {
```
Comment (chemicL) [inline reactor-core/src/test/java/reactor/core/publisher/FluxWindowTimeoutTest.java:495]: I duplicated this method as some window tests don't share a common base – namely `FluxWindowBoundaryTest`, `FluxWindowTimeoutTest`, and `FluxWindowWhenTest`. `FluxWindowPredicateTest`, and `FluxWindowTest` on the other hand, do both inherit from `FluxOperatorTest`. Perhaps a more thorough inspection should follow, but I considered it out of scope for this change.

**Review by simonbasle — APPROVED** [review]

**Comment by simonbasle** [comment]
we could maybe mention the wrapping in the javadoc. other than that, looks good to me

**Review by simonbasle — APPROVED** [review]
