### PR TITLE
Fix #2023 by handling "empty `Callable`" case in `Flux#collectList`

### LINKED ISSUE #2023: ReactorDebugAgent messes up with collectList return value
Using `ReactorDebugAgent` changes the behaviour of the return value of `Flux.collectList()`. If I am not using the agent `Flux.empty().collectList()` will return `Mono.just(List.of())`, while if I am using the agent, it will return `Mono.empty()`.

## Expected Behavior
I would expect `Flux.empty().collectList()` to return `Mono.just(List.of())` without mattering if I am using the debug agent or not.

## Actual Behavior
If I am using the debug agent, the return value of that call will be `Mono.empty()`.

## Steps to Reproduce

Without the agent:

```java
  @Test
  void noAgent() {
    var empty = new EmptyFlux();
    var result = empty.value()
        .collectList();

    StepVerifier.create(result)
        .assertNext(res -> assertEquals(0, res.size()))
        .verifyComplete();
  }

  public static class EmptyFlux {
    public Flux<String> value() {
      return Flux.empty();
    }
  }
```

With the agent:

```java
  @Test
  void agent() {
    ReactorDebugAgent.init();
    var empty = new EmptyFlux();
    var result = empty.value()
        .collectList();

    StepVerifier.create(result)
        .verifyComplete();
  }

  public static class EmptyFlux {
    public Flux<String> value() {
      return Flux.empty();
    }
  }
```

Run the tests separately.

## Possible Solution
My knowledge of the library is not good enough to think about the cause and possible solutions :(

## Your Environment
I am using reactor-core, reactor-tools and reactor-test version 3.3.2 and I am executing the tests in JUnit 5.

* Reactor version(s) used: 3.3.2
* Other relevant libraries versions (eg. `netty`, ...): JUnit 5.5.2
* JVM version (`javar -version`): OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
* OS and version (eg `uname -a`): Darwin MBP073.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64 i386

### PR DESCRIPTION
**Pull request by bsideup**
It seems that we were handling `Callable` (but not `Fuseable.ScalarCallable`) incorrectly
and, instead of producing an empty list, were returning an empty `Mono` instead.

The change also simplifies handling of `Fuseable.ScalarCallable`

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/Flux.java [hunk 1]
```diff
@@ -3184,23 +3184,25 @@ public final T blockLast(Duration timeout) {
 				catch (Exception e) {
 					return Mono.error(e);
 				}
-				if (v == null) {
-					return Mono.onAssembly(new MonoSupplier<>(listSupplier()));
-				}
-				return Mono.just(v).map(u -> {
+				return Mono.fromCallable(() -> {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/Flux.java]: @simonbasle I believe a single `fromCallable` is better than `just` + `map` and easier to follow. WDYT?

Comment (simonbasle) [inline reactor-core/src/main/java/reactor/core/publisher/Flux.java]: I would suggest to use the form `onAssembly(new MonoCallable<>(...))` here and below, so that there is no additional step in the backtrace that corresponds to the `fromCallable` call.

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/Flux.java]: yeah that works for me
