### PR TITLE
fix #2014 Cancel discards concatMapIterable/fromIterable's remainder …

### LINKED ISSUE #2014: concatMapIterable could be enhanced to discard iterator remainder
From #1925:
> I can't verify because the step before `bufferUntil` is `concatMapIterable` which produces a collection of allocated items and those don't seem to pass through `doOnDiscard` in case of a downstream error. Could there be an issue with `concatMapIterable`?

Here is a simplified test:

```java
@Test
void concatMapIterableDoOnDiscardTest() {

	Foo foo1 = new Foo();
	Foo foo2 = new Foo();
	Foo foo3 = new Foo();

	Flux<Foo> source = Flux.just(1)
			.concatMapIterable(i -> Arrays.asList(foo1, foo2, foo3))
			.doOnDiscard(Foo.class, Foo::release);

	StepVerifier.create(source)
			.consumeNextWith(foo -> {
				foo.release();
			})
			.thenCancel()
			.verify();

	assertThat(foo1.getRefCount()).isEqualTo(0); // okay
	assertThat(foo2.getRefCount()).isEqualTo(0); // fails
	assertThat(foo3.getRefCount()).isEqualTo(0); // fails
}

static class Foo {

	int refCount = 1;

	public int getRefCount() {
		return this.refCount;
	}

	public void release() {
		this.refCount = 0;
	}
}
```

_Originally posted by @rstoyanchev in https://github.com/reactor/reactor-core/issues/1925#issuecomment-573630082_

### PR DESCRIPTION
**Pull request by simonbasle**
…from iterator

If both an Iterator and a Spliterator can be generated for each of the
processed Iterables, then the Spliterator is used to ensure the Iterable
is SIZED. This allows us to safely assume we can iterate over the
remainder of the iterator when cancelling, in order to discard its
elements that weren't emitted.

Not doing this check would likely cause trouble with infinite discarding
loops in the case of infinite Iterables (which is technically possible).

For Streams, since both the iterator() and spliterator() methods are
terminating the Stream we only generate the Spliterator. We use it to
check SIZED and then wrap it in an Iterator adapter for iteration (which
is what BaseStream does by default).

Note that using a Spliterator to drive the internal iteration doesn't
work that well, since the default Iterable#spliterator isn't SIZED and
its estimatedSize() method doesn't behave like hasNext().
Iterator#hasNext is far better suited for looking ahead of the emitted
element to trigger onComplete immediately after the last onNext.

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java [hunk 1]
```diff
@@ -89,11 +91,11 @@ public void subscribe(CoreSubscriber<? super R> actual) {
 			}
 
 			Iterator<? extends R> it;
-
+			boolean knownToBeFinite;
 			try {
 				Iterable<? extends R> iter = mapper.apply(v);
-
 				it = iter.iterator();
+				knownToBeFinite = iter.spliterator().getExactSizeIfKnown() != -1;
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java]: magical constant used in a few places, let's extract :)

File: reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java [hunk 2]
```diff
@@ -367,15 +378,21 @@ void drainAsync() {
 					while (e != r) {
 						if (cancelled) {
 							current = null;
-							Operators.onDiscardQueueWithClear(q, ctx, null);
+							currentKnownToBeFinite = false; //reset explicitly
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java]: this block seems to be repeated 9 times, wdyt about extracting it into a method?

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java]: Maybe not the whole block, but the `current = null; currentKnownToBeFinite = false;` part: it is very important these two are reset together, and the code is short enough that it can be inlined. I'll extract that instead (19 duplicates).

File: reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java [hunk 3]
```diff
@@ -89,11 +90,11 @@ public void subscribe(CoreSubscriber<? super R> actual) {
 			}
 
 			Iterator<? extends R> it;
-
+			boolean knownToBeFinite;
 			try {
 				Iterable<? extends R> iter = mapper.apply(v);
-
 				it = iter.iterator();
+				knownToBeFinite = iter.spliterator().getExactSizeIfKnown() != FluxIterable.SPLITERATOR_UNSIZED;
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java]: FYI I was looking at the sources of `java.util.Spliterator` and trying to find the `-1` constant there.

`getExactSizeIfKnown()` is defined as:
```java
    default long getExactSizeIfKnown() {
        return (characteristics() & SIZED) == 0 ? -1L : estimateSize();
    }
```

which means that we could also do `(iter.spliterator().characteristics() & Spliterator.SIZED) == 0` instead of calling `getExactSizeIfKnown()` which also matches what we're actually checking. WDYT?

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java]: yeah that is still expressive enough and less computational-intensive

**Comment by simonbasle** [comment]
> The following block seems to be duplicated many times:
> 
> ```java
> Context context = actual.currentContext();
> Operators.onDiscardQueueWithClear(queue, context, null);
> Operators.onDiscardMultiple(it, itFinite, context);
> ```
> 
> WDYT about extracting it as well?

Not as obvious an improvement as the methods can make sense separately.

**Comment by bsideup** [comment]
@simonbasle we don't need to _remove_ them, but "group". It feels weird to always call two "onDiscard" methods, feels like it should be a single method

File: reactor-core/src/main/java/reactor/core/publisher/FluxIterable.java [hunk 4]
```diff
@@ -19,16 +19,20 @@
 import java.util.Collection;
```
Comment (rstoyanchev) [inline reactor-core/src/main/java/reactor/core/publisher/FluxIterable.java]: I noticed `onCloseWithDropError` in both subscriptions don't call `onDiscardMultiple`. Perhaps there is a reason, but it looks like the iterator may have more items (e.g. in `poll()` if an item is `null`).

File: reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java [hunk 5]
```diff
@@ -658,6 +697,7 @@ public boolean isEmpty() {
 		@Nullable
 		public R poll() {
 			Iterator<? extends R> it = current;
+			boolean itFinite = currentKnownToBeFinite;
```
Comment (rstoyanchev) [inline reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java]: Isn't this initialization redundant? It will be updated before its used.

File: reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java [hunk 6]
```diff
@@ -679,16 +721,18 @@ public R poll() {
 						continue;
 					}
 					current = it;
+					currentKnownToBeFinite = itFinite;
 				}
 				else if (!it.hasNext()) {
 					it = null;
+					itFinite = false;
```
Comment (rstoyanchev) [inline reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java]: Likewise setting this here seems redundant since `itFinite` will be set again before its used.

File: reactor-core/src/main/java/reactor/core/publisher/FluxIterable.java (hunk 4 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxIterable.java]: a `QueueSubscription` must only return `null` to `poll()` if the subscription is empty/done. some cases of calling `onCloseWithDropErrors` are not suitable for attempting a drain of the iterator, for instance if `hasNext()` throws... Should we attempt to drain in the case the iterator returns a `null` value though? I'd argue this is an illegal state so the user should find the root cause of the `null` first and foremost, after which the discarding will be correctly done.

File: reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java (hunk 5 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java]: indeed, fixed

**Comment by simonbasle** [comment]
> One thing I noticed while reviewing is that `Operators#onDiscard*` methods put `try-catch` around the entire loop. So if the discard action throws an error for one item, the rest will not be discarded. Should those keep going to try to discard as many as possible?

Indeed, that is another avenue of improvement. I'll introduce a separate commit, so I'll clean up the history of this PR to allow for a rebase and merge.

**Comment by simonbasle** [comment]
@bsideup @rstoyanchev can you review this? should be the final state in terms of code, and once approved I'll locally squash the commits to get 2 separates commits (one that addresses the cancel, the other that makes doOnDiscard more resilient).

**Comment by simonbasle** [comment]
Rebased on top of 3.2.x and cleaned up the commits, will merge as soon as tests pass.
