### PR TITLE
fix #2557 protect against sparse array on subscribe

### LINKED ISSUE #2557: ArrayIndexOutOfBoundsException is thrown from Flux#firstWithValue(Iterable<? extends Publisher<? extends I>> sources)
Flux#firstWithValue(Iterable<? extends Publisher<? extends I>> sources) throws ArrayIndexOutOfBoundsException.

## Expected Behavior

Behaviour should be the same as for the method which accepts vararg Flux#firstWithValue(Publisher<? extends I> first, Publisher<? extends I>... others)

## Actual Behavior

ArrayIndexOutOfBoundsException is thrown

## Steps to Reproduce

```java
@Test
void reproCase() {
    Flux.firstWithValue(Arrays.asList(Mono.just(1), Mono.empty())).blockFirst();
}
```

## Your Environment

* Reactor version(s) used: 3.4.2
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): 11.0.3
* OS and version (eg `uname -a`): OSX

### PR DESCRIPTION
**Pull request by ericbottard**

### CODE REVIEW

File: reactor-core/src/test/java/reactor/core/publisher/FluxFirstWithValueTest.java [hunk 1]
```diff
@@ -249,6 +249,12 @@ void combineMoreThanOneAdditionalSource() {
 						.doesNotContainNull());
 	}
 
+	// See https://github.com/reactor/reactor-core/issues/2557
+	@Test
+	void protectAgainstSparseArray() {
+		Flux.firstWithValue(Arrays.asList(Mono.just(1), Mono.empty())).blockFirst();
```
Comment (simonbasle) [inline reactor-core/src/test/java/reactor/core/publisher/FluxFirstWithValueTest.java:255]: maybe be more explicit, like using either a `StepVerifier` or an AssertJ `assertThatCode.doesNotThrowAnyException(() -> {...})` ?

File: reactor-core/src/test/java/reactor/core/publisher/MonoFirstWithValueTest.java [hunk 2]
```diff
@@ -221,6 +221,12 @@ void iterableOneIsNullSource() {
 				.assertError(NullPointerException.class);
 	}
 
+	// See https://github.com/reactor/reactor-core/issues/2557
+	@Test
+	void protectAgainstSparseArray() {
+		Mono.firstWithValue(Arrays.asList(Mono.just(1), Mono.empty())).block();
```
Comment (simonbasle) [inline reactor-core/src/test/java/reactor/core/publisher/MonoFirstWithValueTest.java:227]: same, make an explicit assertion in the test here too

**Review by simonbasle — CHANGES_REQUESTED** [review]

**Review by simonbasle — APPROVED** [review]
