### PR TITLE
Make sure ElasticScheduler.CachedService gets disposed

### LINKED ISSUE #1722: ElasticScheduler leaks thread when task is disposed immediately
### Expected behavior

The following code should always return the executor to the cache.

```java
Schedulers.elastic()
    .schedule(() -> System.out.println("yeah"))
    .dispose();
```

### Actual behavior

Sometimes the executor is not returned to the cache. It causes threads to leak.

### Steps to reproduce

```java
public class ElasticSchedulerLeakTest {
    public static void main(String[] args) throws Exception {
        while (true) {
            Schedulers.elastic()
                    .schedule(() -> System.out.println("yeah"))
                    .dispose();

            Thread.sleep(100);

            int cacheSize = ((Scannable) Schedulers.elastic()).scan(Scannable.Attr.BUFFERED);
            // should print 1 if executor is returned to cache, but sometimes 0 is printed
            System.out.println(cacheSize);
        }
    }
}
```

### Reactor Core version

3.2.8.RELEASE

It seems to happen on other versions too.

----

When `schedule` is called, a `CachedService` is acquired first:

https://github.com/reactor/reactor-core/blob/a0b332b99b25f98461536f01cc18e6b30319301a/reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java#L159

`CachedService` is disposed after the task is run:

https://github.com/reactor/reactor-core/blob/a0b332b99b25f98461536f01cc18e6b30319301a/reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java#L300

However, if the task is not run (because of immediate disposal), `CachedService` is not disposed.

### PR DESCRIPTION
**Pull request by dittos**
Fixes #1722.

When `schedule` is called, a `CachedService` is acquired first:

https://github.com/reactor/reactor-core/blob/a0b332b99b25f98461536f01cc18e6b30319301a/reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java#L159

`CachedService` is disposed after the task is run:

https://github.com/reactor/reactor-core/blob/a0b332b99b25f98461536f01cc18e6b30319301a/reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java#L300

However, if the task is not run (because of immediate disposal), `CachedService` is not disposed.

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java [hunk 1]
```diff
@@ -300,6 +308,13 @@ public void run() {
 				cached.dispose();
 			}
 		}
+
+		@Override
+		public void dispose() {
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java]: perhaps we should do it in `SchedulerTask`? `directSchedule` returns it, and we can handle the disposed state there

/cc @simonbasle

Comment (dittos) [reply reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java]: I'll try. I put it here because `SchedulerTask` seemed to have a bit more complex state.

Comment (dittos) [reply reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java]: `SchedulerTask` is also used in the other schedulers that do not manage executor pool. I don't see much benefit adding a reference/handling of `Disposable` in `SchedulerTask` just for the `ElasticScheduler`. Maybe we can copy `SchedulerTask` into `ElasticScheduler` and specialize for it.

Comment (bsideup) [reply reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java]: `Disposables.composite` allocates an object and it is a part of the hot path, I thought about avoiding it

**Comment by simonbasle** [comment]
hey @dittos ! Looks like tests are not passing with your last iteration. What is the status on this? Will you have time to further work on this PR?

File: reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java [hunk 2]
```diff
@@ -276,4 +280,62 @@ else if (i == fastCount - 1) {
...
+			AtomicBoolean stop = new AtomicBoolean(false);
+			Disposable d = s.schedule(() -> {
+				// simulate uninterruptible computation
+				for (;;) {
+					if (stop.get()) {
+						break;
+					}
+				}
+			});
+			Thread.sleep(100);
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java]: since it is not time-sensitive, please add a `CountDownLatch` to detect the start of the submitted `Runnable` instead of waiting for a fixed amount of time

File: reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java [hunk 3]
```diff
@@ -276,4 +280,62 @@ else if (i == fastCount - 1) {
 			LOGGER.info("{} threads active post shutdown", Thread.activeCount() - otherThreads);
 		}
 	}
+
+	@Test
+	public void doesntRecycleWhileRunningAfterDisposed() throws Exception {
+		Scheduler s = Schedulers.newElastic("test-recycle");
+		((ElasticScheduler)s).evictor.shutdownNow();
+
+		try{
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java]:
```suggestion
		try {
```

File: reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java [hunk 4]
```diff
@@ -276,4 +280,62 @@ else if (i == fastCount - 1) {
...
+			assertThat(((ElasticScheduler)s).cache).isEmpty();
+
+			stop.set(true);
+
+			Thread.sleep(100);
+			assertThat(((ElasticScheduler)s).cache.size()).isEqualTo(1);
+		}
+		finally {
+			s.dispose();
+			s.dispose();//noop
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java]: why do we need a noop call here?

File: reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java [hunk 5]
```diff
@@ -276,4 +280,62 @@ else if (i == fastCount - 1) {
...
+		}
+	}
+
+	@Test
+	public void recycleOnce() throws Exception {
+		Scheduler s = Schedulers.newElastic("test-recycle");
+		((ElasticScheduler)s).evictor.shutdownNow();
+
+		try{
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java]:
```suggestion
		try {
```

File: reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java [hunk 6]
```diff
@@ -276,4 +280,62 @@ else if (i == fastCount - 1) {
...
+			Disposable d = s.schedule(() -> {
+				try {
+					Thread.sleep(10000);
+				} catch (InterruptedException e) {
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java]:
```suggestion
				}
				catch (InterruptedException e) {
```

File: reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java [hunk 7]
```diff
@@ -68,21 +69,24 @@ public void eviction() throws Exception {
...
-				}
-				catch (InterruptedException e) {
-					Thread.currentThread().interrupt();
-				}
-			});
+			for (int i = 0; i < 100; i++) {
+				Disposable d = s.schedule(() -> {
+					try {
+						Thread.sleep(10000);
+					} catch (InterruptedException e) {
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java]:
```suggestion
					}
					catch (InterruptedException e) {
```

File: reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java [hunk 8]
```diff
@@ -276,4 +280,62 @@ else if (i == fastCount - 1) {
...
+			Disposable d = s.schedule(() -> {
+				try {
+					Thread.sleep(10000);
+				} catch (InterruptedException e) {
+					Thread.currentThread().interrupt();
+				}
+			});
+
+			d.dispose();
+			d.dispose();
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java]: could you please explain why we need two `dispose` calls here?

File: reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java [hunk 9]
```diff
@@ -276,4 +281,64 @@ else if (i == fastCount - 1) {
...
+			Disposable d = s.schedule(() -> {
+				started.countDown();
+				// simulate uninterruptible computation
+				for (;;) {
+					if (stop.get()) {
+						break;
+					}
+				}
+			});
+			started.await();
```
Comment (simonbasle) [inline reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java]: maybe prevent infinite test (in case of future regression) by capping the `await` and checking the returned boolean?

Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java]: @dittos apart from this minor change to the test, this PR should be good to go

```suggestion
			assertThat(started.await(10, TimeUnit.SECONDS)).as("latch timeout").isTrue();
```
