### PR TITLE
ensures that proper index is used during onNext check

### LINKED ISSUE #3525: flaky test `FluxBufferTimeoutTest > flushShouldNotRaceWithNext()`
flaky test. seeing it constantly

```
FluxBufferTimeoutTest > flushShouldNotRaceWithNext() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: 500
     but was: 499
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at reactor.core.publisher.FluxBufferTimeoutTest.flushShouldNotRaceWithNext(FluxBufferTimeoutTest.java:337)
```

### PR DESCRIPTION
**Pull request by OlegDokuka**
closes #3525

### CODE REVIEW

File: reactor-core/src/test/java/reactor/core/publisher/FluxBufferTimeoutTest.java [hunk 1]
```diff
@@ -310,31 +312,54 @@ public void scanSubscriberCancelled() {
 
 	@Test
 	public void flushShouldNotRaceWithNext() {
-		Set<Integer> seen = new HashSet<>();
-		Consumer<List<Integer>> consumer = integers -> {
-			for (Integer i : integers) {
-				if (!seen.add(i)) {
-					throw new IllegalStateException("Duplicate! " + i);
+		for (int i = 0; i < 100; i++) {
```
Comment (chemicL) [inline reactor-core/src/test/java/reactor/core/publisher/FluxBufferTimeoutTest.java:315]: The changes in the test look like were introduced because the race testing utils are not trusted. At the same time, changing a test at the same time while introducing a change to the production code is suspicious - are these the final changes? Do we want to repeat the test 100 times?

**Review by chemicL — CHANGES_REQUESTED** [review]

File: reactor-core/src/test/java/reactor/core/publisher/FluxBufferTimeoutTest.java (hunk 1 above)
Comment (OlegDokuka) [reply reactor-core/src/test/java/reactor/core/publisher/FluxBufferTimeoutTest.java:315]: it is probability related thing. Just running race test once gives no guarantee of event to occur. JCStress are doing the same underneath (looping many times until a possible event is being triggered). Here, we do that manually. 

Ideally that should be moved to JCStress suit which does that in more sophisticated way + adds different VM configurations in addition which may create higher probability to a specific event occurrence.

Comment (OlegDokuka) [reply reactor-core/src/test/java/reactor/core/publisher/FluxBufferTimeoutTest.java:315]: There should be a separate effort moving all such tests to JCStress. For now just wanna eliminate the bug

**Review by chemicL — APPROVED** [review]
