### PR TITLE
fix #1938 Remove overeager toString calls in FluxIndexFuseable

### LINKED ISSUE #1938: FluxIndexFuseable calls toString() on every element
## Steps to Reproduce

`toString()` should not be called on element when using `index` operator.

To demonstrate the behavior I defined a class that throws on `toString()`.

```java
import reactor.core.publisher.Flux;

public class FluxIndexTest {
	public static void main(String[] args) {
		Flux.just(new ThrowsOnToString())
				.index()
				.blockFirst();
	}

	static class ThrowsOnToString {
		@Override
		public String toString() {
			throw new RuntimeException("should not call");
		}
	}
}
```

Running the code throws because `toString()` is called unnecessarily.

```
Exception in thread "main" java.lang.RuntimeException: should not call
	at FluxIndexTest$ThrowsOnToString.toString(FluxIndexTest.java:14)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at reactor.core.publisher.FluxIndexFuseable$IndexFuseableSubscriber.onNext(FluxIndexFuseable.java:133)
	at reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:99)
	at reactor.core.publisher.FluxIndexFuseable$IndexFuseableSubscriber.request(FluxIndexFuseable.java:174)
	at reactor.core.publisher.BlockingSingleSubscriber.onSubscribe(BlockingSingleSubscriber.java:49)
	at reactor.core.publisher.FluxIndexFuseable$IndexFuseableSubscriber.onSubscribe(FluxIndexFuseable.java:101)
	at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8134)
	at reactor.core.publisher.Flux.blockFirst(Flux.java:2437)
	at FluxIndexTest.main(FluxIndexTest.java:8)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Flux.blockFirst(Flux.java:2438)
		... 1 more
```

Does not throw when no fusion.

```java
		Flux.just(new ThrowsOnToString())
				.flatMap(Flux::just)
				.index()
				.blockFirst();
```

## Possible Solution

Generate error message only when `null` is returned from index mapper. (fixed in #1456 but not on fused version)

https://github.com/reactor/reactor-core/blob/628258f644bdddd095e72d1fc81c5d6ac0e3fa12/reactor-core/src/main/java/reactor/core/publisher/FluxIndexFuseable.java#L111-L113

## Your Environment

* Reactor version(s) used: 3.3.0

### PR DESCRIPTION
**Pull request by dittos**
Fixes #1938

### CODE REVIEW

**Comment by bsideup** [comment]
@dittos nice! Could you please add some tests for it?

**Comment by simonbasle** [comment]
do you think this approach is better than the `NullSafeIndexMapper` in #1456 ? I'm not leaning any particular way, but I'd prefer to align both implementations (which can be done for `FluxIndex` in this PR as well)

File: reactor-core/src/main/java/reactor/core/publisher/FluxIndex.java [hunk 1]
```diff
@@ -274,5 +274,15 @@ public I apply(Long i, T t) {
 			}
 			return typedIndex;
 		}
+
+		static <T, I> BiFunction<? super Long, ? super T, ? extends I> create(
+				BiFunction<? super Long, ? super T, ? extends I> indexMapper) {
+			if (indexMapper == Flux.TUPLE2_BIFUNCTION) {
+				// TUPLE2_BIFUNCTION (Tuples::of) never returns null.
+				// Also helps FluxIndexFuseable to detect the default index mapper.
```
Comment (simonbasle) [inline reactor-core/src/main/java/reactor/core/publisher/FluxIndex.java]: @dittos can you expand on that part? doesn't seem to ever be checked apart from here

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxIndex.java]: maybe add a test that instantiating with that default mapper doesn't override the internal `indexMapper` field?

Comment (dittos) [reply reactor-core/src/main/java/reactor/core/publisher/FluxIndex.java]: `requestFusion` checks for it.

https://github.com/reactor/reactor-core/blob/0328059f370b03c9212ccb53b92197eeb2ed430b/reactor-core/src/main/java/reactor/core/publisher/FluxIndexFuseable.java#L195

There is a test for the default mapper + thread barrier case, so I think the comment is enough (instead of adding test). Maybe need to word it better.

https://github.com/reactor/reactor-core/blob/0328059f370b03c9212ccb53b92197eeb2ed430b/reactor-core/src/test/java/reactor/core/publisher/FluxIndexedFuseableTest.java#L237-L245

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/FluxIndex.java]: ah right it was a pre-existing test :+1:
