### PR TITLE
fix #1830 Catch more specific exceptions and errors 

### LINKED ISSUE #1830: reactor.core.publisher.Traces to catch specific exception and errors
`reactor.core.publisher.Traces` class has code to catch `Throwable`. However, It's good practice to specify more explicit errors and exceptions.

```
try {
        Class<?> clazz = Class.forName(className);
        @SuppressWarnings("unchecked")
        Supplier<Supplier<String>> function = (Supplier) clazz.getDeclaredConstructor()
                                                              .newInstance();
        return Stream.of(function);
}
catch (Throwable e) {
        return Stream.empty();
}
```

## Motivation

it's good practice to specify exceptions and errors that may occur in try clause rather than `Throwable`. https://stackoverflow.com/a/6083271/975074

## Desired solution

Catching more specific exceptions and errors is desirable:

```
try {
        Class<?> clazz = Class.forName(className);
        @SuppressWarnings("unchecked")
        Supplier<Supplier<String>> function = (Supplier) clazz.getDeclaredConstructor()
                                                              .newInstance();
        return Stream.of(function);
}
catch (ClassNotFoundException|NoSuchMethodException|LinkageError e) {
        return Stream.empty();
}
```

## Considered alternatives

None

## Additional context

Our static analysis tool "Linkage Checker" detected reactor.core.publisher.Traces not properly catching LinkageError.

https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/816

### PR DESCRIPTION
**Pull request by gindex**

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/publisher/Traces.java [hunk 1]
```diff
@@ -80,7 +80,7 @@
 						                                                      .newInstance();
 						return Stream.of(function);
 					}
-					catch (Throwable e) {
+					catch (ReflectiveOperationException | LinkageError e) {
```
Comment (simonbasle) [inline reactor-core/src/main/java/reactor/core/publisher/Traces.java]: a brief analysis of constructors shows that other types of exceptions are unlikely, but I'd prefer to add the catch-all clause back at the end still (in case said constructors "evolve")

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/Traces.java]: also can you put up a comment that this catch clause is there to help with static analysis tools that warn about potential `LinkageError` and such?

Comment (gindex) [reply reactor-core/src/main/java/reactor/core/publisher/Traces.java]: Sure 👍

**Comment by suztomo** [comment]
Yes, thank you for accepting suggestion.
