### PR TITLE
fix #1107 Avoid interrupting WorkerTask Future if cancelled race

### LINKED ISSUE #1107: Premature thread interruption when using Mono.just().transform(flux)
See: https://github.com/ReactiveX/RxJava/issues/5711
See: https://github.com/ReactiveX/RxJava/issues/5715

In the following scenario:
```
Scheduler scheduler = Schedulers.fromExecutorService(Executors.newCachedThreadPool());
Flux<Integer> flux = Flux.just(1);
Function<Publisher<Integer>, Publisher<Integer>> addOne = f -> Flux.from(f)
		                                                    .map(i -> i + 1)
		                                                    .publishOn(scheduler);
flux.concatMap(j -> Mono.just(j).transform(addOne)).subscribe(System.out::println);
````

- the Mono.transform, given addOne is not a Mono uses MonoNext to wrap
- MonoNext does s.cancel() before actual.onNext(t);
- WorkerTask future gets cancelled (due to MonoNext s.cancel), and can get cancelled even before reactor.core.scheduler.WorkerTask#setFuture. If this happens thread is interrupted and processing on that thread (e.g. reading of IO) can be cut short

In my case the thread doing the map() is an HTTP selector thread and the `Thread.interrupt()` provoked in `WorkerTask#setFuture` causes the reading of `AbstractInterruptibleChannel` to be cut short with a `ClosedByInterruptException` resulting in an empty response body.

The cancel-before-next in `MonoNext` is necessary but causes a race condition between `reactor.core.scheduler.WorkerTask#dispose` and `sr.setFuture(f)` (in `reactor.core.scheduler.Schedulers#workerSchedule`), where when `dispose()` is called before `setFuture(f)` the thread that is still processing the `onNext()` signal is prematurely interrupted.

### PR DESCRIPTION
**Pull request by simonbasle**
This commit prevents the undesirable interruption of the WorkerTask's
thread when a cancellation happens within the run() method (eg. a
MonoNext is cancelling upon first onNext downstream).

This would previously lead to a race condition between the cancellation
and the setFuture, which would interrupt if called AFTER the dispose.

### CODE REVIEW

File: reactor-core/src/main/java/reactor/core/scheduler/WorkerTask.java [hunk 1]
```diff
@@ -53,7 +66,9 @@
 	static final AtomicReferenceFieldUpdater<WorkerTask, Composite> PARENT =
 			AtomicReferenceFieldUpdater.newUpdater(WorkerTask.class, Composite.class, "parent");
 
-	Thread thread;
+	volatile Thread thread;
```
Comment (smaldini) [inline reactor-core/src/main/java/reactor/core/scheduler/WorkerTask.java]: @akarnokd is there a real need to pass this thread property volatile ?

Comment (akarnokd) [reply reactor-core/src/main/java/reactor/core/scheduler/WorkerTask.java]: A lazySet is enough, that's what's happening with the field updater below.
