### PR TITLE
fix #1393 null can be passed to reduce lambda if cancelled, causing NPE

### LINKED ISSUE #1393: Race condition in reduce with seed cancellation can lead to NPE
### Expected behavior
A reducing `Flux` with a seed value can safely be cancelled.

### Actual behavior
The `BiFunction` can be fed a `null` value in case there is a concurrent `cancel()` along the first `onNext(T)`. This is due to `cancel` nulling out the internal accumulated `value` and `onNext` not checking for nulls.

### Steps to reproduce
```java
	@Test
	public void onNextAndCancelRace() {
		List<Integer> list = new ArrayList<>();
		final AssertSubscriber<Object> testSubscriber = AssertSubscriber.create();

		MonoReduceSeed.ReduceSeedSubscriber<Integer, List<Integer>> sub =
				new MonoReduceSeed.ReduceSeedSubscriber<>(testSubscriber,
						(l, next) -> {
							l.add(next);
							return l;
						}, list);

		sub.onSubscribe(Operators.emptySubscription());
		sub.cancel();
		sub.onNext(1);
		testSubscriber.assertNoError(); //=> fails, NullPointerException in lambda above
	}
```

### Reactor Core version
3.1.10.RELEASE

### PR DESCRIPTION
**Pull request by simonbasle**
This commit fixes a race condition that would result in a null
being passed to the BiFunction of the seeded variant, which could
trigger a NullPointerException depending on said function.

This was due to `cancel()` nulling out the accumulated value / seed,
which was not guarded against in `onNext`.

### CODE REVIEW

File: reactor-core/src/test/java/reactor/core/publisher/MonoReduceSeedTest.java [hunk 1]
```diff
@@ -155,6 +158,28 @@ public void accumulatorReturnsNull() {
...
+				new MonoReduceSeed.ReduceSeedSubscriber<>(testSubscriber,
+						(l, next) -> {
+							l.add(next);
+							return l;
+						}, list);
+
+		sub.onSubscribe(Operators.emptySubscription());
+
+		//the race alone _could_ previously produce a NPE
+		RaceTestUtils.race(() -> sub.onNext(1), sub::cancel);
```
Comment (akarnokd) [inline reactor-core/src/test/java/reactor/core/publisher/MonoReduceSeedTest.java]: Is this helper basically syncing up two threads to execute the lambdas? The situation with race tests is that they may not happen just running once, therefore, I usually loop the whole test 1.000-10.000 times to be way more certain.

Comment (simonbasle) [reply reactor-core/src/test/java/reactor/core/publisher/MonoReduceSeedTest.java]: that's what I did initially, but then since I'm manipulating a subscriber directly I figured I could simply trigger the same conditions as in the race by doing another `sub.onNext` afterwards. I could have removed the RaceTestUtils usage entirely I guess...

**Comment by simonbasle** [comment]
@akarnokd thanks for the comment on `onError`. I'll actually make a note to change that as part of #1394
