### PR TITLE
fixes stress test expectation and bug in ColdTestPublisher

### LINKED ISSUE #3633: JCStress Test failing for `reactor.core.publisher.FluxSwitchMapStressTest.RequestAndProduceStressTest2`
```
Error:  [ERROR] reactor.core.publisher.FluxSwitchMapStressTest.RequestAndProduceStressTest2

  Results across all configurations:

  RESULT  SAMPLES     FREQ      EXPECT  DESCRIPTION
  200, 0       84   91.30%  Acceptable  Should produced exactly what was requested
  200, 1        8    8.70%  Acceptable  Should produced exactly what was requested

  Messages:
    Check test failed
    java.lang.IllegalStateException: 200, 1 [386769567455] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][sns][14][0b0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000-0b0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0010]
    [386769581151] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][ini][14][0b0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0010-0b0000_0000_0000_0000_0000_0000_0000_0001_0000_0000_0000_0000_0000_0000_0000_0000]
    [386769599615] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][sns][14][0b0000_0000_0000_0000_0000_0000_0000_0001_0000_0000_0000_0000_0000_0000_0000_0000-0b0000_0000_0000_0000_0000_0000_0000_0001_0000_0000_0000_0000_0000_0000_0000_0010]
    [386769609123] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][ini][14][0b0000_0000_0000_0000_0000_0000_0000_0001_0000_0000_0000_0000_0000_0000_0000_0010-0b0000_0000_0000_0000_0000_0000_0000_0010_0000_0000_0000_0000_0000_0000_0000_0000]
    [386769623379] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][sns][14][0b0000_0000_0000_0000_0000_0000_0000_0010_0000_0000_0000_0000_0000_0000_0000_0000-0b0000_0000_0000_0000_0000_0000_0000_0010_0000_0000_0000_0000_0000_0000_0000_0010]
    [386769632416] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][ini][14][0b0000_0000_0000_0000_0000_0000_0000_0010_0000_0000_0000_0000_0000_0000_0000_0010-0b0000_0000_0000_0000_0000_0000_0000_0011_0000_0000_0000_0000_0000_0000_0000_0000]
    [386769645841] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][sns][14][0b0000_0000_0000_0000_0000_0000_0000_0011_0000_0000_0000_0000_0000_0000_0000_0000-0b0000_0000_0000_0000_0000_0000_0000_0011_0000_0000_0000_0000_0000_0000_0000_0010]
    [386769654858] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][ini][14][0b0000_0000_0000_0000_0000_0000_0000_0011_0000_0000_0000_0000_0000_0000_0000_0010-0b0000_0000_0000_0000_0000_0000_0000_0100_0000_0000_0000_0000_0000_0000_0000_0000]
    [386769668183] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][sns][14][0b0000_0000_0000_0000_0000_0000_0000_0100_0000_0000_0000_0000_0000_0000_0000_0000-0b0000_0000_0000_0000_0000_0000_0000_0100_0000_0000_0000_0000_0000_0000_0000_0010]
    [386769682770] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][ini][14][0b0000_0000_0000_0000_0000_0000_0000_0100_0000_0000_0000_0000_0000_0000_0000_0010-0b0000_0000_0000_0000_0000_0000_0000_0101_0000_0000_0000_0000_0000_0000_0000_0000]
    [386769717375] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][sns][14][0b0000_0000_0000_0000_0000_0000_0000_0101_0000_0000_0000_0000_0000_0000_0000_0000-0b0000_0000_0000_0000_0000_0000_0000_0101_0000_0000_0000_0000_0000_0000_0000_0010]
    [386769735559] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][ini][14][0b0000_0000_0000_0000_0000_0000_0000_0101_0000_0000_0000_0000_0000_0000_0000_0010-0b0000_0000_0000_0000_0000_0000_0000_0110_0000_0000_0000_0000_0000_0000_0000_0000]
    [386769760074] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][sns][14][0b0000_0000_0000_0000_0000_0000_0000_0110_0000_0000_0000_0000_0000_0000_0000_0000-0b0000_0000_0000_0000_0000_0000_0000_0110_0000_0000_0000_0000_0000_0000_0000_0010]
    [386769776976] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][ini][14][0b0000_0000_0000_0000_0000_0000_0000_0110_0000_0000_0000_0000_0000_0000_0000_0010-0b0000_0000_0000_0000_0000_0000_0000_0111_0000_0000_0000_0000_0000_0000_0000_0000]
    [386769853539] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][sns][14][0b0000_0000_0000_0000_0000_0000_0000_0111_0000_0000_0000_0000_0000_0000_0000_0000-0b0000_0000_0000_0000_0000_0000_0000_0111_0000_0000_0000_0000_0000_0000_0000_0010]
    [386769902600] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][ini][14][0b0000_0000_0000_0000_0000_0000_0000_0111_0000_0000_0000_0000_0000_0000_0000_0010-0b0000_0000_0000_0000_0000_0000_0000_1000_0000_0000_0000_0000_0000_0000_0000_0000]
    [386769935071] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][sns][14][0b0000_0000_0000_0000_0000_0000_0000_1000_0000_0000_0000_0000_0000_0000_0000_0000-0b0000_0000_0000_0000_0000_0000_0000_1000_0000_0000_0000_0000_0000_0000_0000_0010]
    [386770000549] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][adr][16][0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0000_0000-0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0001_0000]
    [386770003268] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][ini][14][0b0000_0000_0000_0000_0000_0000_0000_1000_0000_0000_0000_0000_0000_0000_0000_0010-0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0000_0000]
    [386770019835] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][adr][16][0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0001_0000-0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0010_0000]
    [386770028164] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][sns][14][0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0010_0000-0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0010_0010]
    [386770036076] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][adr][16][0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0010_0010-0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0011_0010]
    [386770047390] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][swp][14][0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0011_0010-0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0011_0011]
    [386770051665] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][adr][16][0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0011_0011-0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0100_0011]
    [386770068456] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][adr][16][0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0100_0011-0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_0000_0101_0011]
    [386774687609] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][swp][14][0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_1100_1000_0010-0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_1100_1000_0011]
    [386774694953] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][sic][14][0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_1100_1000_0011-0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_1100_1000_0110]
    [386774702177] [reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain@85655fe][smc][14][0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_1100_1000_0110-0b0000_0000_0000_0000_0000_0000_0000_1001_0000_0000_0000_0000_0000_1100_1000_1110]
    	at reactor.core.publisher.FluxSwitchMapStressTest$RequestAndProduceStressTest2.arbiter(FluxSwitchMapStressTest.java:319)
    	at reactor.core.publisher.FluxSwitchMapStressTest_RequestAndProduceStressTest2_jcstress$TestResourceEstimator.runWith(FluxSwitchMapStressTest_RequestAndProduceStressTest2_jcstress.java:266)
    	at org.openjdk.jcstress.infra.runners.ForkedTestConfig.tryWith(ForkedTestConfig.java:126)
    	at org.openjdk.jcstress.infra.runners.ForkedTestConfig.adjustStrideCount(ForkedTestConfig.java:97)
    	at reactor.core.publisher.FluxSwitchMapStressTest_RequestAndProduceStressTest2_jcstress.jcstress_sanityCheck_Resource(FluxSwitchMapStressTest_RequestAndProduceStressTest2_jcstress.java:279)
    	at reactor.core.publisher.FluxSwitchMapStressTest_RequestAndProduceStressTest2_jcstress.sanityCheck(FluxSwitchMapStressTest_RequestAndProduceStressTest2_jcstress.java:30)
    	at org.openjdk.jcstress.infra.runners.Runner.run(Runner.java:64)
    	at org.openjdk.jcstress.ForkedMain.main(ForkedMain.java:79)
```

### PR DESCRIPTION
**Pull request by OlegDokuka**
This PR fixes an early termination bug in `ColdTestPublisher` which happens when request from the downstream subscriber races with new values and following termination which in rare case endups in termination without propagation of the remaining values.  Also this PR improves expectation for the stress test where ColdTestPulisher takes a key role

closes #3633

### CODE REVIEW

**Review by chemicL — APPROVED** [review]

File: reactor-core/src/jcstress/java/reactor/core/publisher/FluxSwitchMapStressTest.java [hunk 1]
```diff
@@ -272,7 +272,8 @@ public void arbiter(II_Result r) {
 
 	// Ignore, flaky test (https://github.com/reactor/reactor-core/issues/3633)
 	//@JCStressTest
```
Comment (chemicL) [inline reactor-core/src/jcstress/java/reactor/core/publisher/FluxSwitchMapStressTest.java:274]:
```suggestion
	@JCStressTest
```

Comment (chemicL) [reply reactor-core/src/jcstress/java/reactor/core/publisher/FluxSwitchMapStressTest.java:274]: This and the other tests can now have the ignores removed

**Review by chemicL — CHANGES_REQUESTED** [review]
I realized that the tests are effectively disabled at the moment. As this PR aims to fix the flakiness, these tests can be re-enabled.

**Review by chemicL — APPROVED** [review]

**Comment by chemicL** [comment]
The related tests can be uncommented as a follow-up.
