### PR TITLE
Dispose picked worker when BoundedElasticScheduler rejects task

### LINKED ISSUE #3182: Not decrement BoundedState MARK_COUNT if running task is rejected
Sorry for my English
## Expected Behavior
In the BoundedElasticScheduler, after an overflow and an error occur RejectedExecutionException, the thread in which the error occurred will remain executable indefinitely. 

## Actual Behavior
BoundedState no decrement MARK_COUNT (Not disposed), if scheduler reject task.

## Steps to Reproduce

```java
@Test
	public void moveToIdleAfterHaveRejectTasksAndCompleteAllTasks() throws InterruptedException {
		AtomicInteger taskRejected = new AtomicInteger();

		int maxThreads = 2;
		int maxTaskQueuedPerThread = 10;

		BoundedElasticScheduler scheduler = afterTest.autoDispose(
				new BoundedElasticScheduler(
						maxThreads,
						maxTaskQueuedPerThread,
						new ReactorThreadFactory(
								"moveToIdleAfterHaveRejectTasksAndCompleteAllTasks",
								new AtomicLong(),
								false,
								false,
								null),
						60));
		scheduler.start();

		CountDownLatch latch = new CountDownLatch(1);
		CountDownLatch tasksStartedLatch = new CountDownLatch(maxThreads);

		Runnable startedAndWaitLatchRunnable = () -> {
			try {
				tasksStartedLatch.countDown();
				latch.await(30, TimeUnit.SECONDS);
			}
			catch (InterruptedException e) {
				e.printStackTrace();
			}
		};

		Runnable waitLatchRunnable = () -> {
			try {
				latch.await(30, TimeUnit.SECONDS);
			}
			catch (InterruptedException e) {
				e.printStackTrace();
			}
		};

		//initial task that blocks the threads, causing other tasks to enter pending queue
		for (int i = 0; i < maxThreads; i++) {
			scheduler.schedule(startedAndWaitLatchRunnable);
		}

		assertThat(tasksStartedLatch.await(1, TimeUnit.SECONDS)).as("task picked").isTrue(); //small window to start the first task

		//initial all queue
		for (int i = 0; i < maxThreads * maxTaskQueuedPerThread; i++) {
			scheduler.schedule(waitLatchRunnable);
		}

		//check reject new tasks
		assertThatExceptionOfType(RejectedExecutionException.class)
				.as("must reject for method schedule without delay")
				.isThrownBy(() -> scheduler.schedule(waitLatchRunnable));
		taskRejected.incrementAndGet();

		assertThatExceptionOfType(RejectedExecutionException.class)
				.as("must reject for method schedule with delay")
				.isThrownBy(() -> scheduler.schedule(waitLatchRunnable, 100, TimeUnit.MILLISECONDS));
		taskRejected.incrementAndGet();

		assertThatExceptionOfType(RejectedExecutionException.class)
				.as("must reject for method schedulePeriodically")
				.isThrownBy(() -> scheduler.schedulePeriodically(waitLatchRunnable, 100, 100, TimeUnit.MILLISECONDS));
		taskRejected.incrementAndGet();

		assertThat(taskRejected).as("task rejected").hasValue(3);

		latch.countDown();

		Awaitility.with().pollInterval(50, TimeUnit.MILLISECONDS).pollDelay(100, TimeUnit.MILLISECONDS)
				.await().atMost(500, TimeUnit.MILLISECONDS)
				.untilAsserted(() -> assertThat(scheduler.estimateIdle())
						.as("all tasks idle after complete tasks")
						.isEqualTo(maxThreads)
				);
	}
```

## Possible Solution

Need dispose picked BoundedState when try schedule and get RejectedExecutionException
```java
   public Disposable schedule(Runnable task) {
        //tasks running once will call dispose on the BoundedState, decreasing its usage by one
        BoundedState picked = state.currentResource.pick();
        try {
            return Schedulers.directSchedule(picked.executor, task, picked, 0L, TimeUnit.MILLISECONDS);
        } catch (RejectedExecutionException ex) {
            //if task rejected need releases the BoundedState for decreases its usage by one
            picked.dispose();
            throw ex;
        }
    }
```

## Your Environment

* Reactor version(s) used: 3.3.3 AND LATEST
* JVM version (`java -version`): 11.0.14.1

### PR DESCRIPTION
**Pull request by Fearsin**
If BoundedState picked and rejected, BoundedState not decrement markCount. After RejectedExecutionException BoundedState never move to idle.

Fixes #3182.

Signed-off-by: Stanislav Kotik <STAlkerS-05@yandex.ru>
Co-authored-by: Stanislav Kotik <STAlkerS-05@yandex.ru>

### CODE REVIEW

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java [hunk 1]
```diff
@@ -1551,6 +1551,88 @@ void toStringOfExecutorReflectsIdleVsActive() throws InterruptedException {
...
+		Runnable waitLatchRunnable = () -> {
+			try {
+				latch.await(30, TimeUnit.SECONDS);
+			}
+			catch (InterruptedException e) {
+				e.printStackTrace();
+			}
+		};
+
+		//initial task that blocks the threads, causing other tasks to enter pending queue
```
Comment (chemicL) [inline reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java:1596]: //initial task that blocks the threads, causing other tasks to enter pending queue

->

    // initial tasks that block the threads, causing other tasks to enter the pending queue

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java [hunk 2]
```diff
@@ -1551,6 +1551,88 @@ void toStringOfExecutorReflectsIdleVsActive() throws InterruptedException {
...
+		for (int i = 0; i < maxThreads; i++) {
+			scheduler.schedule(startedAndWaitLatchRunnable);
+		}
+
+		assertThat(tasksStartedLatch.await(1, TimeUnit.SECONDS)).as("task picked").isTrue(); //small window to start the first task
+
+		//initial all queue
```
Comment (chemicL) [inline reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java:1603]: //initial all queue

->

    // fill up pending queue

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java [hunk 3]
```diff
@@ -1551,6 +1551,88 @@ void toStringOfExecutorReflectsIdleVsActive() throws InterruptedException {
...
+		for (int i = 0; i < maxThreads * maxTaskQueuedPerThread; i++) {
+			scheduler.schedule(waitLatchRunnable);
+		}
+
+		//check reject new tasks
```
Comment (chemicL) [inline reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java:1608]: check reject new tasks

->

    check new tasks are rejected

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java [hunk 4]
```diff
@@ -1551,6 +1551,88 @@ void toStringOfExecutorReflectsIdleVsActive() throws InterruptedException {
...
+		taskRejected.incrementAndGet();
+
+		assertThat(taskRejected).as("task rejected").hasValue(3);
+
+		latch.countDown();
+
+		Awaitility.with().pollInterval(50, TimeUnit.MILLISECONDS).pollDelay(100, TimeUnit.MILLISECONDS)
+				.await().atMost(500, TimeUnit.MILLISECONDS)
+				.untilAsserted(() -> assertThat(scheduler.estimateIdle())
+						.as("all tasks idle after complete tasks")
```
Comment (chemicL) [inline reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java:1631]: all tasks idle after complete tasks

->

    all BoundedStates are idle after all pending tasks finish

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java [hunk 5]
```diff
@@ -1551,6 +1551,88 @@ void toStringOfExecutorReflectsIdleVsActive() throws InterruptedException {
...
+		assertThatExceptionOfType(RejectedExecutionException.class)
+				.as("must reject for method schedulePeriodically")
+				.isThrownBy(() -> scheduler.schedulePeriodically(waitLatchRunnable, 100, 100, TimeUnit.MILLISECONDS));
+		taskRejected.incrementAndGet();
+
+		assertThat(taskRejected).as("task rejected").hasValue(3);
+
+		latch.countDown();
+
+		Awaitility.with().pollInterval(50, TimeUnit.MILLISECONDS).pollDelay(100, TimeUnit.MILLISECONDS)
```
Comment (chemicL) [inline reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java:1628]: Consider lowering the values, 100ms is quite a long time considering the amount of tests. I'd assume the tasks to finish quicker after the latch is released.

**Comment by chemicL** [comment]
Also, it might not be codified, but seems we're using the style of

    // comment

vs
    //comment

which looks cleaner.

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 6]
```diff
@@ -252,14 +252,26 @@ public Mono<Void> disposeGracefully() {
 	public Disposable schedule(Runnable task) {
 		//tasks running once will call dispose on the BoundedState, decreasing its usage by one
 		BoundedState picked = state.currentResource.pick();
-		return Schedulers.directSchedule(picked.executor, task, picked, 0L, TimeUnit.MILLISECONDS);
+		try {
+			return Schedulers.directSchedule(picked.executor, task, picked, 0L, TimeUnit.MILLISECONDS);
+		} catch (RejectedExecutionException ex) {
+			//if task rejected need releases the BoundedState for decreases its usage by one
```
Comment (chemicL) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java:258]:
```suggestion
			// ensure to free the BoundedState so it can be reused
```

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 7]
```diff
@@ -252,14 +252,26 @@ public Mono<Void> disposeGracefully() {
...
 
 	@Override
 	public Disposable schedule(Runnable task, long delay, TimeUnit unit) {
 		//tasks running once will call dispose on the BoundedState, decreasing its usage by one
 		final BoundedState picked = state.currentResource.pick();
-		return Schedulers.directSchedule(picked.executor, task, picked, delay, unit);
+		try {
+			return Schedulers.directSchedule(picked.executor, task, picked, delay, unit);
+		} catch (RejectedExecutionException ex) {
+			//if task rejected need releases the BoundedState for decreases its usage by one
```
Comment (chemicL) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java:271]:
```suggestion
			// ensure to free the BoundedState so it can be reused
```

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java [hunk 8]
```diff
@@ -268,14 +280,20 @@ public Disposable schedulePeriodically(Runnable task,
...
+			Disposable scheduledTask = Schedulers.directSchedulePeriodically(picked.executor,
+					task,
+					initialDelay,
+					period,
+					unit);
+			//a composite with picked ensures the cancellation of the task releases the BoundedState
+			// (ie decreases its usage by one)
+			return Disposables.composite(scheduledTask, picked);
+		} catch (RejectedExecutionException ex) {
+			//if task rejected need releases the BoundedState for decreases its usage by one
```
Comment (chemicL) [inline reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java:293]:
```suggestion
			// ensure to free the BoundedState so it can be reused
```

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java [hunk 9]
```diff
@@ -1551,6 +1551,88 @@ void toStringOfExecutorReflectsIdleVsActive() throws InterruptedException {
 		}
 	}
 
+	@Test
+	public void moveToIdleAfterHaveRejectTasksAndCompleteAllTasks() throws InterruptedException {
```
Comment (chemicL) [inline reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java:1555]:
```suggestion
	public void transitionsToIdleAfterRejectionAndFollowingCompletion() throws InterruptedException {
```

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java (hunk 1 above)
Comment (chemicL) [inline reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java:1596]:
```suggestion
		// initial tasks that block the threads, causing other tasks to enter the pending queue
```

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java (hunk 2 above)
Comment (chemicL) [inline reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java:1603]:
```suggestion
		// fill up pending queue
```

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java (hunk 3 above)
Comment (chemicL) [inline reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java:1608]:
```suggestion
		// check new tasks are rejected
```

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java (hunk 4 above)
Comment (chemicL) [inline reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java:1631]:
```suggestion
						.as("all BoundedStates are idle after all pending tasks finish")
```

**Review by OlegDokuka — APPROVED** [review]

**Comment by OlegDokuka** [comment]
@Fearsin LGTM with minor comments from @chemicL.

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java [hunk 10]
```diff
@@ -1551,6 +1551,88 @@ void toStringOfExecutorReflectsIdleVsActive() throws InterruptedException {
...
+		AtomicInteger taskRejected = new AtomicInteger();
```
[the remark this answers is not in the document]
Comment (Fearsin) [reply reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java]: Done

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java [hunk 11]
```diff
@@ -1551,6 +1551,88 @@ void toStringOfExecutorReflectsIdleVsActive() throws InterruptedException {
...
+						new ReactorThreadFactory(
+								"moveToIdleAfterHaveRejectTasksAndCompleteAllTasks",
+								new AtomicLong(),
+								false,
+								false,
+								null),
+						60));
+		scheduler.start();
+
+		CountDownLatch latch = new CountDownLatch(1);
```
[the remark this answers is not in the document]
Comment (Fearsin) [reply reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java]: Done

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java (hunk 5 above)
Comment (Fearsin) [reply reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java]: Done

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java (hunk 6 above)
Comment (Fearsin) [reply reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: Done

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java (hunk 7 above)
Comment (Fearsin) [reply reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: Done

File: reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java (hunk 8 above)
Comment (Fearsin) [reply reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java]: Done

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java (hunk 9 above)
Comment (Fearsin) [reply reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java]: Done

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java (hunk 1 above)
Comment (Fearsin) [reply reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java]: Done

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java (hunk 2 above)
Comment (Fearsin) [reply reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java]: Done

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java (hunk 3 above)
Comment (Fearsin) [reply reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java]: Done

File: reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java (hunk 4 above)
Comment (Fearsin) [reply reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java]: Done

**Review by OlegDokuka — APPROVED** [review]

**Review by chemicL — APPROVED** [review]
Thanks for addressing the comments. LGTM 🚢

**Review by simonbasle — APPROVED** [review]
thanks for the contribution (and good job on the retargetting to 3.4.x), LGTM 👍
