### PR TITLE
fix #1853 Prevent some Mono operators to trigger onNext+onError

### LINKED ISSUE #1853: A few Mono operators can lead to bad signal combination of onNext+onError
## Expected Behavior
`Mono` authorized sequences of events are `onNext`+`onComplete`, `onComplete` or `onError` (also, technically, infinite Monos with `onNext` or no signal at all).

`onNext` should never be followed by `onError`.

## Actual Behavior
`Mono.just("foo").doOnTerminate(() -> { throw new IllegalStateException(); })` results in the undesirable signals sequence.

`Mono.using` with a `completeHandler` that throws similarly produces bad signals.

## Possible Solution
-  for `Mono#doOnComplete`, rework into an alias to `doOnSuccessOrError` that ignores both inputs, make it prominent in the javadoc (ie. `onNext` is discarded rather than propagated if the callback fails, and thus the callback is executed _before_ `actual.onNext` rather than between onNext and onComplete)
 - for `Mono#using`, like `usingWhen` it would delay the emission of `onNext` to until the `onComplete` handler has finished.

Relates to #1832

### PR DESCRIPTION
**Pull request by simonbasle**
This commit slightly changes the behavior of Mono#using so that, in
eager mode, the cleanup is applied inside `onNext`. Thus it is applied
before the value is passed to downstream (which at this point is no
longer in the protected scope of the `sourceSupplier`).

This is done to prevent the case where the value would be passed down
yet the cleanup throws, resulting in an invalid sequence of onNext then
onError signals.

### CODE REVIEW

**Comment by simonbasle** [comment]
@smaldini I'm not sure of what I've done on `MonoUsing` with regard to fusion.

File: reactor-core/src/main/java/reactor/core/publisher/Mono.java [hunk 1]
```diff
@@ -2216,7 +2222,9 @@ public T block(Duration timeout) {
 	 */
 	public final Mono<T> doOnError(Consumer<? super Throwable> onError) {
 		Objects.requireNonNull(onError, "onError");
-		return doOnSignal(this, null, null, onError, null, null, null);
+		return doOnSuccessOrError((ignoreValue, error) -> {
```
Comment (smaldini) [inline reactor-core/src/main/java/reactor/core/publisher/Mono.java]: Do we need to change doOnError , if we observe an error in a mono flow it's already too late for propagating any other signal ?

File: reactor-core/src/main/java/reactor/core/publisher/Mono.java [hunk 2]
```diff
@@ -2235,9 +2243,12 @@ public T block(Duration timeout) {
 	public final <E extends Throwable> Mono<T> doOnError(Class<E> exceptionType,
 			final Consumer<? super E> onError) {
 		Objects.requireNonNull(exceptionType, "type");
-		@SuppressWarnings("unchecked")
-		Consumer<Throwable> handler = (Consumer<Throwable>)onError;
-		return doOnError(exceptionType::isInstance, handler);
+		Objects.requireNonNull(onError, "onError");
+		return doOnTerminalSignal(this, null,
```
Comment (smaldini) [inline reactor-core/src/main/java/reactor/core/publisher/Mono.java]: See above comment on doOnError

File: reactor-core/src/main/java/reactor/core/publisher/Mono.java [hunk 3]
```diff
@@ -2254,11 +2265,12 @@ public T block(Duration timeout) {
 	public final Mono<T> doOnError(Predicate<? super Throwable> predicate,
 			final Consumer<? super Throwable> onError) {
 		Objects.requireNonNull(predicate, "predicate");
-		return doOnError(t -> {
-			if (predicate.test(t)) {
-				onError.accept(t);
-			}
-		});
+		Objects.requireNonNull(onError, "onError");
```
Comment (smaldini) [inline reactor-core/src/main/java/reactor/core/publisher/Mono.java]: See above comment on doOnError

File: reactor-core/src/main/java/reactor/core/publisher/MonoPeekTerminal.java [hunk 4]
```diff
@@ -378,12 +343,14 @@ public T poll() {
...
 		@Override
 		public boolean isEmpty() {
-			return queueSubscription.isEmpty();
+			return queueSubscription == null || queueSubscription.isEmpty();
 		}
 
 		@Override
 		public void clear() {
-			queueSubscription.clear();
+			if (queueSubscription != null) {
```
Comment (smaldini) [inline reactor-core/src/main/java/reactor/core/publisher/MonoPeekTerminal.java]: These kind of checks are usually redundant as they are called only if fuseable. Wouldn't be covered by normal test coverage.

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/MonoPeekTerminal.java]: I wanted to get rid of the pesky nullability warnings from static analysis... maybe an `assert queueSubscription != null` would be better overhead-wise?

File: reactor-core/src/main/java/reactor/core/publisher/Mono.java (hunk 1 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/Mono.java]: actually, this one should be changed to `doOnTerminalSignal(..., onError)`: no allocation for the individual handlers (success or error) in the new version of `MonoPeekTerminal`. I included this change because it aligns all onComplete/onError signals into a single operator.

File: reactor-core/src/main/java/reactor/core/publisher/MonoPeekTerminal.java (hunk 4 above)
Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/MonoPeekTerminal.java]: actually, isn't it safer to keep these checks, especially as the number of hybrid `Subscribers` that are instantiated for both `Fuseable` and non-fuseable versions grow? I expect the JVM to optimize these checks out at runtime anyway.

Comment (simonbasle) [reply reactor-core/src/main/java/reactor/core/publisher/MonoPeekTerminal.java]: right. I was thinking about discard scenarios where we can call `Queue::clear` by default, but these should be managed by the original subscription anyway...
