### PR TITLE
fix #1968 Make FluxPublish propagate 1st subscriber context

### LINKED ISSUE #1968: FluxPublish does not propagate subscriber context
## Expected Behavior

`FluxPublish` should propagate the first subscriber context, as, for example, `FluxReplay` does, after #1114 got fixed.

## Actual Behavior

`FluxPublish` does not propagate any subscriber context.

## Steps to Reproduce

```java
@Test
public void subscriberContextPropagation() {
	String key = "key";
	int expectedValue = 1;
	Flux<Integer> integerFlux =
			Flux.just(1, 2, 3)
			    .flatMap(value ->
					    Mono.subscriberContext()
					        .doOnNext(context -> assertThat((int) conte
							        .isEqualTo(expectedValue)
					        )
					        .thenReturn(value)
			    )
			    .publish()
			    .autoConnect(2);
	integerFlux.subscriberContext(Context.of(key, expectedValue))
	           .subscribe();
	integerFlux.subscriberContext(Context.of(key, 2))
	           .subscribe();
}
```

## Possible Solution

Override `CoreSubscriber.currentContext()` in `FluxPublish.PublishSubscriber`:
```java
@Override
public Context currentContext() {
	return Operators.multiSubscribersContext(subscribers);
}
```
## Your Environment

* Reactor version(s) used: `3.3.0.RELEASE`
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`):
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (Zulu 8.42.0.21-CA-macosx) (build 1.8.0_232-b18)
OpenJDK 64-Bit Server VM (Zulu 8.42.0.21-CA-macosx) (build 25.232-b18, mixed mode)
```
* OS and version (eg `uname -a`):
```
Darwin 192-168-0-196.rdsnet.ro 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
```

### PR DESCRIPTION
**Pull request by andreisilviudragnea**
According to issue #1114, it looks like the FluxPublish operator should propagate the first subscriber context too.

This PR is a fix for #1968.

I will rebase the branch over the earliest relevant maintenance branch when it is decided.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@andreisilviudragnea Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1969)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=1969) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@andreisilviudragnea Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1969)!

File: reactor-core/src/main/java/reactor/core/publisher/FluxPublish.java [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2011-2018 Pivotal Software Inc, All Rights Reserved.
+ * Copyright (c) 2011-2019 Pivotal Software Inc, All Rights Reserved.
```
Comment (bsideup) [inline reactor-core/src/main/java/reactor/core/publisher/FluxPublish.java]:
```suggestion
 * Copyright (c) 2011-Present Pivotal Software Inc, All Rights Reserved.
```

File: reactor-core/src/test/java/reactor/core/publisher/FluxPublishTest.java [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2011-2018 Pivotal Software Inc, All Rights Reserved.
+ * Copyright (c) 2011-2019 Pivotal Software Inc, All Rights Reserved.
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/FluxPublishTest.java]:
```suggestion
 * Copyright (c) 2011-Present Pivotal Software Inc, All Rights Reserved.
```

File: reactor-core/src/test/java/reactor/core/publisher/FluxPublishTest.java [hunk 3]
```diff
@@ -720,4 +721,28 @@ public void removeUnknownInnerIgnored() {
...
+	@Test
+	public void subscriberContextPropagation() {
+		String key = "key";
+		int expectedValue = 1;
+
+		Flux<Integer> integerFlux =
+				Flux.just(1, 2, 3)
+				    .flatMap(value ->
+						    Mono.subscriberContext()
+						        .doOnNext(context -> assertThat((int) context.get(key))
```
Comment (bsideup) [inline reactor-core/src/test/java/reactor/core/publisher/FluxPublishTest.java]: To avoid false positives, could you please make an assertion outside of the reactive chain (e.g. by capturing the context and doing the `assertThat` call after `subscribe()`s?

**Comment by bsideup** [comment]
@simonbasle should we target `3.2.x` branch?

**Comment by simonbasle** [comment]
Thanks for the report and PR @andreisilviudragnea 
Yes, please target the `3.2.x` branch :bow:

File: reactor-core/src/test/java/reactor/core/publisher/FluxPublishTest.java (hunk 3 above)
Comment (andreisilviudragnea) [reply reactor-core/src/test/java/reactor/core/publisher/FluxPublishTest.java]: Is it ok using an `AtomicReference`?

File: reactor-core/src/main/java/reactor/core/publisher/FluxPublish.java (hunk 1 above)
Comment (andreisilviudragnea) [reply reactor-core/src/main/java/reactor/core/publisher/FluxPublish.java]: Done

File: reactor-core/src/test/java/reactor/core/publisher/FluxPublishTest.java (hunk 2 above)
Comment (andreisilviudragnea) [reply reactor-core/src/test/java/reactor/core/publisher/FluxPublishTest.java]: Done
