### PR TITLE
Fixes #86. Add mapOrFilter operator.

### LINKED ISSUE #86: Flux.map() and null-handling when wrapping existing blocking API's
The only way to do this currently is via the use of `flatMap` and `Mono.justOrEmpty()` which isn't as efficient and causes more allocations/stack.

One option is to introduce something in Flux e.g. `Flux.mapOrEmpty()` that behaves the same as `map` but drops message and does `request(1)` when null is returned, but I understand this clutters the primary API where nulls simply are not allowed.  So maybe an alternative is to implement something outside of Flux in something like `LegacyUtils` that can then somehow be pulled into and used in a Flux stream just in the cases where you need to deal with legacy API's that throw exceptions/return null.

This is somewhat related to: https://github.com/reactor/reactor-core/issues/80

### PR DESCRIPTION
**Pull request by dfeist**

### CODE REVIEW

File: src/main/java/reactor/core/publisher/FluxMapOrFilter.java [hunk 1]
```diff
@@ -0,0 +1,313 @@
...
+			try {
+				v = mapper.apply(t);
+			} catch (Throwable e) {
+				done = true;
+				onError(Exceptions.mapOperatorError(s, e, t));
+				return true;
+			}
+
+			if (v == null) {
+				done = true;
```
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilter.java]: If v is null, just return with false; the upstream will send a new value.

File: src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java [hunk 2]
```diff
@@ -0,0 +1,437 @@
...
+			s.cancel();
+		}
+
+		@Override
+		public R poll() {
+			T v = s.poll();
+			if (v != null) {
+				R u = mapper.apply(v);
+				if (u == null) {
+					throw new NullPointerException();
```
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: I though you want to skip null-mapped values from upstream. Take some inspiration from `FluxFilterFuseable`.

File: src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java [hunk 3]
```diff
@@ -0,0 +1,437 @@
...
+	
+				try {
+					v = mapper.apply(t);
+				} catch (Throwable e) {
+					onError(Exceptions.mapOperatorError(s, e, t));
+					return;
+				}
+	
+				if (v == null) {
+					done = true;
```
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: Request 1 instead of throwing?

File: src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java [hunk 4]
```diff
@@ -0,0 +1,437 @@
...
+	
+				try {
+					v = mapper.apply(t);
+				} catch (Throwable e) {
+					onError(Exceptions.mapOperatorError(s, e, t));
+					return true;
+				}
+	
+				if (v == null) {
+					done = true;
```
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: return false

File: src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java [hunk 5]
```diff
@@ -0,0 +1,437 @@
...
+			s.cancel();
+		}
+
+		@Override
+		public R poll() {
+			T v = s.poll();
+			if (v != null) {
+				R u = mapper.apply(v);
+				if (u == null) {
+					throw new NullPointerException();
```
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: Same as above with the regular, fused poll.

File: src/test/java/reactor/core/publisher/FluxMapOrFilterTest.java [hunk 6]
```diff
@@ -0,0 +1,57 @@
...
+		TestSubscriber<Integer> ts = TestSubscriber.create();
+
+		Flux.range(1, 5).mapOrFilter(v -> v % 2 == 0 ? v * 2 : null).subscribe(ts);
+
+		Set<Integer> expectedValues = new HashSet<>(Arrays.asList(4, 8));
+		ts.assertContainValues(expectedValues)
+			.assertNoError()
+			.assertComplete();
+	}
+
```
Comment (akarnokd) [inline src/test/java/reactor/core/publisher/FluxMapOrFilterTest.java]: Please add tests that invoke `ts.requestedFusionMode(Fuseable.ANY)` and then `.assertFuseableSource().assertFusionMode(Fuseable.SYNC)`

**Comment by dfeist** [comment]
@akarnokd Pushed updates, I'd completely skipped some of the fuseable stuff :-(  I need to read your fused operators blogpost in detail.  Question: How can i test that ASYNC fusion mode code path?

**Comment by akarnokd** [comment]
There should be an `UnicastProcessor` somewhere unless @smaldini hid it.

**Comment by dfeist** [comment]
`UnicastProcessor` still exists but you need to give it a queue etc.  I found i could use ASYNC fusion with `.publishOn(Schedulers.single())` so used that instead.

File: src/main/java/reactor/core/publisher/FluxMapOrFilter.java [hunk 7]
```diff
@@ -0,0 +1,310 @@
...
+		}
+		if (s instanceof Fuseable.ConditionalSubscriber) {
+			Fuseable.ConditionalSubscriber<? super R> cs = (Fuseable.ConditionalSubscriber<? super R>) s;
+			source.subscribe(new MapOrFilterConditionalSubscriber<>(cs, mapper));
+			return;
+		}
+		source.subscribe(new MapOrFilterSubscriber<>(s, mapper));
+	}
+
+	static final class MapOrFilterSubscriber<T, R>
```
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilter.java]: You can also implement `ConditionalSubscriber` to avoid `request(1)`s.

File: src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java [hunk 8]
```diff
@@ -0,0 +1,450 @@
...
+		@Override
+		public R poll() {
+			if (sourceMode == ASYNC) {
+				long dropped = 0;
+				for (;;) {
+					T v = s.poll();
+					if(v != null) {
+						R u = mapper.apply(v);
+						if (u == null) {
+							if (dropped != 0) {
```
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: This should also happen on the v == null path because otherwise all the dropped elements won't get replenished (I'll fix `filter`)

File: src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java [hunk 9]
```diff
@@ -0,0 +1,450 @@
...
+		}
+		
+		@Override
+		public void cancel() {
+			s.cancel();
+		}
+
+		@Override
+		public R poll() {
+			T v = s.poll();
```
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: This needs fixing as well.

File: src/main/java/reactor/core/publisher/FluxMapOrFilter.java [hunk 10]
```diff
@@ -0,0 +1,332 @@
...
+			if (Operators.validate(this.s, s)) {
+				this.s = s;
+
+				actual.onSubscribe(this);
+			}
+		}
+
+		@Override
+		public void onNext(T t) {
+			if (done) {
```
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilter.java]: You can simplify this method by calling `tryOnNext`:

```java
if (!tryOnNext(t)) {
    s.request(1);
}
```

File: src/main/java/reactor/core/publisher/FluxMapOrFilter.java (hunk 7 above)
Comment (dfeist) [inline src/main/java/reactor/core/publisher/FluxMapOrFilter.java]: Updated. `request(1)` still needs to be used in `onNext()` though.  Could `ConditionalSubscriber` have a default implementation of `onNext()` that uses `tryOnNext()`?

File: src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java (hunk 8 above)
Comment (dfeist) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: I'll wait for you to fix FluxFilterFusable, to be sure I'm fixing this correctly..

File: src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java (hunk 9 above)
Comment (dfeist) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: What needs fixing here?

File: src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java (hunk 8 above)
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: Apparently it's already correct: https://github.com/reactor/reactor-core/blob/master/src/main/java/reactor/core/publisher/FluxFilterFuseable.java#L207

File: src/main/java/reactor/core/publisher/FluxMapOrFilter.java (hunk 10 above)
Comment (dfeist) [inline src/main/java/reactor/core/publisher/FluxMapOrFilter.java]: Can do that, but see my comment about default method in interface, as this code is duplicated in almost all operator implementation.

File: src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java (hunk 9 above)
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: This has to be a loop as well, plus handle the fusion modes.

File: src/main/java/reactor/core/publisher/FluxMapOrFilter.java (hunk 10 above)
Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilter.java]: Can't default it because it needs to access the `Subscription s` which is not available in an interface.

Comment (dfeist) [inline src/main/java/reactor/core/publisher/FluxMapOrFilter.java]: 👍

File: src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java (hunk 9 above)
Comment (dfeist) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: reactor.core.publisher.FluxMapFuseable.MapFuseableSubscriber#poll doesn't do any of that, I assume thats because there is no conditional request() etc though? Or is this missing from FluxMapFuseable?

Comment (akarnokd) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: You should have based it on Filter internals because that's the dominant behavior.

Comment (dfeist) [inline src/main/java/reactor/core/publisher/FluxMapOrFilterFuseable.java]: Yup. I see that now :-)

**Comment by smaldini** [comment]
I'll merge and rework it into handle()

**Comment by mpolajnar** [comment]
I'm sorry to comment on such an old ticket, but how exactly does handle() replace mapOrFilter()? As I see it, the flatMap() approach is simpler than handle() when interfacing with non-reactive API, and flatMap() being cumbersome for this usecase was the main motivation to implement mapOrFilter()...

**Comment by simonbasle** [comment]
True, `handle` has almost as much ceremony as `flatMap` for the map-or-filter case, but `flatMap` necessitate to wrap the result in a `Mono` and has more overhead than handle, since it needs to accommodate for multiple values being emitted for a single source element.

`handle` on the other hand is covering the simpler case of "1 or 0 element for each source element". The use of a helper method would allow you to easily adapt a `Predicate`+`Function` api or a `@Nullable Function` api: 

```java
public static BiConsumer<T, SynchronousSink<R>> mapOrFilter(Function<T, R> nullableFunction) {
  return (t, sink) -> {
    R value = nullableFunction.apply(t);
    if (value != null) sink.next(value);
  }
}

public static BiConsumer<T, SynchronousSink<R>> mapOrFilter(Predicate<T> predicate, Function<T, R> transform) {
  return (t, sink) -> {
    if (check.test(t)) sink.next(transform.apply(t));
  }
}

source.handle(mapOrFilter(myPredicate, nonNullTransform));
source.handle(mapOrFilter(nullableTransform));
```
