### PR TITLE
Account for source disconnection in refCountGrace

### LINKED ISSUE #2649: FluxRefCountGrace doesn't mark it's source as terminated if an error signal occurs during the grace period
## Expected Behavior

If an error signal occurs on a source that is using `FluxRefCountGrace` during the grace period when there are zero subscribers, there is no listener to observe the error signal and realize that the source has terminated

## Actual Behavior

A new subscriber after an error occurred during the grace period should re-establish a new connection to the source

## Steps to Reproduce

If you enable `share` instead of `.publish().refCount(1, ...)`, the test passes.

```java
import org.junit.jupiter.api.Test;
import reactor.core.publisher.Flux;
import reactor.test.StepVerifier;

import java.time.Duration;

public class FluxRefCountGraceTest {

    @Test
    void shouldReconnect() {
        StepVerifier.withVirtualTime(() -> Flux.concat(Flux.just("hello"),
                                                       Flux.error(() -> new RuntimeException("boom"))
                                                           .delayElements(Duration.ofSeconds(5)))
                                               .log()
//                                               .share()
                                               .publish()
                                               .refCount(1, Duration.ofSeconds(10))
                                               .take(1)
                                               .repeat(1)
                                     .log()
        )
                    .expectNext("hello")
                    .thenAwait(Duration.ofSeconds(7))
                    .expectNext("hello")
                    .expectComplete()
                    .verify(Duration.ofSeconds(10));
    }
}
```

* reactor-core 3.4.3

### PR DESCRIPTION
**Pull request by simonbasle**
This commit changes how FluxRefCountGrace evaluates if the connection
is terminated, by taking into account the case where the source
ConnectableFlux has itself disposed the connection (by checking if
the held `Disposable` that represents said connection is disposed).

This fixes a hanging situation when used in combination with publish.

Fixes #2649.

### CODE REVIEW

**Comment by simonbasle** [comment]
this is indeed a bug in the sense that `FluxRefCountGrace` only registers internal termination of its `RefConnection`. When the `Disposable` held by the `RefConnection` is marked as `isDisposed()`, which represents the source `ConnectableFlux`'s own disconnection, the operators doesn't register that.

It only happens with `publish()`, and hangs because `publish()` never gets another `connect()` instruction due to the above. With `replay()`, it doesn't hang because the terminal signal is replayed to the second subscription.

I took the liberty of amending your test a bit, would you still say this is a fair representation of your issue @osi ?

File: reactor-core/src/test/java/reactor/core/publisher/FluxRefCountGraceTest.java [hunk 1]
```diff
@@ -35,6 +35,153 @@
...
+		            .expectNext("[0,onNext(hello)]")
+		            .expectNext("[0,onComplete()]")
+		            .expectComplete()
+		            .verify(Duration.ofMillis(500));
+
+		assertThat(sourceSubscriptions).as("source subscriptions").hasValue(1);
+	}
+
+	@Test
+	void shouldReconnect() {
```
Comment (simonbasle) [inline reactor-core/src/test/java/reactor/core/publisher/FluxRefCountGraceTest.java:169]: if the above tests satisfy you @osi I'll probably remove this one

Comment (osi) [reply reactor-core/src/test/java/reactor/core/publisher/FluxRefCountGraceTest.java:169]: They look good. Your tests are more comprehensive than what I had put together to demonstrate the problem (distilled from a larger body of work).

**Review by OlegDokuka — APPROVED** [review]
LGTM
